#!/usr/bin/env python3
"""Build complete localization.dart from part1 + generated translations."""
import os, re

D = os.path.dirname(__file__)
P1 = os.path.join(D, 'frontend', 'lib', 'core', 'localization_part1.dart')
OUT = os.path.join(D, 'frontend', 'lib', 'core', 'localization.dart')

with open(P1, 'r', encoding='utf-8') as f:
    content = f.read()

# Fix truncated line
old = "'please_enter_phone': 'J\u1ecdw\u1ecd t"
new = "'please_enter_phone': 'J\u1ecdw\u1ecd t\u1eb9 n\u1ecdmba foonu r\u1eb9 sii',"
content = content.replace(old, new)

# Find the end of Yoruba section
# The file structure is: en{...}, yo{...}, (then we need ig{...}, ha{...}, delegate, extension)
# Find where yo section ends (last '}," before ig or end)
lines = content.split('\n')

# Find the yo closing line
yo_end = -1
for i in range(len(lines)-1, -1, -1):
    if lines[i].strip() == '},' and i > 100:  # yo section ends with },
        # Check if we're past the en section
        en_end = -1
        for j in range(i-1, -1, -1):
            if lines[j].strip() == '},' and j > 10:
                en_end = j
                break
        if en_end > 0 and en_end < i:
            yo_end = i
            break

if yo_end < 0:
    # Fallback: find 'yo' section start and find its closing
    yo_start = -1
    for i, l in enumerate(lines):
        if "'yo': {" in l:
            yo_start = i
            break
    if yo_start >= 0:
        # Find matching closing brace
        depth = 0
        for i in range(yo_start, len(lines)):
            depth += lines[i].count('{') - lines[i].count('}')
            if depth <= 0:
                yo_end = i
                break

print(f"yo_end line: {yo_end}")

# Base content = everything up to and including yo_end
base_lines = lines[:yo_end+1] if yo_end > 0 else lines

# ====== MISSING YORUBA KEYS (99 keys) ======
# These are the keys present in English but missing from Yoruba
yo_missing = {
    'please_enter_password': 'J\u1ecdw\u1ecd t\u1eb9 \u1ecdr\u1ecdm\u1ecdm\u1ecd as\u1ecdp\u1ecd r\u1eb9 sii',
    'password_min_chars': '\u1eccr\u1ecdm\u1ecdm\u1ecd as\u1ecdp\u1ecd gb\u1ecdd\u1ecdd\u1ecdd k\u1ecd \u00f3 k\u00e9r\u1eb9 sii ju \u00e0\u1e63\u1eb9',
    'emergency_tools': 'Aw\u1ecdn irin\u1e63\u1eb9 pajawiri',
    'broadcasts': 'Aw\u1ecdn igbohunsafefe',
    'radio': 'Redio',
    'data_sync': 'Amu\u1e63i\u1e63i data',
    'syncing': '\u00ccm\u00fa\u1e63i\u1e63i',
    'pending_items': 'Aw\u1ecdn nkan ti o nduro',
    'peers_connected': 'Aw\u1ecdn ẹlẹgbẹ ti a sopọ',
    'sos_sent_silently': 'SOS ti firanṣẹ ni ipalọlọ',
    'sos_failed': 'SOS kuna',
    'send_sos_alert_title': 'Firanṣẹ itaniji SOS',
    'alert_type': 'Iru itaniji',
    'select_alert_type': 'Yan iru itaniji',
    'description_optional': 'Apejuwe (aṣayan)',
    'capture_evidence_optional': 'Gba ẹri (aṣayan)',
    'photo': 'Fọto',
    'video': 'Fidio',
    'audio': 'Ohun',
    'sending_in_seconds': 'Firanṣẹ ni {} aaya',
    'tap_to_send_alert': 'Tẹ lati firanṣẹ itaniji',
    'ai_analyzing': 'AI n ṣe itupalẹ...',
    'distress_detected': 'Wahala ti a rii',
    'no_distress_detected': 'Ko si wahala ti a rii',
    'priority': 'Pataki',
    'confidence': 'Igbagbọ',
    'alert_broadcast_channels': 'Awọn ikanni igbohunsafefe itaniji',
    'your_location_sent': 'Ipo rẹ ti firanṣẹ',
    'failed_to_send_sos': 'Kuna lati firanṣẹ SOS',
    'permissions_required': 'Awọn igbanilaaye ti a beere',
    'location': 'Ipo',
    'bluetooth': 'Bluetooth',
    'storage': 'Ibi ipamọ',
    'unread_messages': 'Awọn ifiranṣẹ ti a ko ka',
    'active_alerts': 'Awọn itaniji ti nṣiṣe lọwọ',
    'recent_messages': 'Awọn ifiranṣẹ aipẹ',
    'no_recent_messages': 'Ko si awọn ifiranṣẹ aipẹ',
    'open_inbox': 'Ṣii apoti ifiranṣẹ',
    'unknown_sender': 'Olufiranṣẹ aimọ',
    'medical_info': 'Alaye iṣoogun',
    'privacy_security': 'Aṣiri ati Aabo',
    'stealth_mode_sos': 'Ipo SOS ni ikoko',
    'silent_panic_trigger': 'Ikọlu ipalọlọ',
    'stealth_mode_description': 'Ipo ikoko n gba ọ laaye lati firanṣẹ itaniji laisi ṣiṣi apoti ifiranṣẹ',
    'close': 'Pa',
    'save': 'Fipamọ',
    'name': 'Orukọ',
    'phone': 'Foonu',
    'profile_updated': 'Profaili ti imudojuiwọn',
    'medical_info_saved': 'Alaye iṣoogun ti fipamọ',
    'blood_type': 'Iru ẹjẹ',
    'allergies': 'Awọn aleji',
    'medications': 'Awọn oogun',
    'medical_conditions': 'Awọn ipo iṣoogun',
    'add_contact': 'Fi olubasọrọ kun',
    'edit_contact': 'Ṣatunkọ olubasọrọ',
    'no_contacts': 'Ko si awọn olubasọrọ',
    'read_privacy_policy': 'Ka eto aṣiri',
    'open_full_map': 'Ṣii maapu ni kikun',
    'zones_nearby': 'Awọn agbegbe nitosi',
    'failed_to_load': 'Kuna lati gbe',
    'change_language': 'Yi ede pada',
    'english': 'Gẹ̀ẹ́sì',
    'yoruba': 'Yorùbá',
    'igbo': 'Igbo',
    'hausa': 'Hausa',
    'trapped': 'Idẹkùn',
    'lost': 'Pàdánù',
    'structural_damage': 'Ibajẹ igbekalẹ',
    'other_emergency': 'Pajawiri miiran',
    'general_emergency': 'Pajawiri gbogbogbo',
    'silent_panic': 'Ipayà ipalọlọ',
    'stealth_sos': 'SOS ikoko',
    'stealth_sos_dashboard': 'SOS ikoko',
    'emergency_user': 'Olumulo pajawiri',
    'offline_mode': 'Ipo aisopọ',
    'medical_info_title': 'Alaye iṣoogun',
    'privacy_security_title': 'Aṣiri ati Aabo',
    'edit_profile_title': 'Ṣatunkọ profaili',
    'emergency_contacts_title': 'Awọn olubasọrọ pajawiri',
    'about_title': 'Nipa',
    'app_version': 'Ẹya ohun elo',
    'sectop_description': 'Sectop jẹ ohun elo aabo agbegbe ti o fun ọ laaye lati gba awọn itaniji ati awọn imudojuiwọn lori awọn irokeke ewu',
    'no_emergency_contacts': 'Ko si awọn olubasọrọ pajawiri',
    'add_contact_title': 'Fi olubasọrọ kun',
    'edit_contact_title': 'Ṣatunkọ olubasọrọ',
    'contact_name': 'Orukọ olubasọrọ',
    'contact_phone': 'Foonu olubasọrọ',
    'save_contact': 'Fipamọ olubasọrọ',
    'cancel_btn': 'Fagilee',
    'close_btn': 'Pa',
    'save_btn': 'Fipamọ',
    'cancel_action': 'Fagilee',
    'close_action': 'Pa',
    'save_action': 'Fipamọ',
    'permission_location': 'Ipo',
    'permission_notifications': 'Awọn ifitonileti',
    'permission_bluetooth': 'Bluetooth',
    'permission_storage': 'Ibi ipamọ',
}

# ====== IGBO TRANSLATIONS (all 335 keys) ======
ig = {
    'app_name': 'Sectop',
    'ok': 'Ọma',
    'cancel': 'Kagbuo',
    'loading': 'Na-ebugo...',
    'error': 'Njehie',
    'success': 'Ọma',
    'retry': 'Nwa ọzọ',
    'confirm': 'Kwenye',
    'delete': 'Hichapụ',
    'edit': 'Dezie',
    'settings': 'Ntọala',
    'help': 'Enyemaka',
    'about': 'Banyere',
    'version': 'Mpụta',
    'exit': 'Pụọ',
    'back': 'Azụ',
    'next': 'Osote',
    'submit': 'Nyefee',
    'search': 'Chọọ',
    'filter': 'Nyochaa',
    'sort': 'Hazie',
    'refresh': 'Megharịa',
    'no_data': 'Enweghị data',
    'try_again': 'Nwa ọzọ',
    'network_error': 'Njehie netwọk',
    'server_error': 'Njehie sava',
    'unknown_error': 'Njehie amaghị',
    'timeout_error': 'Oge gwụchara',
    'offline': 'Anọghị n'ịntanetị',
    'online': 'N'ịntanetị',
    'connecting': 'Na-ejikọ...',
    'connected': 'Ejikọrọ',
    'disconnected': 'Kewapụrụ',
    'login': 'Banye',
    'register': 'Deba aha',
    'logout': 'Pụọ',
    'email': 'Email',
    'password': 'Okwuntughe',
    'phone_number': 'Nọmba ekwentị',
    'full_name': 'Aha zuru ezu',
    'sign_in': 'Banye',
    'sign_up': 'Deba aha',
    'forgot_password': 'Chefuru okwuntughe?',
    'reset_password': 'Tụgharịa okwuntughe',
    'new_password': 'Okwuntughe ọhụrụ',
    'confirm_password': 'Kwenye okwuntughe',
    'create_account': 'Mepụta akaụntụ',
    'already_have_account': 'Enweela akaụntụ?',
    'dont_have_account': 'Enweghị akaụntụ?',
    'welcome_back': 'Nnọọ',
    'welcome_to_sectop': 'Nnọọ na Sectop',
    'sos_alert': 'Nkọtị SOS',
    'send_sos': 'Ziga SOS',
    'sos_sent': 'Ezigala SOS',
    'sending_sos': 'Na-eziga SOS...',
    'cancel_sos': 'Kagbuo SOS',
    'sos_countdown': 'SOS na-agụta {}',
    'emergency': 'Ihe mberede',
    'help_message': 'Ozi enyemaka',
    'current_location': 'Ọnọdụ ugbu a',
    'share_location': 'Kesaa ọnọdụ',
    'tracking': 'Na-eso',
    'stop_tracking': 'Kwụsị ịso',
    'start_tracking': 'Malite ịso',
    'location_tracking': 'Ịso ọnọdụ',
    'location_permission': 'Ikike ọnọdụ',
    'location_permission_desc': 'Sectop chọrọ ikike ọnọdụ iji zipu ọnọdụ gị n'ihe mberede',
    'enable_location': 'Gosi ọnọdụ',
    'enable_bluetooth': 'Gosi Bluetooth',
    'dashboard': 'Dashboard',
    'inbox': 'Igbe ozi',
    'map': 'Map',
    'profile': 'Profaịlụ',
    'home': 'Ụlọ',
    'notifications': 'Ngosi',
    'messages': 'Ozi',
    'alerts': 'Nkọtị',
    'incidents': 'Ihe mere',
    'report_incident': 'Kọọ ihe mere',
    'view_details': 'Le nkọwa',
    'status': 'Ọnọdụ',
    'active': 'Na-arụ ọrụ',
    'inactive': 'Anọghị ọrụ',
    'pending': 'Na-echere',
    'resolved': 'Edozila',
    'closed': 'Emechila',
    'critical': 'Dị oké mkpa',
    'high': 'Elu',
    'medium': 'Ọkara',
    'low': 'Ala',
    'safe': 'Nchebe',
    'danger': 'Ihe egwu',
    'warning': 'Ịdọ aka ná ntị',
    'info': 'Ozi',
    'threat_level': 'Ọkwa ihe egwu',
    'threats_nearby': 'Ihe egwu dị nso',
    'no_threats': 'Enweghị ihe egwu',
    'safe_route': 'Ụzọ nchebe',
    'calculate_route': 'Gbakọọ ụzọ',
    'route_planned': 'Emebere ụzọ',
    'avoid_area': 'Zere mpaghara',
    'danger_zone': 'Mpaghara ihe egwu',
    'restricted_area': 'Mpaghara amachibidoro',
    'mesh_network': 'Netwọk mesh',
    'mesh_status': 'Ọnọdụ mesh',
    'mesh_connected': 'Mesh ejikọrọ',
    'mesh_disconnected': 'Mesh kewapụrụ',
    'mesh_peers': 'Ndị ọgbọ mesh',
    'bluetooth_scanning': 'Nyocha Bluetooth',
    'bluetooth_disabled': 'Enyọrọ Bluetooth',
    'bluetooth_enabled': 'Gosiri Bluetooth',
    'device_info': 'Ozi ngwaọrụ',
    'device_id': 'NJ ngwaọrụ',
    'battery_level': 'Ọkwa batrị',
    'charging': 'Na-achọ',
    'not_charging': 'Anaghị achọ',
    'last_seen': 'Ụbọchị ikpeazụ',
    'online_users': 'Ndị ọrụ n'ịntanetị',
    'offline_users': 'Ndị ọrụ anọghị n'ịntanetị',
    'tip_off': 'Ntụnye',
    'send_tip': 'Ziga ntụnye',
    'tip_sent': 'Ezigala ntụnye',
    'tip_anonymous': 'Ntụnye na-amaghị aha',
    'tip_off_title': 'Ntụnye nchebe',
    'tip_description': 'Kọọ ihe enyo enyo n'enweghị egwu',
    'tip_off_guidelines': 'Ntuziaka ntụnye',
    'anonymous': 'Amaghị aha',
    'your_identity_protected': 'A ga-echebe njirimara gị',
    'broadcast': 'Mgbasa ozi',
    'create_broadcast': 'Mepụta mgbasa ozi',
    'broadcast_message': 'Ozi mgbasa ozi',
    'broadcast_to': 'Mgbasa ozi na',
    'select_state': 'Họrọ steeti',
    'select_lga': 'Họrọ LGA',
    'all_states': 'Steeti niile',
    'all_lgas': 'LGA niile',
    'target_audience': 'Ndị na-ege ntị',
    'send_broadcast': 'Ziga mgbasa ozi',
    'broadcast_history': 'Akụkọ mgbasa ozi',
    'no_broadcasts': 'Enweghị mgbasa ozi',
    'walkie_talkie': 'Walkie-talkie',
    'press_to_talk': 'Pịa ikwu okwu',
    'release_to_send': 'Hapụ iziga',
    'recording': 'Na-edekọ...',
    'voice_message': 'Ozi olu',
    'voice_broadcast': 'Mgbasa ozi olu',
    'first_aid': 'Enyemaka mbụ',
    'first_aid_guide': 'Ntuziaka enyemaka mbụ',
    'first_aid_tips': 'Ndụmọdụ enyemaka mbụ',
    'emergency_numbers': 'Nọmba mberede',
    'call_emergency': 'Kpọọ mberede',
    'police': 'Ndị uwe ojii',
    'fire_service': 'Ọrụ ọkụ',
    'ambulance': 'Ụgbọ ihe mberede',
    'nema': 'NEMA',
    'frsc': 'FRSC',
    'custom_emergency': 'Mberede ahaziri',
    'add_number': 'Tinye nọmba',
    'edit_number': 'Dezie nọmba',
    'remove_number': 'Wepụ nọmba',
    'default_emergency': 'Mberede ndabara',
    'sectop_community': 'Obodo Sectop',
    'community': 'Obodo',
    'forum': 'Ọgbakọ',
    'discussions': 'Mkparịta ụka',
    'post': 'Zipu',
    'comment': 'Okwu',
    'share': 'Kesaa',
    'report': 'Kọọ',
    'block_user': 'Gbochie onye ọrụ',
    'mute': 'Gbachi nkịtị',
    'unmute': 'Wepụ ịgbachi nkịtị',
    'follow': 'Soro',
    'unfollow': 'Kwụsị ịsọ',
    'verified': 'Enyochala',
    'official': 'Gọọmenti',
    'trusted_source': 'Isi iyi a tụkwasịrị obi',
    'ai_powered': 'Nke AI kwadoro',
    'threat_analysis': 'Nyocha ihe egwu',
    'analyzing': 'Na-enyocha...',
    'threat_detected': 'Achọpụtala ihe egwu',
    'no_threat_detected': 'Achọpụtaghị ihe egwu',
    'safe_area': 'Mpaghara nchebe',
    'evacuation_route': 'Ụzọ mgbapụ',
    'shelter_in_place': 'Gbachi ebe ahụ',
    'emergency_alerts': 'Nkọtị mberede',
    'subscribe_alerts': 'Denye aha maka nkọtị',
    'unsubscribe_alerts': 'Wepụ aha na nkọtị',
    'alert_history': 'Akụkọ nkọtị',
    'clear_alerts': 'Kpochapụ nkọtị',
    'mark_all_read': 'Gosi na agụla ha niile',
    'no_alerts': 'Enweghị nkọtị',
    'account': 'Akaụntụ',
    'account_settings': 'Ntọala akaụntụ',
    'privacy_policy': 'Amụma nzuzo',
    'terms_of_service': 'Usoro ọrụ',
    'delete_account': 'Hichapụ akaụntụ',
    'delete_account_warning': 'Ị ga-efunahụ data gị niile. Enweghị ike ịtụgharị omume a.',
    'confirm_delete': 'Kwenye ihichapụ',
    'account_deleted': 'Emechara hichapụ akaụntụ',
    'data_saved_offline': 'Echekwara data na mpụga',
    'sync_now': 'Mekọrịta ugbu a',
    'last_sync': 'Mekọrịta ikpeazụ',
    'sync_status': 'Ọnọdụ mmekọrịta',
    'sync_complete': 'Mekọrịtachara',
    'sync_failed': 'Mmekọrịta dara',
    'sync_in_progress': 'Mmekọrịta na-aga n'ihu',
    'please_enter_phone': 'Biko tinye nọmba ekwentị gị',
    'please_enter_password': 'Biko tinye okwuntughe gị',
    'password_min_chars': 'Okwuntughe ga-enwe opekata mpe mkpụrụedemede 8',
    'emergency_tools': 'Ngwaọrụ mberede',
    'broadcasts': 'Mgbasa ozi',
    'radio': 'Redio',
    'data_sync': 'Mmekọrịta data',
    'syncing': 'Na-emekọrịta',
    'pending_items': 'Ihe ndị na-echere',
    'peers_connected': 'Ndị ọgbọ ejikọrọ',
    'sos_sent_silently': 'Ezigara SOS na nkịtị',
    'sos_failed': 'SOS dara',
    'send_sos_alert_title': 'Ziga nkọtị SOS',
    'alert_type': 'Ụdị nkọtị',
    'select_alert_type': 'Họrọ ụdị nkọtị',
    'description_optional': 'Nkọwa (nhọrọ)',
    'capture_evidence_optional': 'Jide ihe akaebe (nhọrọ)',
    'photo': 'Foto',
    'video': 'Vidiyo',
    'audio': 'Ọdịyo',
    'sending_in_seconds': 'Na-eziga na {} sekọnd',
    'tap_to_send_alert': 'Pịa iziga nkọtị',
    'ai_analyzing': 'AI na-enyocha...',
    'distress_detected': 'Achọpụtala nsogbu',
    'no_distress_detected': 'Achọpụtaghị nsogbu',
    'priority': 'Mkpa',
    'confidence': 'Ntụkwasị obi',
    'alert_broadcast_channels': 'Ọwa mgbasa ozi nkọtị',
    'your_location_sent': 'Ezigala ọnọdụ gị',
    'failed_to_send_sos': 'Ọ dara iziga SOS',
    'permissions_required': 'Ikike achọrọ',
    'location': 'Ọnọdụ',
    'bluetooth': 'Bluetooth',
    'storage': 'Nchekwa',
    'unread_messages': 'Ozi agụghị',
    'active_alerts': 'Nkọtị na-arụ ọrụ',
    'recent_messages': 'Ozi na-adịbeghị anya',
    'no_recent_messages': 'Enweghị ozi na-adịbeghị anya',
    'open_inbox': 'Mepee igbe ozi',
    'unknown_sender': 'Onye zitere amaghị',
    'medical_info': 'Ozi ahụike',
    'privacy_security': 'Nzuzo na Nchebe',
    'stealth_mode_sos': 'SOS ọnọdụ nzuzo',
    'silent_panic_trigger': 'Mkpasu iwe ịgbachi nkịtị',
    'stealth_mode_description': 'Ọnọdụ nzuzo na-enye gị ohere iziga nkọtị n'ezoghị ọnụ',
    'close': 'Mechie',
    'save': 'Chekwa',
    'name': 'Aha',
    'phone': 'Ekwentị',
    'profile_updated': 'Emechapụta profaịlụ',
    'medical_info_saved': 'Echekwala ozi ahụike',
    'blood_type': 'Ụdị ọbara',
    'allergies': 'Ihe nfụkasị ahụ',
    'medications': 'Ọgwụ',
    'medical_conditions': 'Ọnọdụ ahụike',
    'add_contact': 'Tinye kọntaktị',
    'edit_contact': 'Dezie kọntaktị',
    'no_contacts': 'Enweghị kọntaktị',
    'read_privacy_policy': 'Gụọ amụma nzuzo',
    'open_full_map': 'Mepee map zuru ezu',
    'zones_nearby': 'Mpaghara dị nso',
    'failed_to_load': 'Ọ dara ibunye',
    'change_language': 'Gbanwee asụsụ',
    'english': 'Bekee',
    'yoruba': 'Yoruba',
    'igbo': 'Igbo',
    'hausa': 'Hausa',
    'trapped': 'Tọrọ atọ',
    'lost': 'Furfu',
    'structural_damage': 'Mmebi ihe owuwu',
    'other_emergency': 'Ihe mberede ọzọ',
    'general_emergency': 'Ihe mberede izugbe',
    'silent_panic': 'Ụjọ ịgbachi nkịtị',
    'stealth_sos': 'SOS nzuzo',
    'stealth_sos_dashboard': 'SOS nzuzo',
    'emergency_user': 'Onye ọrụ mberede',
    'offline_mode': 'Ọnọdụ anọghị n'ịntanetị',
    'medical_info_title': 'Ozi ahụike',
    'privacy_security_title': 'Nzuzo na Nchebe',
    'edit_profile_title': 'Dezie profaịlụ',
    'emergency_contacts_title': 'Kọntaktị mberede',
    'about_title': 'Banyere',
    'app_version': 'Mpụta ngwa',
    'sectop_description': 'Sectop bụ ngwa nchebe obodo nke na-enye gị ohere ịnata nkọtị na mmelite banyere ihe egwu nchebe',
    'no_emergency_contacts': 'Enweghị kọntaktị mberede',
    'add_contact_title': 'Tinye kọntaktị',
    'edit_contact_title': 'Dezie kọntaktị',
    'contact_name': 'Aha kọntaktị',
    'contact_phone': 'Ekwentị kọntaktị',
    'save_contact': 'Chekwa kọntaktị',
    'cancel_btn': 'Kagbuo',
    'close_btn': 'Mechie',
    'save_btn': 'Chekwa',
    'cancel_action': 'Kagbuo',
    'close_action': 'Mechie',
    'save_action': 'Chekwa',
    'permission_location': 'Ọnọdụ',
    'permission_notifications': 'Ngosi',
    'permission_bluetooth': 'Bluetooth',
    'permission_storage': 'Nchekwa',
}

# ====== HAUSA TRANSLATIONS (all 335 keys) ======
ha = {
    'app_name': 'Sectop',
    'ok': 'Yayi',
    'cancel': 'Soke',
    'loading': 'Ana lodi...',
    'error': 'Kuskure',
    'success': 'Nasara',
    'retry': 'Sake gwadawa',
    'confirm': 'Tabbatar',
    'delete': 'Share',
    'edit': 'Gyara',
    'settings': 'Saituna',
    'help': 'Taimako',
    'about': 'Game da',
    'version': 'Sigar',
    'exit': 'Fita',
    'back': 'Baya',
    'next': 'Gaba',
    'submit': 'Aika',
    'search': 'Bincike',
    'filter': 'Tace',
    'sort': 'Tsara',
    'refresh': 'Wartsake',
    'no_data': 'Babu bayanai',
    'try_again': 'Sake gwadawa',
    'network_error': 'Kuskuren hanyar sadarwa',
    'server_error': 'Kuskuren uwar garken',
    'unknown_error': 'Kuskuren da ba a sani ba',
    'timeout_error': 'Lokaci ya kare',
    'offline': 'Babu intanet',
    'online': 'Akan intanet',
    'connecting': 'Ana haɗi...',
    'connected': 'An haɗa',
    'disconnected': 'An cire haɗi',
    'login': 'Shiga',
    'register': 'Yi rajista',
    'logout': 'Fita',
    'email': 'Imel',
    'password': 'Kalmar sirri',
    'phone_number': 'Lambar waya',
    'full_name': 'Cikakken suna',
    'sign_in': 'Shiga',
    'sign_up': 'Yi rajista',
    'forgot_password': 'Ka manta kalmar sirri?',
    'reset_password': 'Sake saita kalmar sirri',
    'new_password': 'Sabuwar kalmar sirri',
    'confirm_password': 'Tabbatar da kalmar sirri',
    'create_account': 'Ƙirƙiri asusu',
    'already_have_account': 'Kana da asusu?',
    'dont_have_account': 'Baka da asusu?',
    'welcome_back': 'Sannu da dawowa',
    'welcome_to_sectop': 'Barka da zuwa Sectop',
    'sos_alert': 'Faɗakarwar SOS',
    'send_sos': 'Aika SOS',
    'sos_sent': 'An aika SOS',
    'sending_sos': 'Ana aika SOS...',
    'cancel_sos': 'Soke SOS',
    'sos_countdown': 'SOS yana kirgawa {}',
    'emergency': 'Gaggawa',
    'help_message': 'Sakon taimako',
    'current_location': 'Wurin da yake yanzu',
    'share_location': 'Raba wuri',
    'tracking': 'Ana bin diddigi',
    'stop_tracking': 'Dakatar da bin diddigi',
    'start_tracking': 'Fara bin diddigi',
    'location_tracking': 'Bin diddigin wuri',
    'location_permission': 'Izinin wuri',
    'location_permission_desc': 'Sectop na buƙatar izinin wuri don aika wurin ka a cikin gaggawa',
    'enable_location': 'Kunna wuri',
    'enable_bluetooth': 'Kunna Bluetooth',
    'dashboard': 'Dashboard',
    'inbox': 'Akwatin saƙo',
    'map': 'Taswira',
    'profile': 'Bayanan martaba',
    'home': 'Gida',
    'notifications': 'Sanarwa',
    'messages': 'Saƙonni',
    'alerts': 'Faɗakarwa',
    'incidents': 'Abubuwan da suka faru',
    'report_incident': 'Bayar da rahoton abin da ya faru',
    'view_details': 'Duba cikakkun bayanai',
    'status': 'Matsayi',
    'active': 'Aiki',
    'inactive': 'Ba aiki',
    'pending': 'Ana jira',
    'resolved': 'An warware',
    'closed': 'An rufe',
    'critical': 'Mai matuƙar muhimmanci',
    'high': 'Babba',
    'medium': 'Matsakaici',
    'low': 'Ƙasa',
    'safe': 'Lafiya',
    'danger': 'Haɗari',
    'warning': 'Gargadi',
    'info': 'Bayani',
    'threat_level': 'Matakin haɗari',
    'threats_nearby': 'Haɗari a kusa',
    'no_threats': 'Babu haɗari',
    'safe_route': 'Hanyar lafiya',
    'calculate_route': 'Ƙididdige hanya',
    'route_planned': 'An tsara hanya',
    'avoid_area': 'Ka guji yankin',
    'danger_zone': 'Y