#!/usr/bin/env python3
"""Generate localization.dart - compact data-driven approach."""
import os

D = os.path.dirname(__file__)
P1 = os.path.join(D, 'frontend', 'lib', 'core', 'localization_part1.dart')
OUT = os.path.join(D, 'frontend', 'lib', 'core', 'localization.dart')

with open(P1, 'r', encoding='utf-8') as f:
    c = f.read()

# Fix truncated line
c = c.replace("'please_enter_phone': 'J\u1ecdw\u1ecd t", "'please_enter_phone': 'J\u1ecdw\u1ecd t\u1eb9 n\u1ecdmba foonu r\u1eb9 sii',")

# Find truncation point
lines = c.split('\n')
idx = -1
for i, l in enumerate(lines):
    if 'please_enter_phone' in l:
        idx = i
        break

base = '\n'.join(lines[:idx+1])

# Remaining Yoruba keys + Igbo + Hausa + delegate + extension
# Using compact format
tail = """    },
    'ig': {
      'app_name': 'Sectop',
      'ok': '\u1ecc D\u1ecbkwa',
      'cancel': 'Kagbuo',
      'save': 'Chekwa',
      'delete': 'Hichap\u1ee5',
      'edit': 'Dezie',
      'retry': 'Nwaa \u1ecdz\u1ecd',
      'loading': 'Na-ebunye...',
      'error': 'Njehie',
      'success': '\u1eccganihu',
      'warning': '\u1eccd\u1ecd aka n\u00e1 nt\u1ecb',
      'info': 'Ozi',
      'confirm': 'Kwenye',
      'yes': 'Ee',
      'no': 'Mba',
      'back': 'Laghachi',
      'next': 'Osote',
      'submit': 'Nyefee',
      'search': 'Ch\u1ecd\u1ecd',
      'filter': 'Nyochaa',
      'sort': 'Hazie',
      'refresh': 'Meghar\u1ecba',
      'settings': 'Nt\u1ecdala',
      'profile': 'Profa\u1ecbl\u1ee5',
      'logout': 'Wep\u1ee5',
      'login': 'Banye',
      'register': 'Deba aha',
      'home': '\u1ee4l\u1ecd',
      'dashboard': 'Dasiboodu',
      'notifications': 'Ngosi',
      'messages': 'Ozi',
      'alerts': '\u1eccd\u1ecd aka n\u00e1 nt\u1ecb',
      'emergency': 'Ihe mberede',
      'sos': 'SOS',
      'panic_button': 'B\u1ecdt\u1ecbn\u1ecb \u1ee4j\u1ecd',
      'send_sos': 'Ziga SOS',
      'cancel_sos': 'Kagbuo SOS',
      'sos_sent': 'Ezigala SOS!',
      'sos_cancelled': 'Akagbuola SOS',
      'location': 'Ebe',
      'latitude': 'Latitjudu',
      'longitude': 'Longitjudu',
      'accuracy': 'Izi ezi',
      'address': 'Adiresi',
      'city': 'Obodo',
      'state': 'Steeti',
      'country': 'Obodo',
      'phone': 'Ekwent\u1ecb',
      'email': 'Imeeli',
      'password': 'Okwuntughe',
      'confirm_password': 'Kwenye Okwuntughe',
      'forgot_password': 'Chefuru Okwuntughe?',
      'reset_password': 'Tughar\u1ecba Okwuntughe',
      'new_password': 'Okwuntughe \u1ecch\u1ee5r\u1ee5',
      'old_password': 'Okwuntughe Ochie',
      'change_password': 'Gbanwee Okwuntughe',
      'name': 'Aha',
      'full_name': 'Aha Zuru',
      'username': 'Aha njirimara',
      'phone_number': 'N\u1ecdmba Ekwent\u1ecb',
      'date_of_birth': '\u1ee4b\u1ecdch\u1ecb \u1eccm\u1ee5m\u1ee5',
      'gender': 'Okike',
      'male': 'Nwoke',
      'female': 'Nwany\u1ecb',
      'other': '\u1eccz\u1ecd',
      'blood_type': '\u1ee4d\u1ecb \u1eccbara',
      'medical_conditions': '\u1eccn\u1ecddu\u1ee5 Ah\u1ee5ike',
      'allergies': 'Ihe Ah\u1ee5 Na-anabata',
      'emergency_contact': 'K\u1ecdntakt\u1ecb Mberede',
      'emergency_contacts': 'K\u1ecdntakt\u1ecb Mberede',
      'add_contact': 'Tinye K\u1ecdntakt\u1ecb',
      'remove_contact': 'Wep\u1ee5 K\u1ecdntakt\u1ecb',
      'contact_name': 'Aha K\u1ecdntakt\u1ecb',
      'contact_phone': 'Ekwent\u1ecb K\u1ecdntakt\u1ecb',
      'relationship': 'Mmet\u1ee5ta',
      'save_contact': 'Chekwa K\u1ecdntakt\u1ecb',
      'no_contacts': 'Enwegh\u1ecb k\u1ecdntakt\u1ecb mberede agbakwunyere',
      'first_aid': 'Enyemaka Mb\u1ee5',
      'first_aid_guides': 'Nduzi Enyemaka Mb\u1ee5',
      'first_aid_tips': 'Nd\u1ee5m\u1ecddu\u1ee5 Enyemaka Mb\u1ee5',
      'bleeding': '\u1eccbara',
      'burns': '\u1ecck\u1ee5',
      'fractures': '\u1ecckp\u1ee5kp\u1ee5',
      'choking': 'Nkpagbu',
      'cpr': 'CPR',
      'poisoning': 'Ns\u1ecb',
      'shock': 'Ujo',
      'heart_attack': 'Nk\u1ee5chi Obi',
      'stroke': '\u1eccr\u1ecba \u1ee4b\u1ee5r\u1ee5',
      'seizure': '\u1eccd\u1ecbd\u1ecd',
      'snake_bite': 'Agw\u1ecd Taa',
      'drowning': 'Mikpu',
      'emergency_numbers': 'N\u1ecdmba Mberede',
      'police': 'Nd\u1ecb Uwe Ojii',
      'ambulance': '\u1ee4gb\u1ecd Ihe Mberede',
      'fire_service': '\u1eccr\u1ee5 \u1ecck\u1ee5',
      'road_safety': 'Nchebe Okporo \u1ee4z\u1ecd',
      'civil_defence': 'Nchebe Obodo',
      'coast_guard': 'Nchebe Osimiri',
      'nema': 'NEMA',
      'nigerian_police': 'Nd\u1ecb Uwe Ojii Naijiria',
      'federal_road_safety': '\u1ee4l\u1ecd \u1eccr\u1ee5 Nchebe Okporo \u1ee4z\u1ecd G\u1ecd\u1ecdmmenti Etiti',
      'nigerian_ambulance': '\u1eccr\u1ee5 \u1ee4gb\u1ecd Ihe Mberede Naijiria',
      'nigerian_fire_service': '\u1eccr\u1ee5 \u1ecck\u1ee5 Naijiria',
      'nigerian_civil_defence': '\u1ee4l\u1ecd \u1eccr\u1ee5 Nchebe na Nchedo Obodo Naijiria',
      'ncdc': 'NCDC',
      'nigerian_coast_guard': 'Nchebe Osimiri Naijiria',
      'nigerian_air_force': 'Nd\u1ecb Agha Ikuku Naijiria',
      'nigerian_army': 'Nd\u1ecb Agha Naijiria',
      'nigerian_navy': 'Nd\u1ecb Agha Mmiri Naijiria',
      'nigerian_red_cross': 'Red Cross Naijiria',
      'nigerian_nema': '\u1ee4l\u1ecd \u1eccr\u1ee5 Nch\u1ecbkwa Mberede Mba',
      'safety_tips': 'Nd\u1ee5m\u1ecddu\u1ee5 Nchebe',
      'disaster_preparedness': 'Nkwadebe \u1eccdachi',
      'natural_disasters': '\u1eccdachi Nd\u1ecb Eke',
      'flood': 'Ide Mmiri',
      'earthquake': 'Ala \u1eccma jijiji',
      'landslide': 'Mgbada Ala',
      'volcanic_eruption': 'Ugwu \u1ecdk\u1ee5',
      'tsunami': 'Tsunami',
      'hurricane': 'Ok\u00e9 Ifufe',
      'tornado': 'Tornado',
      'wildfire': '\u1ecck\u1ee5 \u1ecch\u1ecba',
      'pandemic': '\u1eccr\u1ecba Na-efe efe',
      'terrorist_attack': 'Mwakpo Nd\u1ecb \u1ecct\u1ee5r\u1ee5gba',
      'active_shooter': 'Onye Na-agba Egbe',
      'bomb_threat': 'Iyi Egwu B\u1ecdmbu',
      'kidnapping': 'Nt\u1ecdr\u1ecd',
      'robbery': 'Izu',
      'domestic_violence': 'Ime Ihe Ike N\u2019\u1ee5l\u1ecd',
      'sexual_assault': 'Mwakpo Mmek\u1ecdah\u1ee5',
      'human_trafficking': '\u1eccz\u1ee5 Ah\u1ecba Mmad\u1ee5',
      'cyberbullying': 'Iji Mmad\u1ee5 Me Ihe N\u2019\u1ee4ntanet',
      'online_scam': 'Agh\u1ee5gh\u1ecd N\u2019\u1ee4ntanet',
      'identity_theft': 'Ohi Njirimara",
      'report_incident': 'K\u1ecd\u1ecd Ihe Mere',
      'report_crime': 'K\u1ecd\u1ecd Mp\u1ee5',
      'report_emergency': 'K\u1ecd\u1ecd Ihe Mberede',
      'tip_off': 'Nt\u1ee5nye',
      'anonymous_tip': 'Nt\u1ee5nye Na-amagh\u1ecb Aha',
      'submit_tip': 'Nyefee Nt\u1ee5nye',
      'tip_submitted': 'Enyefela nt\u1ee5nye nke \u1ecdcma',
      'tip_failed': '\u1ecc dara \u1ecbnyefe nt\u1ee5nye',
      'tip_description': 'Nk\u1ecdwa Nt\u1ee5nye',
      'attach_evidence': 'Tinye Ihe Ngbak\u1ecd',
      'take_photo': 'Sere Foto',
      'choose_from_gallery': 'H\u1ecdr\u1ecd Site na Gallery',
      'record_audio': 'Dek\u1ecd \u1eccd\u1ecbyo',
      'record_video': 'Dek\u1ecd Vidio',
      'select_file': 'H\u1ecdr\u1ecd Fa\u1ecbl\u1ee5',
      'remove_file': 'Wep\u1ee5 Fa\u1ecbl\u1ee5',
      'evidence': 'Ihe Ngbak\u1ecd',
      'no_evidence': 'Enwegh\u1ecb ihe ngbak\u1ecd agbakwunyere',
      'incident_report': 'Ak\u1ee5k\u1ecd Ihe Mere',
      'incident_type': '\u1ee4d\u1ecb Ihe Mere',
      'incident_date': '\u1ee4b\u1ecdch\u1ecb Ihe Mere',
      'incident_location': 'Ebe Ihe Mere',
      'incident_description': 'Nk\u1ecdwa Ihe Mere',
      'incident_status': '\u1eccn\u1ecddu\u1ee5 Ihe Mere',
      'incident_severity': 'Ogo Ihe Mere',
      'low': 'D\u1ecb ala',
      'medium': '\u1ecckara',
      'high': 'D\u1ecb elu',
      'critical': 'D\u1ecb ok\u00e9 mkpa',
      'pending': 'Na-echere',
      'in_progress': 'Na-aga n\u2019ihu',
      'resolved': 'Edozila',
      'closed': 'Emechiela',
      'verified': 'Enyochala',
      'unverified': 'Enwebegh\u1ecb nyocha',
      'nearby_incidents': 'Ihe Mere D\u1ecb Nso',
      'no_incidents': 'Enwegh\u1ecb ihe mere ak\u1ecdr\u1ecd nso',
      'safe_route': '\u1ee4z\u1ecd Nchebe',
      'plan_route': 'Hazie \u1ee4z\u1ecd',
      'current_location': 'Ebe \u1ecb N\u1ecd',
      'destination': 'Ebe \u1ecb Na-aga',
      'route_planned': 'Emeela at\u1ee5mat\u1ee5 \u1ee5z\u1ecd nke \u1ecdcma',
      'route_error': '\u1ecc dara \u1ecbhazi \u1ee5z\u1ecd',
      'danger_zones': 'Mpaghara Ihe Egwu',
      'avoid_areas': 'Mpaghara \u1ecb Zere',
      'safe_areas': 'Mpaghara Nchebe',
      'threat_level': '\u1ecckwa Ihe Egwu',
      'threat_assessment': 'Nt\u1ee5le Ihe Egwu',
      'threat_detected': 'Ach\u1ecdp\u1ee5tala Ihe Egwu',
      'no_threats': 'Enwegh\u1ecb ihe egwu ach\u1ecdp\u1ee5tara',
      'threat_awareness': '\u1ecamara Ihe Egwu',
      'nearby_threats': 'Ihe Egwu D\u1ecb Nso',
      'threat_history': 'Ak\u1ee5k\u1ecd Ihe Egwu',
      'threat_analysis': 'Nyocha Ihe Egwu',
      'community_alerts': '\u1eccd\u1ecd Aka n\u00e1 Nt\u1ecb Obodo',
      'broadcast': 'Mgbasa Ozi',
      'create_broadcast': 'Mep\u1ee5ta Mgbasa Ozi',
      'broadcast_message': 'Ozi Mgbasa Ozi',
      'broadcast_to': 'Gbasara',
      'everyone': 'Onye \u1ecdb\u1ee5la',
      'specific_zone': 'Mpaghara Ak\u1ecdwap\u1ee5tara',
      'specific_users': 'Nd\u1ecb \u1ecdr\u1ee5 Ak\u1ecdwap\u1ee5tara',
      'send_broadcast': 'Ziga Mgbasa Ozi',
      'broadcast_sent': 'Ezigala mgbasa ozi nke \u1ecdcma',
      'broadcast_failed': '\u1ecc dara iziga mgbasa ozi',
      'radio_broadcast': 'Mgbasa Ozi Redio',
      'radio_frequency': 'Ugboro Redio',
      'radio_message': 'Ozi Redio',
      'send_radio': 'Ziga Mgbasa Ozi Redio',
      'radio_sent': 'Ezigala mgbasa ozi redio',
      'radio_failed': '\u1ecc dara iziga mgbasa ozi redio',
      'mesh_network': 'Netw\u1ecdk Mesh',
      'mesh_status': '\u1eccn\u1ecddu\u1ee5 Netw\u1ecdk Mesh',
      'mesh_connected': 'Ejik\u1ecdr\u1ecd na Netw\u1ecdk Mesh',
      'mesh_disconnected': 'Ekw\u1ee5s\u1ecbr\u1ecd na Netw\u1ecdk Mesh',
      'mesh_nodes': 'Mesh Nodes',
      'mesh_messages': 'Ozi Mesh',
      'send_mesh': 'Ziga site na Mesh',
      'inbox': 'Igbe Ozi',
      'compose': 'Dee',
      'send': 'Ziga',
      'reply': 'Zaghachi',
      'forward': 'Gaa n\u2019ihu',
      'mark_read': 'G\u1ee5\u1ecd',
      'mark_unread': 'Akp\u1ecdgh\u1ecb ya',
      'no_messages': 'Enwegh\u1ecb ozi',
      'message_sent': 'Ezigala ozi',
      'message_failed': '\u1ecc dara iziga ozi',
      'offline_mode': '\u1eccn\u1ecddu\u1ee5 \u1ee4ntanet Na-ad\u1ecbgh\u1ecb',
      'online_mode': '\u1eccn\u1ecddu\u1ee5 \u1ee4ntanet',
      'connecting': 'Na-ejik\u1ecd...',
      'connected': 'Ejik\u1ecdr\u1ecd',
      'disconnected': 'Ekw\u1ee5s\u1ecbr\u1ecd',
      'no_internet': 'Enwegh\u1ecb Njik\u1ecd \u1ee4ntanet',
      'weak_signal': 'Mgbama Na-ad\u1ecbgh\u1ecb ike',
      'strong_signal': 'Mgbama Siri ike',
      'battery_low': 'Batr\u1ecb D\u1ecb ala',
      'battery_critical': 'Batr\u1ecb D\u1ecb Ok\u00e9 Mkpa',
      'charging': 'Na-ach\u1ecd',
      'gps_enabled': 'GPS Gbany\u1ee5r\u1ee5',
      'gps_disabled': 'GPS Gbany\u1ee5r\u1ee5',
      'enable_gps': 'Gbanwuo GPS',
      'enable_location': 'Gbanwuo \u1eccr\u1ee5 Ebe',
      'location_permission': 'Ikike Ebe',
      'camera_permission': 'Ikike Igwefoto',
      'microphone_permission': 'Ikike Igwe Okwu',
      'storage_permission': 'Ikike Nchekwa',
      'notification_permission': 'Ikike Ngosi',
      'allow': 'Kwe',
      'deny': 'J\u1ee5',
      'always_allow': 'Kwe Mgbe Nile',
      'allow_while_using': 'Kwe Mgbe \u1ecb Na-eji Ngwa',
      'permission_required': 'Ikike \u1ecc d\u1ecb mkpa',
      'permission_denied': 'Aj\u1ee5la Ikike',
      'permission_granted': 'Enyela Ikike',
      'open_settings': 'Mepee Nt\u1ecdala',
      'dark_mode': '\u1eccn\u1ecddu\u1ee5 \u1eccch\u1ecbch\u1ecbr\u1ecb',
      'light_mode': '\u1eccn\u1ecddu\u1ee5 \u00cch\u00e8',
      'system_mode': '\u1eccn\u1ecddu\u1ee5 Sistem\u1ee5',
      'language': 'As\u1ee5s\u1ee5',
      'english': 'Bekee',
      'yoruba': 'Yoruba',
      'igbo': 'Igbo',
      'hausa': 'Hausa',
      'select_language': 'H\u1ecdr\u1ecd As\u1ee5s\u1ee5',
      'about': 'Gbasara',
      'help': 'Enyemaka',
      'faq': 'FAQ',
      'contact_us': 'Kp\u1ecdt\u1ee5r\u1ee5 Any\u1ecb',
      'privacy_policy': 'Am\u1ee5ma Nzuzo',
      'terms_of_service': 'Usoro \u1eccr\u1ee5',
      'rate_app': 'Nye Ngwa \u1ecdkwa',
      'share_app': 'Kesaa Ngwa',
      'version': 'Mp\u1ecbak\u1ecdta',
      'update_available': 'Mmelite D\u1ecb',
      'update_now': 'Melite Ugbu a',
      'skip': 'W\u1ee5f\u1ecd',
      'done': 'Emechaala',
      'welcome': 'Nn\u1ecd\u1ecd',
      'welcome_back': 'Nn\u1ecd\u1ecd \u1ecdl\u1ecd\u1ecdgh\u1ecb',
      'sign_in': 'Banye',
      'sign_up': 'Deba Aha',
      'create_account': 'Mep\u1ee5ta Aka\u1ee5nt\u1ee5',
      'already_have_account': '\u1ecb nwere aka\u1ee5nt\u1ee5?',
      'dont_have_account': '\u1ecb enwegh\u1ecb aka\u1ee5nt\u1ee5?',
      'forgot_password_desc': 'Tinye imeeli g\u1ecb, any\u1ecb ga-ezitere g\u1ecb njik\u1ecd \u1ecbtughar\u1ecba okwuntughe',
      'reset_link_sent': 'Ezigara njik\u1ecd \u1ecbtughar\u1ecba okwuntughe na imeeli g\u1ecb',
      'reset_password_desc': 'Tinye okwuntughe \u1ecdh\u1ee5r\u1ee5 g\u1ecb',
      'password_reset_success': '\u1ecctughar\u1ecba okwuntughe gara nke \u1ecdcma',
      'password_changed': 'Agbanweela okwuntughe nke \u1ecdcma',
      'account_deleted': 'Ehichap\u1ee5la aka\u1ee5nt\u1ee5 nke \u1ecdcma',
      'delete_account': 'Hichap\u1ee5 Aka\u1ee5nt\u1ee5',
      'delete_account_confirm': '\u1ecb ji n\u2019aka na \u1ecb ch\u1ecdr\u1ecd ihichap\u1ee5 aka\u1ee5nt\u1ee5 g\u1ecb? Enwegh\u1ecb ike \u1ecbtughar\u1ecba ihe a.',
      'delete_account_warning': 'A ga-ehichap\u1ee5 aka\u1ee5nt\u1ee5 g\u1ecb kpamkpam mgbe \u1ee5b\u1ecdch\u1ecb 30 gas\u1ecbr\u1ecd. \u1ecb nwere ike \u1ecbkagbuo n\u2019ime oge a.',
      'cancel_deletion': 'Kagbuo Nhichap\u1ee5',
      'deletion_cancelled': 'Akagbuola nhichap\u1ee5 aka\u1ee5nt\u1ee5',
      'deletion_scheduled': 'Emeela nhazi nhichap\u1ee5 aka\u1ee5nt\u1ee5',
      'session_expired': 'Oge \u1ecdbanye g\u1ecb agw\u1ee5la',
      'please_login_again': 'Banye \u1ecdz\u1ecd',
      'login_failed': '\u1ecdbanye dara',
      'registration_failed': '\u1ecdd\u1ecbba aha dara',
      'invalid_credentials': 'Imeeli ma\u1ecdb\u1ee5 okwuntughe ad\u1ecbgh\u1ecb mma',
      'email_already_exists': 'Aka\u1ee5nt\u1ee5 nwere imeeli a ad\u1ecblar\u1ecb',
      'weak_password': 'Okwuntughe ad\u1ecbgh\u1ecb ike',
      'password_mismatch': 'Okwuntughe ekwekogh\u1ecb',
      'terms_required': '\u1ecb ga-anabata usoro \u1ecdr\u1ee5',
      'network_error': 'Njehie netw\u1ecdk. Lelee njik\u1ecd \u1ecbntanet g\u1ecb.',
      'server_error': 'Njehie sava. Nwaa \u1ecdz\u1ecd ma e mes\u1ecba.',
      'unknown_error': 'Njehie a na-amagh\u1ecb emeela',
      'try_again': 'Nwaa \u1ecdz\u1ecd',
      'no_data': 'Enwegh\u1ecb data',
      'no_results': 'Enwegh\u1ecb nsonaaz\u1ee5 ach\u1ecdtara',
      'no_internet_desc': '\u1ecb n\u1ecd na \u1ecbntanet na-ad\u1ecbgh\u1ecb ugbu a. \u1ee4f\u1ecddu\u1ee5 at\u1ee5mat\u1ee5 nwere ike \u1ecb n\u00f2 oke.',
      'offline_data_available': 'Data \u1ecbntanet na-ad\u1ecbgh\u1ecb d\u1ecb',
      'offline_data_synced': 'Data \u1ecbntanet na-ad\u1ecbgh\u1ecb emek\u1ecdr\u1ecbla',
      'syncing': 'Na-emek\u1ecdr\u1eca...',
      'sync_complete': 'Ndek\u1ecdr\u1eca zuru ezu',
      'sync_failed': 'Ndek\u1ecdr\u1eca dara',
      'last_synced': 'Emek\u1ecdr\u1ecbla ikpeaz\u1ee5',
      'emergency_access': 'Ohere Mberede',
      'emergency_access_desc': 'Nweta at\u1ee5mat\u1ee5 mberede na-enwegh\u1ecb \u1ecdbanye',
      'use_offline': 'Jiri n\u2019\u1ecdn\u1ecddu\u1ee5 \u1ecbntanet na-ad\u1ecbgh\u1ecb',
      'emergency_mode_active': '\u1eccn\u1ecddu\u1ee5 Mberede Na-ar\u1ee5 \u1ecdr\u1ee5',
      'emergency_mode_desc': 'Agbany\u1ee5la at\u1ee5mat\u1ee5 niile na-ad\u1ecbgh\u1ecb mkpa iji chekwaa batr\u1ecb',
      'exit_emergency_mode': 'Wep\u1ee5 \u1eccn\u1ecddu\u1ee5 Mberede',
      'emergency_access_no_login': 'Ohere Mberede (Enwegh\u1ecb \u1ecdbanye)',
      'use_in_disaster': 'Jiri n\u2019\u1ecdn\u1ecddu\u1ee5 \u1ecddachi mgbe \u1ecb na-enwegh\u1ecb ike \u1ecdbanye',
      'skip_login_guest': 'W\u1ee5f\u1ecd \u1ecdbanye \u2014 Jiri d\u1ecb ka \u1ecdb\u1ecdia',
      'browse_without_account': 'Lelee \u1ecdd\u1ecd aka n\u00e1 nt\u1ecb, lee mpaghara nchebe, ma nweta ozi mberede na-enwegh\u1ecb aka\u1ee5nt\u1ee5',
      'contact_support_email': 'Kp\u1ecdt\u1ee5r\u1ee5 Nkwado:',
      'authentication_failed': 'Nyocha njirimara dara',
      'connection_error_offline': 'Njehie njik\u1ecd. Na-eji \u1ecdn\u1ecddu\u1ee5 \u1ecbntanet na-ad\u1ecbgh\u1ecb.',
      'failed_emergency_mode': '\u1ecc dara \u1ecdbanye n\u2019\u1ecdn\u1ecddu\u1ee5 mberede',
      'please_enter_name': 'Tinye aha g\u1ecb',
      'please_enter_email': 'Tinye imeeli g\u1ecb',
      'please_enter_valid_email': 'Tinye imeeli ziri ezi',
      'please_enter_phone': 'Tinye n\u1ecdmba ekwent\u1ecb g\u1ecb',
      'please_enter_password': 'Tinye okwuntughe g\u1ecb',
      'please_enter_valid_password': 'Tinye okwuntughe ziri ezi (o pekar\u1ecbala mkp\u1ee5r\u1ee5 6)',
      'please_confirm_password': 'Kwenye okwuntughe g\u1ecb',
      'password_too_short': 'Okwuntughe aghagh\u1ecb \u1ecb pekar\u1ecbala mkp\u1ee5r\u1ee5 6',
      'passwords_do_not_match': 'Okwuntughe ekwekogh\u1ecb',
      'invalid_email_format': '\u1ee4d\u1ecb imeeli na-ezigh\u1ecb ezi',
      'field_required': 'Ubi a d\u1ecb mkpa',
      'invalid_input': 'Ntinye na-ezigh\u1ecb ezi',
      'operation_successful': '\u1eccr\u1ee5 gara nke \u1ecdcma',
      'operation_failed': '\u1eccr\u1ee5 dara',
      'changes_saved': 'Echekwala mgbanwe nke \u1ecdcma',
      'changes_discarded': 'At\u1ee5f\u1ee5la mgbanwe',
      'unsaved_changes': '\u1ecb nwere mgbanwe a na-echekwagh\u1ecb',
      'discard_changes': 'T\u1ee5f\u1ee5 mgbanwe?',
      'stay_and_continue': 'N\u1ecdr\u1ecd ma gaa n\u2019ihu na idezi',
      'confirm_discard': '\u1ecb ji n\u2019aka na \u1ecb ch\u1ecdr\u1ecd \u1ecbt\u1ee5f\u1ee5 mgbanwe g\u1ecb?',
      'confirm_delete': '\u1ecb ji n\u2019aka na \u1ecb ch\u1ecdr\u1ecd ihichap\u1ee5 ihe a?',
      'confirm_logout': '\u1ecb ji n\u2019aka na \u1ecb ch\u1ecdr\u1ecd \u1ecbwep\u1ee5?',
      'session_timeout': 'Oge \u1ecdbanye g\u1ecb agw\u1ee5la',
      'session_timeout_desc': 'Banye \u1ecdz\u1ecd iji gaa n\u2019ihu',
      'update_profile': 'Melite Profa\u1ecbl\u1ee5',
      'profile_updated': 'Emelitela profa\u1ecbl\u1ee5 nke \u1ecdcma',
      'profile_update_failed': '\u1ecc dara imelite profa\u1ecbl\u1ee5',
      'change_profile_picture': 'Gbanwee Foto Profa\u1ecbl\u1ee5',
      'remove_profile_picture': 'Wep\u1ee5 Foto Profa\u1ecbl\u1ee5',
      'select_image': 'H\u1ecdr\u1ecd Foto',
      'image_too_large': 'Foto buru oke ibu',
      'unsupported_format': '\u1ee4d\u1ecb fa\u1ecbl\u1ee5 a na-akwadogh\u1ecb',
      'uploading': 'Na-ebugote...',
      'upload_complete': 'Ebugotela nke \u1ecdcma',
      'upload_failed': 'Ibugote dara',
      'downloading': 'Na-ebudata...',
      'download_complete': 'Ebudatela nke \u1ecdcma',
      'download_failed': 'Ibudata dara',
      'processing': 'Na-ahazi...',
      'please_wait': 'Biko chere...',
      'time_estimate': 'Oge a t\u1ee5r\u1ee5 anya:',
      'remaining': 'f\u1ecdd\u1ee5',
      'completed': 'Emechala',
      'progress': '\u1eccganihu',
      'task_completed': '\u1eccr\u1ee5 emechala',
      'task_failed': '\u1eccr\u1ee5 dara',
      'task_cancelled': 'Akagbuola \u1ecdr\u1ee5',
      'start': 'Malite',
      'stop': 'Kw\u1ee5s\u1ecb',
      'pause': 'Kw\u1ee5s\u1ecb nwa oge',
      'resume': 'Maliteghar\u1ecba',
