#!/usr/bin/env python3
"""Generate complete localization.dart - compact version."""
import os

DIR = os.path.dirname(__file__)
PART1 = os.path.join(DIR, 'frontend', 'lib', 'core', 'localization_part1.dart')
OUT = os.path.join(DIR, 'frontend', 'lib', 'core', 'localization.dart')

# Read part1 (first 611 lines)
with open(PART1, 'r', encoding='utf-8') as f:
    content = f.read()

# Fix the truncated line
content = content.replace("'please_enter_phone': 'J\u1ecdw\u1ecd t", "'please_enter_phone': 'J\u1ecdw\u1ecd t\u1eb9 n\u1ecdmba foonu r\u1eb9 sii',")

# Remove the closing braces of the Yoruba section and the rest
# Find the last closing of yo section
# The file ends with the yo dict still open
# We need to find where to cut

lines = content.split('\n')
# Find the truncated line index
trunc_idx = -1
for i, line in enumerate(lines):
    if 'please_enter_phone' in line:
        trunc_idx = i
        break

# Keep everything up to and including the fixed line
base_lines = lines[:trunc_idx + 1]

# Now append the complete remaining content
remaining = '''
      'please_enter_password': 'J\u1ecdw\u1ecd t\u1eb9 \u1ecdr\u1ecdigbaniw\u1ecdle r\u1eb9 sii',
      'please_enter_valid_password': 'J\u1ecdw\u1ecd t\u1eb9 \u1ecdr\u1ecdigbaniw\u1ecdle to wulo sii (o kere ju 6 l\u1eb9ta)',
      'please_confirm_password': 'J\u1ecdw\u1ecd j\u1eb9risi \u1ecdr\u1ecdigbaniw\u1ecdle r\u1eb9',
      'password_too_short': '\u1eccr\u1ecdigbaniw\u1ecdle gb\u1ecdd\u1ecd kere ju 6 l\u1eb9ta',
      'passwords_do_not_match': 'Aw\u1ecdn \u1ecdr\u1ecdigbaniw\u1ecdle ko baramu',
      'invalid_email_format': '\u1eccna imeeli ti ko wulo',
      'field_required': 'Aaye yii ni a nilo',
      'invalid_input': 'I\u1e63aw\u1ecdle ti ko wulo',
      'operation_successful': 'I\u1e63\u1eb9 naa \u1e63a\u1e63ey\u1ecdri',
      'operation_failed': 'I\u1e63\u1eb9 naa kuna',
      'changes_saved': 'Aw\u1ecdn ayipada ti fipam\u1ecd ni a\u1e63ey\u1ecdri',
      'changes_discarded': 'Aw\u1ecdn ayipada ti s\u1ecdn\u00f9',
      'unsaved_changes': 'O ni aw\u1ecdn ayipada ti a ko fipam\u1ecd',
      'discard_changes': 'S\u1ecd aw\u1ecdn ayipada n\u00f9?',
      'stay_and_continue': 'Duro ki o t\u1eb9siwaju \u1e63atunk\u1ecd',
      'confirm_discard': '\u1e62e o da \u1ecd loju pe o f\u1eb9 s\u1ecd aw\u1ecdn ayipada r\u1eb9 n\u00f9?',
      'confirm_delete': '\u1e62e o da \u1ecd loju pe o f\u1eb9 pa eyi r\u1eb9?',
      'confirm_logout': '\u1e62e o da \u1ecd loju pe o f\u1eb9 jade?',
      'session_timeout': 'Akoko igba r\u1eb9 ti pari',
      'session_timeout_desc': 'J\u1ecdw\u1ecd w\u1ecdle l\u1eb9\u1eb9kansi lati t\u1eb9siwaju',
      'update_profile': '\u1e62e Imudojuiw\u1ecdn Profaili',
      'profile_updated': 'Profaili ti ni imudojuiw\u1ecdn ni a\u1e63ey\u1ecdri',
      'profile_update_failed': 'Kuna lati \u1e63e imudojuiw\u1ecdn profaili',
      'change_profile_picture': 'Yi Aworan Profaili Pada',
      'remove_profile_picture': 'Y\u1ecd Aworan Profaili',
      'select_image': 'Yan Aworan',
      'image_too_large': 'Aworan ti tobi ju',
      'unsupported_format': '\u1eccna faili ti ko ni atil\u1eb9yin',
      'uploading': 'Gbigbe si oke...',
      'upload_complete': 'Gbigbe si oke ti pari',
      'upload_failed': 'Gbigbe si oke kuna',
      'downloading': 'Gbigba lati ayelujara...',
      'download_complete': 'Gbigba lati ayelujara ti pari',
      'download_failed': 'Gbigba lati ayelujara kuna',
      'processing': '\u1e62i\u1e63\u1eb9...',
      'please_wait': 'J\u1ecdw\u1ecd duro...',
      'time_estimate': 'Akoko ifoju:',
      'remaining': 'ti o ku',
      'completed': 'Ti pari',
      'progress': 'Il\u1ecdsiwaju',
      'task_completed': 'I\u1e63\u1eb9-\u1e63i\u1e63e ti pari',
      'task_failed': 'I\u1e63\u1eb9-\u1e63i\u1e63e kuna',
      'task_cancelled': 'I\u1e63\u1eb9-\u1e63i\u1e63e ti fagilee',
      'start': 'B\u1eb9r\u1eb9',
      'stop': 'Duro',
      'pause': 'Duro fun igba di\u1eb9',
      'resume': 'Tesiwaju',
      'enable': 'Mu \u1e63i\u1e63\u1eb9',
      'disable': 'Pa',
      'enabled': '\u1e62i\u1e63\u1eb9',
      'disabled': 'Pa',
      'on': 'Ni',
      'off': 'Pa',
      'auto': 'Aif\u1ecdw\u1ecdyi',
      'manual': 'Af\u1ecdw\u1ecd\u1e63e',
      'more': 'Di\u1eb9 sii',
      'less': 'Kere',
      'show_all': 'Fi Gbogbo Han',
      'show_less': 'Fi Kere Han',
      'show_more': 'Fi Di\u1eb9 sii Han',
      'select_all': 'Yan Gbogbo',
      'deselect_all': 'Y\u1ecd Gbogbo',
      'clear': 'Nu',
      'clear_all': 'Nu Gbogbo',
      'reset': 'Tunto',
      'reset_all': 'Tunto Gbogbo',
      'default': 'Aiyipada',
      'custom': 'Ara',
      'advanced': 'Il\u1ecdsiwaju',
      'basic': 'Ipil\u1eb9',
      'general': 'Gbogbogbo',
      'security': 'Aabo',
      'privacy': 'Asiri',
      'account': 'Ak\u1ecd\u1ecdl\u1eb9',
      'data_usage': 'Lilo Data',
      'storage': 'Ibi ipam\u1ecd',
      'cache': 'Ka\u1e63e',
      'clear_cache': 'Nu Ka\u1e63e',
      'cache_cleared': 'Ka\u1e63e ti nu',
      'cache_size': 'Iw\u1ecdn Ka\u1e63e',
      'notifications_settings': 'Eto Ifitonileti',
      'sound': 'Ohun',
      'vibrate': 'Gbigb\u1ecdn',
      'silent': 'Ipal\u1ecdl\u1ecd',
      'loud': 'Ariwo',
      'notification_sound': 'Ohun Ifitonileti',
      'emergency_alert_sound': 'Ohun Itaniji Pajawiri',
      'sos_activation_sound': 'Ohun Imu\u1e63i\u1e63\u1eb9 SOS',
      'enable_notifications': 'Mu Aw\u1ecdn Ifitonileti \u1e62i\u1e63\u1eb9',
      'disable_notifications': 'Pa Aw\u1ecdn Ifitonileti',
      'notification_preferences': 'Aw\u1ecdn Ayanf\u1eb9 Ifitonileti',
      'receive_emergency_alerts': 'Gba Aw\u1ecdn Itaniji Pajawiri',
      'receive_community_alerts': 'Gba Aw\u1ecdn Itaniji Agbegbe',
      'receive_broadcasts': 'Gba Aw\u1ecdn Ikede',
      'receive_messages': 'Gba Aw\u1ecdn Ifiran\u1e63\u1eb9',
      'location_tracking': 'Ipam\u1ecd Ipo',
      'enable_location_tracking': 'Mu Ipam\u1ecd Ipo \u1e62i\u1e63\u1eb9',
      'disable_location_tracking': 'Pa Ipam\u1ecd Ipo',
      'tracking_interval': 'Aarin Ipam\u1ecd',
      'continuous': 'Lem\u1ecblem\u1ecd',
      'every_5_seconds': 'Ni gbogbo i\u1e63\u1eb9ju-aaya 5',
      'every_10_seconds': 'Ni gbogbo i\u1e63\u1eb9ju-aaya 10',
      'every_30_seconds': 'Ni gbogbo i\u1e63\u1eb9ju-aaya 30',
      'every_1_minute': 'Ni gbogbo i\u1e63\u1eb9ju 1',
      'every_5_minutes': 'Ni gbogbo i\u1e63\u1eb9ju 5',
      'every_15_minutes': 'Ni gbogbo i\u1e63\u1eb9ju 15',
      'every_30_minutes': 'Ni gbogbo i\u1e63\u1eb9ju 30',
      'every_1_hour': 'Ni gbogbo wakati 1',
      'battery_saving': 'Fifipam\u1ecd Batiri',
      'balanced': 'Iwontunw\u1ecdnsi',
      'high_accuracy': 'Ipele Giga',
      'power_saving_mode': 'Ipo Fifipam\u1ecd Agbara',
      'ultra_power_saving': 'Fifipam\u1ecd Agbara Pup\u1ecd',
      'performance_mode': 'Ipo I\u1e63e',
      'data_saver': 'Fifipam\u1ecd Data',
      'offline_data': 'Data Aisinipo',
      'download_offline_maps': 'Gba Aw\u1ecdn Maapu Aisinipo',
      'offline_maps_downloaded': 'Aw\u1ecdn maapu aisinipo ti gba lati ayelujara',
      'offline_maps_failed': 'Kuna lati gba aw\u1ecdn maapu aisinipo',
      'download_size': 'Iw\u1ecdn Gbigba',
      'available_offline': 'Wa Aisinipo',
      'make_available_offline': '\u1e62e ki o Wa Aisinipo',
      'remove_from_offline': 'Y\u1ecd kuro ni Aisinipo',
      'offline_resources': 'Aw\u1ecdn Ohun elo Aisinipo',
      'no_offline_data': 'Ko si data aisinipo to wa',
      'walkie_talkie': 'Walkie Talkie',
      'walkie_talkie_monitor': 'At\u1eb9le Walkie Talkie',
      'press_to_talk': 'T\u1eb9 lati S\u1ecdr\u1ecd',
      'release_to_send': 'Tu sil\u1eb9 lati Firan\u1e63\u1eb9',
      'recording': 'Gbigbasil\u1eb9...',
      'listening': 'Gbigb\u1ecd...',
      'speak_now': 'S\u1ecdr\u1ecd ni bayi',
      'audio_message': 'Ifiran\u1e63\u1eb9 Ohun',
      'audio_message_sent': 'Ifiran\u1e63\u1eb9 ohun ti firan\u1e63\u1eb9',
      'audio_message_failed': 'Kuna lati fi ifiran\u1e63\u1eb9 ohun ran\u1e63\u1eb9',
      'play': '\u1e62i\u1e63\u1eb9',
      'pause_audio': 'Duro',
      'stop_audio': 'Duro',
      'volume': 'Ipele ohun',
      'mute': 'Pa ohun',
      'unmute': 'Mu ohun \u1e63i\u1e63\u1eb9',
      'speaker': 'Agbohun',
      'earpiece': 'Earpiece',
      'bluetooth': 'Bluetooth',
      'connected_devices': 'Aw\u1ecdn \u1eb8r\u1ecd ti a ti sop\u1ecd',
      'no_devices': 'Ko si aw\u1ecdn \u1eb9r\u1ecd ti a ti sop\u1ecd',
      'pair_new_device': 'So \u1eb8r\u1ecd Tuntun',
      'device_name': 'Oruk\u1ecd \u1eb8r\u1ecd',
      'device_type': 'Iru \u1eb8r\u1ecd',
      'signal_strength': 'Agbara Ifihan',
      'battery_level': 'Ipele Batiri',
      'device_connected': '\u1eccr\u1ecd ti sop\u1ecd',
      'device_disconnected': '\u1eccr\u1ecd ti ge asop\u1ecd',
      'connection_lost': 'Asop\u1ecd ti s\u1ecdn\u00f9',
      'reconnecting': 'Tun sop\u1ecd...',
      'scanning': '\u1e62i\u1e63ay\u1eb9wo...',
      'scan_complete': '\u1e62i\u1e63ay\u1eb9wo ti pari',
      'no_devices_found': 'Ko si aw\u1ecdn \u1eb9r\u1ecd ti a ri',
      'found_devices': 'Aw\u1ecdn \u1eb8r\u1ecd ti a ri',
      'connect': 'Sop\u1ecd',
      'disconnect': 'Ge asop\u1ecd',
      'forget_device': 'Gbagbe \u1eb8r\u1ecd',
      'pairing': 'Sisop\u1ecd...',
      'paired': 'Ti sop\u1ecd',
      'pairing_failed': 'Sisop\u1ecd kuna',
      'enter_pin': 'T\u1eb9 PIN sii',
      'incorrect_pin': 'PIN ti ko t\u1ecd',
      'map': 'Maapu',
      'satellite': 'Sat\u1eb9la\u1ecbti',
      'terrain': 'Il\u1eb9',
      'traffic': 'Ijab\u1ecd',
      'heatmap': 'Ooru maapu',
      'incident_heatmap': 'Ooru maapu I\u1e63\u1eb9l\u1eb9',
      'my_location': 'Ipo Mi',
      'zoom_in': 'Sunmo',
      'zoom_out': 'Jinna',
      'center_map': 'Maapu Aarin',
      'map_layers': 'Aw\u1ecdn Ipele Maapu',
      'map_style': 'Ara Maapu',
      'standard': 'Bo\u1e63ewa',
      'navigation': 'It\u1ecds\u1ecdna',
      'hybrid': 'Arabara',
      'dark': 'Dudu',
      'zones': 'Aw\u1ecdn Agbegbe',
      'danger_zone': 'Agbegbe Ewu',
      'safe_zone': 'Agbegbe Ailewu',
      'restricted_zone': 'Agbegbe Idinam\u1ecd',
      'zone_details': 'Aw\u1ecdn Alaye Agbegbe',
      'zone_name': 'Oruk\u1ecd Agbegbe',
      'zone_type': 'Iru Agbegbe',
      'zone_boundary': 'Aala Agbegbe',
      'zone_radius': 'Redio Agbegbe',
      'enter_zone': 'W\u1ecd Agbegbe',
      'exit_zone': 'Jade Agbegbe',
      'approaching_zone': 'Sunmo Agbegbe',
      'zone_alert': 'Itaniji Agbegbe',
      'you_are_here': 'O wa nibi',
      'distance': 'Ijinna',
      'estimated_time': 'Akoko Ifoju',
      'arrival': 'Dide',
      'departure': 'Il\u1ecdkuro',
      'eta': 'ETA',
      'directions': 'Aw\u1ecdn It\u1ecds\u1ecdna',
      'route': 'Ipa-\u1ecdcna',
      'alternative_route': 'Ipa-\u1ecdcna Yiyan',
      'fastest_route': 'Ipa-\u1ecdcna Yara Ju',
      'safest_route': 'Ipa-\u1ecdcna Ailewu Ju',
      'shortest_route': 'Ipa-\u1ecdcna Kukuru Ju',
      'route_saved': 'Ipa-\u1ecdcna ti fipam\u1ecd',
      'route_cleared': 'Ipa-\u1ecdcna ti nu',
      'start_navigation': 'B\u1eb9r\u1eb9 It\u1ecds\u1ecdna',
      'stop_navigation': 'Duro It\u1ecds\u1ecdna',
      'navigation_started': 'It\u1ecds\u1ecdna ti b\u1eb9r\u1eb9',
      'navigation_ended': 'It\u1ecds\u1ecdna ti pari',
      'recalculating': 'Tun \u1e63e i\u1e63iro...',
      'turn_left': 'Yipada si osi',
      'turn_right': 'Yipada si otun',
      'go_straight': 'L\u1ecd taara',
      'arrived': 'Ti de',
      'destination_reached': 'O ti de ibi ti o nlo',
      'off_route': 'O wa ni ita ipa-\u1ecdcna',
      'stay_on_route': 'Duro lori ipa-\u1ecdcna ti a gbero',
      'danger_ahead': 'Ewu ni iwaju',
      'caution': 'I\u1e63\u1ecdra',
      'proceed_with_caution': 'Tesiwaju p\u1eb9lu i\u1e63\u1ecdra',
      'avoid_area': 'Yago fun agbegbe yii',
      'reported_incident_ahead': 'I\u1e63\u1eb9l\u1eb9 ti a royin ni iwaju',
      'heavy_traffic': 'Ijab\u1ecd nla',
      'road_closure': 'Titipa opopona',
      'construction': 'Ikole',
      'accident': 'Ijamba',
      'weather_alert': 'Itaniji Oju-\u1ecdcj\u1ecd',
      'security_checkpoint': 'Ibi ay\u1eb9wo Aabo',
      'permission_storage': 'A nilo igbanilaaye ibi ipam\u1ecd lati fi aw\u1ecdn faili \u1eb9ri pam\u1ecd',
    },
    'ig': {
      'app_name': 'Sectop',
      'ok': '\u1ecc D\u1ecbkwa',
      'cancel': 'Kagbuo',
      'save': 'Chekwa',
      'delete': 'Hichap\u1ee5',
      'edit': 'Dezie',
      'retry': 'Nwaa \u1ecdz\u1ecd',
      'loading': 'Na-ebunye...',
      'error': 'Njehie',
      'success': '\u1eccganihu',
      'warning': '\u1eccd\u1ecd aka n\u00e1 nt\u1ecb',
      'info': 'Ozi',
      'confirm': 'Kwenye',
      'yes': 'Ee',
      'no': 'Mba',
      'back': 'Laghachi',
      'next': 'Osote',
      'submit': 'Nyefee',
      'search': 'Ch\u1ecd\u1ecd',
      'filter': 'Nyochaa',
      'sort': 'Hazie',
      'refresh': 'Meghar\u1ecba',
      'settings': 'Nt\u1ecdala',
      'profile': 'Profa\u1ecbl\u1ee5',
      'logout': 'Wep\u1ee5',
      'login': 'Banye',
      'register': 'Deba aha',
      'home': '\u1ee4l\u1ecd',
      'dashboard': 'Dasiboodu',
      'notifications': 'Ngosi',
      'messages': 'Ozi',
      'alerts': '\u1eccd\u1ecd aka n\u00e1 nt\u1ecb',
      'emergency': 'Ihe mberede',
      'sos': 'SOS',
      'panic_button': 'B\u1ecdt\u1ecbn\u1ecb \u1ee4j\u1ecd',
      'send_sos': 'Ziga SOS',
      'cancel_sos': 'Kagbuo SOS',
      'sos_sent': 'Ezigala SOS!',
      'sos_cancelled': 'Akagbuola SOS',
      'location': 'Ebe',
      'latitude': 'Latitjudu',
      'longitude': 'Longitjudu',
      'accuracy': 'Izi ezi',
      'address': 'Adiresi',
      'city': 'Obodo',
      'state': 'Steeti',
      'country': 'Obodo',
      'phone': 'Ekwent\u1ecb',
      'email': 'Imeeli',
      'password': 'Okwuntughe',
      'confirm_password': 'Kwenye Okwuntughe',
      'forgot_password': 'Chefuru Okwuntughe?',
      'reset_password': 'Tughar\u1ecba Okwuntughe',
      'new_password': 'Okwuntughe \u1ecch\u1ee5r\u1ee5',
      'old_password': 'Okwuntughe Ochie',
      'change_password': 'Gbanwee Okwuntughe',
      'name': 'Aha',
      'full_name': 'Aha Zuru',
      'username': 'Aha njirimara',
      'phone_number': 'N\u1ecdmba Ekwent\u1ecb',
      'date_of_birth': '\u1ee4b\u1ecdch\u1ecb \u1eccm\u1ee5m\u1ee5',
      'gender': 'Okike',
      'male': 'Nwoke',
      'female': 'Nwany\u1ecb',
      'other': '\u1eccz\u1ecd',
      'blood_type': '\u1ee4d\u1ecb \u1eccbara',
      'medical_conditions': '\u1eccn\u1ecddu\u1ee5 Ah\u1ee5ike',
      'allergies': 'Ihe Ah\u1ee5 Na-anabata',
      'emergency_contact': 'K\u1ecdntakt\u1ecb Mberede',
      'emergency_contacts': 'K\u1ecdntakt\u1ecb Mberede',
      'add_contact': 'Tinye K\u1ecdntakt\u1ecb',
      'remove_contact': 'Wep\u1ee5 K\u1ecdntakt\u1ecb',
      'contact_name': 'Aha K\u1ecdntakt\u1ecb',
      'contact_phone': 'Ekwent\u1ecb K\u1ecdntakt\u1ecb',
      'relationship': 'Mmet\u1ee5ta',
      'save_contact': 'Chekwa K\u1ecdntakt\u1ecb',
      'no_contacts': 'Enwegh\u1ecb k\u1ecdntakt\u1ecb mberede agbakwunyere',
      'first_aid': 'Enyemaka Mb\u1ee5',
      'first_aid_guides': 'Nduzi Enyemaka Mb\u1ee5',
      'first_aid_tips': 'Nd\u1ee5m\u1ecddu\u1ee5 Enyemaka Mb\u1ee5',
      'bleeding': '\u1eccbara',
      'burns': '\u1ecck\u1ee5',
      'fractures': '\u1ecckp\u1ee5kp\u1ee5',
      'choking': 'Nkpagbu',
      'cpr': 'CPR',
      'poisoning': 'Ns\u1ecb',
      'shock': 'Ujo',
      'heart_attack': 'Nk\u1ee5chi Obi',
      'stroke': '\u1eccr\u1ecba \u1ee4b\u1ee5r\u1ee5',
      'seizure': '\u1eccd\u1ecbd\u1ecd',
      'snake_bite': 'Agw\u1ecd Taa',
      'drowning': 'Mikpu',
      'emergency_numbers': 'N\u1ecdmba Mberede',
      'police': 'Nd\u1ecb Uwe Ojii',
      'ambulance': '\u1ee4gb\u1ecd Ihe Mberede',
      'fire_service': '\u1eccr\u1ee5 \u1ecck\u1ee5',
      'road_safety': 'Nchebe Okporo \u1ee4z\u1ecd',
      'civil_defence': 'Nchebe Obodo',
      'coast_guard': 'Nchebe Osimiri',
      'nema': 'NEMA',
      'nigerian_police': 'Nd\u1ecb Uwe Ojii Naijiria',
      'federal_road_safety': '\u1ee4l\u1ecd \u1eccr\u1ee5 Nchebe Okporo \u1ee4z\u1ecd G\u1ecd\u1ecdmmenti Etiti',
      'nigerian_ambulance': '\u1eccr\u1ee5 \u1ee4gb\u1ecd Ihe Mberede Naijiria',
      'nigerian_fire_service': '\u1eccr\u1ee5 \u1ecck\u1ee5 Naijiria',
      'nigerian_civil_defence': '\u1ee4l\u1ecd \u1eccr\u1ee5 Nchebe na Nchedo Obodo Naijiria',
      'ncdc': 'NCDC',
      'nigerian_coast_guard': 'Nchebe Osimiri Naijiria',
      'nigerian_air_force': 'Nd\u1ecb Agha Ikuku Naijiria',
      'nigerian_army': 'Nd\u1ecb Agha Naijiria',
      'nigerian_navy': 'Nd\u1ecb Agha Mmiri Naijiria',
      'nigerian_red_cross': 'Red Cross Naijiria',
      'nigerian_nema': '\u1ee4l\u1ecd \u1eccr\u1ee5 Nch\u1ecbkwa Mberede Mba',
      'safety_tips': 'Nd\u1ee5m\u1ecddu\u1ee5 Nchebe',
      'disaster_preparedness': 'Nkwadebe \u1eccdachi',
      'natural_disasters': '\u1eccdachi Nd\u1ecb Eke',
      'flood': 'Ide Mmiri',
      'earthquake': 'Ala \u1eccma jijiji',
      'landslide': 'Mgbada Ala',
      'volcanic_eruption': 'Ugwu \u1ecdk\u1ee5',
      'tsunami': 'Tsunami',
      'hurricane': 'Ok\u00e9 Ifufe',
      'tornado': 'Tornado',
      'wildfire': '\u1ecck\u1ee5 \u1ecch\u1ecba',
      'pandemic': '\u1eccr\u1ecba Na-efe efe',
      'terrorist_attack': 'Mwakpo Nd\u1ecb \u1ecct\u1ee5r\u1ee5gba',
      'active_shooter': 'Onye Na-agba Egbe',
      'bomb_threat': 'Iyi Egwu B\u1ecdmbu',
      'kidnapping': 'Nt\u1ecdr\u1ecd',
      'robbery': 'Izu',
      'domestic_violence': 'Ime Ihe Ike N\u2019\u1ee5l\u1ecd',
      'sexual_assault': 'Mwakpo Mmek\u1ecdah\u1ee5',
      'human_trafficking': '\u1eccz\u1ee5 Ah\u1ecba Mmad\u1ee5',
      'cyberbullying': 'Iji Mmad\u1ee5 Me Ihe N\u2019\u1ee4ntanet',
      'online_scam': 'Agh\u1ee5gh\u1ecd N\u2019\u1ee4ntanet',
      'identity_theft': 'Ohi Njirimara',
      'report_incident': 'K\u1ecd\u1ecd Ihe Mere',
      'report_crime': 'K\u1ecd\u1ecd Mp\u1ee5',
      'report_emergency': 'K\u1ecd\u1ecd Ihe Mberede',
      'tip_off': 'Nt\u1ee5nye',
      'anonymous_tip': 'Nt\u1ee5nye Na-amagh\u1ecb Aha',
      'submit_tip': 'Nyefee Nt\u1ee5nye',
      'tip_submitted': 'Enyefela nt\u1ee5nye nke \u1ecdcma',
      'tip_failed': '\u1ecc dara \u1ecbnyefe nt\u1ee5nye',
      'tip_description': 'Nk\u1ecdwa Nt\u1ee5nye',
      'attach_evidence': 'Tinye Ihe Ngbak\u1ecd',
      'take_photo': 'Sere Foto',
      'choose_from_gallery': 'H\u1ecdr\u1ecd Site na Gallery',
      'record_audio': 'Dek\u1ecd \u1eccd\u1ecbyo',
      'record_video': 'Dek\u1ecd Vidio',
      'select_file': 'H\u1ecdr\u1ecd Fa\u1ecbl\u1ee5',
      'remove_file': 'Wep\u1ee5 Fa\u1ecbl\u1ee5',
      'evidence': 'Ihe Ngbak\u1ecd',
      'no_evidence': 'Enwegh\u1ecb ihe ngbak\u1ecd agbakwunyere',
      'incident_report': 'Ak\u1ee5k\u1ecd Ihe Mere',
      'incident_type': '\u1ee4d\u1ecb Ihe Mere',
      'incident_date': '\u1ee4b\u1ecdch\u1ecb Ihe Mere',
      'incident_location': 'Ebe Ihe Mere',
      'incident_description': 'Nk\u1ecdwa Ihe Mere',
      'incident_status': '\u1eccn\u1ecddu\u1ee5 Ihe Mere',
      'incident_severity': 'Ogo Ihe Mere',
      'low': 'D\u1ecb ala',
      'medium': '\u1ecckara',
      'high': 'D\u1ecb elu',
      'critical': 'D\u1ecb ok\u00e9 mkpa',
      'pending': 'Na-echere',
      'in_progress': 'Na-aga n\u2019ihu',
      'resolved': 'Edozila',
      'closed': 'Emechiela',
      'verified': 'Enyochala',
      'unverified': 'Enwebegh\u1ecb nyocha',
      'nearby_incidents': 'Ihe Mere D\u1ecb Nso',
      'no_incidents': 'Enwegh\u1ecb ihe mere ak\u1ecdr\u1ecd nso',
      'safe_route': '\u1ee4z\u1ecd Nchebe',
      'plan_route': 'Hazie \u1ee4z\u1ecd',
      'current_location': 'Ebe \u1ecb N\u1ecd',
      'destination': 'Ebe \u1ecb Na-aga',
      'route_planned': 'Emeela at\u1ee5mat\u1ee5 \u1ee5z\u1ecd nke \u1ecdcma',
      'route_error': '\u1ecc dara \u1ecbhazi \u1ee5z\u1ecd',
      'danger_zones': 'Mpaghara Ihe Egwu',
      'avoid_areas': 'Mpaghara \u1ecb Zere',
      'safe_areas': 'Mpaghara Nchebe',
      'threat_level': '\u1ecckwa Ihe Egwu',
      'threat_assessment': 'Nt\u1ee5le Ihe Egwu',
      'threat_detected': 'Ach\u1ecdp\u1ee5tala Ihe Egwu',
      'no_threats': 'Enwegh\u1ecb ihe egwu ach\u1ecdp\u1ee5tara',
      'threat_awareness': '\u1ecamara Ihe Egwu',
      'nearby_threats': 'Ihe Egwu D\u1ecb Nso',
      'threat_history': 'Ak\u1ee5k\u1ecd Ihe Egwu',
      'threat_analysis': 'Nyocha Ihe Egwu',
      'community_alerts': '\u1eccd\u1ecd Aka n\u00e1 Nt\u1ecb Obodo',
      'broadcast': 'Mgbasa Ozi',
      'create_b