#!/usr/bin/env python3
"""Generate complete localization.dart with all 4 languages."""
import os, json

# Read the existing truncated file to get the English keys
# Then append the complete remaining content

# First, let's define the complete data structure
# We'll read the existing file and fix it

def main():
    dart_file = os.path.join(os.path.dirname(__file__), 'frontend', 'lib', 'core', 'localization.dart')
    part1_file = os.path.join(os.path.dirname(__file__), 'frontend', 'lib', 'core', 'localization_part1.dart')
    
    # Read the part1 file (first 611 lines of good content)
    with open(part1_file, 'r', encoding='utf-8') as f:
        part1 = f.read()
    
    # Find the last complete line in part1
    lines = part1.split('\n')
    # The last line is truncated at 'please_enter_phone': 'Jọwọ t
    # We need to find the last complete entry
    
    # Find where the Yoruba section starts
    yoruba_start = -1
    for i, line in enumerate(lines):
        if "'en': {" in line:
            break
    
    # The file structure is:
    # _localizedValues = {
    #   'en': { ... },
    #   'yo': { ... },
    #   'ig': { ... },
    #   'ha': { ... },
    # };
    
    # We need to rebuild the file completely
    # Let's extract English keys from the part1 file
    
    # Actually, let's just write the complete file using the part1 as base
    # and append the missing content
    
    # Find the last complete line before truncation
    # The truncation is at 'please_enter_phone': 'Jọwọ t
    # So we need to complete that line and add all remaining keys
    
    # Find the index of the truncated line
    trunc_idx = -1
    for i, line in enumerate(lines):
        if "please_enter_phone" in line:
            trunc_idx = i
            break
    
    if trunc_idx >= 0:
        # Fix the truncated line
        lines[trunc_idx] = "      'please_enter_phone': 'Jọwọ tẹ nọmba foonu rẹ sii',"
    
    # Now we need to add all remaining Yoruba keys, then Igbo, then Hausa
    # Let's build the complete content
    
    # Remaining Yoruba keys (after please_enter_phone)
    yo_remaining = {
        'please_enter_password': 'Jọwọ tẹ ọrọigbaniwọle rẹ sii',
        'please_enter_valid_password': 'Jọwọ tẹ ọrọigbaniwọle to wulo sii (o kere ju 6 lẹta)',
        'please_confirm_password': 'Jọwọ jẹrisi ọrọigbaniwọle rẹ',
        'password_too_short': 'Ọrọigbaniwọle gbọdọ kere ju 6 lẹta',
        'passwords_do_not_match': 'Awọn ọrọigbaniwọle ko baramu',
        'invalid_email_format': 'Ọna imeeli ti ko wulo',
        'field_required': 'Aaye yii ni a nilo',
        'invalid_input': 'Iṣawọle ti ko wulo',
        'operation_successful': 'Iṣẹ naa ṣaṣeyọri',
        'operation_failed': 'Iṣẹ naa kuna',
        'changes_saved': 'Awọn ayipada ti fipamọ ni aṣeyọri',
        'changes_discarded': 'Awọn ayipada ti sọnù',
        'unsaved_changes': 'O ni awọn ayipada ti a ko fipamọ',
        'discard_changes': 'Sọ awọn ayipada nù?',
        'stay_and_continue': 'Duro ki o tẹsiwaju ṣatunkọ',
        'confirm_discard': 'Ṣe o da ọ loju pe o fẹ sọ awọn ayipada rẹ nù?',
        'confirm_delete': 'Ṣe o da ọ loju pe o fẹ pa eyi rẹ?',
        'confirm_logout': 'Ṣe o da ọ loju pe o fẹ jade?',
        'session_timeout': 'Akoko igba rẹ ti pari',
        'session_timeout_desc': 'Jọwọ wọle lẹẹkansi lati tẹsiwaju',
        'update_profile': 'Ṣe Imudojuiwọn Profaili',
        'profile_updated': 'Profaili ti ni imudojuiwọn ni aṣeyọri',
        'profile_update_failed': 'Kuna lati ṣe imudojuiwọn profaili',
        'change_profile_picture': 'Yi Aworan Profaili Pada',
        'remove_profile_picture': 'Yọ Aworan Profaili',
        'select_image': 'Yan Aworan',
        'image_too_large': 'Aworan ti tobi ju',
        'unsupported_format': 'Ọna faili ti ko ni atilẹyin',
        'uploading': 'Gbigbe si oke...',
        'upload_complete': 'Gbigbe si oke ti pari',
        'upload_failed': 'Gbigbe si oke kuna',
        'downloading': 'Gbigba lati ayelujara...',
        'download_complete': 'Gbigba lati ayelujara ti pari',
        'download_failed': 'Gbigba lati ayelujara kuna',
        'processing': 'Ṣiṣẹ...',
        'please_wait': 'Jọwọ duro...',
        'time_estimate': 'Akoko ifoju:',
        'remaining': 'ti o ku',
        'completed': 'Ti pari',
        'progress': 'Ilọsiwaju',
        'task_completed': 'Iṣẹ-ṣiṣe ti pari',
        'task_failed': 'Iṣẹ-ṣiṣe kuna',
        'task_cancelled': 'Iṣẹ-ṣiṣe ti fagilee',
        'start': 'Bẹrẹ',
        'stop': 'Duro',
        'pause': 'Duro fun igba diẹ',
        'resume': 'Tesiwaju',
        'enable': 'Mu ṣiṣẹ',
        'disable': 'Pa',
        'enabled': 'Ṣiṣẹ',
        'disabled': 'Pa',
        'on': 'Ni',
        'off': 'Pa',
        'auto': 'Aifọwọyi',
        'manual': 'Afọwọṣe',
        'more': 'Diẹ sii',
        'less': 'Kere',
        'show_all': 'Fi Gbogbo Han',
        'show_less': 'Fi Kere Han',
        'show_more': 'Fi Diẹ sii Han',
        'select_all': 'Yan Gbogbo',
        'deselect_all': 'Yọ Gbogbo',
        'clear': 'Nu',
        'clear_all': 'Nu Gbogbo',
        'reset': 'Tunto',
        'reset_all': 'Tunto Gbogbo',
        'default': 'Aiyipada',
        'custom': 'Ara',
        'advanced': 'Ilọsiwaju',
        'basic': 'Ipilẹ',
        'general': 'Gbogbogbo',
        'security': 'Aabo',
        'privacy': 'Asiri',
        'account': 'Akọọlẹ',
        'data_usage': 'Lilo Data',
        'storage': 'Ibi ipamọ',
        'cache': 'Kaṣe',
        'clear_cache': 'Nu Kaṣe',
        'cache_cleared': 'Kaṣe ti nu',
        'cache_size': 'Iwọn Kaṣe',
        'notifications_settings': 'Eto Ifitonileti',
        'sound': 'Ohun',
        'vibrate': 'Gbigbọn',
        'silent': 'Ipalọlọ',
        'loud': 'Ariwo',
        'notification_sound': 'Ohun Ifitonileti',
        'emergency_alert_sound': 'Ohun Itaniji Pajawiri',
        'sos_activation_sound': 'Ohun Imuṣiṣẹ SOS',
        'enable_notifications': 'Mu Awọn Ifitonileti Ṣiṣẹ',
        'disable_notifications': 'Pa Awọn Ifitonileti',
        'notification_preferences': 'Awọn Ayanfẹ Ifitonileti',
        'receive_emergency_alerts': 'Gba Awọn Itaniji Pajawiri',
        'receive_community_alerts': 'Gba Awọn Itaniji Agbegbe',
        'receive_broadcasts': 'Gba Awọn Ikede',
        'receive_messages': 'Gba Awọn Ifiranṣẹ',
        'location_tracking': 'Ipamọ Ipo',
        'enable_location_tracking': 'Mu Ipamọ Ipo Ṣiṣẹ',
        'disable_location_tracking': 'Pa Ipamọ Ipo',
        'tracking_interval': 'Aarin Ipamọ',
        'continuous': 'Lemọlemọ',
        'every_5_seconds': 'Ni gbogbo iṣẹju-aaya 5',
        'every_10_seconds': 'Ni gbogbo iṣẹju-aaya 10',
        'every_30_seconds': 'Ni gbogbo iṣẹju-aaya 30',
        'every_1_minute': 'Ni gbogbo iṣẹju 1',
        'every_5_minutes': 'Ni gbogbo iṣẹju 5',
        'every_15_minutes': 'Ni gbogbo iṣẹju 15',
        'every_30_minutes': 'Ni gbogbo iṣẹju 30',
        'every_1_hour': 'Ni gbogbo wakati 1',
        'battery_saving': 'Fifipamọ Batiri',
        'balanced': 'Iwontunwọnsi',
        'high_accuracy': 'Ipele Giga',
        'power_saving_mode': 'Ipo Fifipamọ Agbara',
        'ultra_power_saving': 'Fifipamọ Agbara Pupọ',
        'performance_mode': 'Ipo Iṣe',
        'data_saver': 'Fifipamọ Data',
        'offline_data': 'Data Aisinipo',
        'download_offline_maps': 'Gba Awọn Maapu Aisinipo',
        'offline_maps_downloaded': 'Awọn maapu aisinipo ti gba lati ayelujara',
        'offline_maps_failed': 'Kuna lati gba awọn maapu aisinipo',
        'download_size': 'Iwọn Gbigba',
        'available_offline': 'Wa Aisinipo',
        'make_available_offline': 'Ṣe ki o Wa Aisinipo',
        'remove_from_offline': 'Yọ kuro ni Aisinipo',
        'offline_resources': 'Awọn Ohun elo Aisinipo',
        'no_offline_data': 'Ko si data aisinipo to wa',
        'walkie_talkie': 'Walkie Talkie',
        'walkie_talkie_monitor': 'Atẹle Walkie Talkie',
        'press_to_talk': 'Tẹ lati Sọrọ',
        'release_to_send': 'Tu silẹ lati Firanṣẹ',
        'recording': 'Gbigbasilẹ...',
        'listening': 'Gbigbọ...',
        'speak_now': 'Sọrọ ni bayi',
        'audio_message': 'Ifiranṣẹ Ohun',
        'audio_message_sent': 'Ifiranṣẹ ohun ti firanṣẹ',
        'audio_message_failed': 'Kuna lati fi ifiranṣẹ ohun ranṣẹ',
        'play': 'Ṣiṣẹ',
        'pause_audio': 'Duro',
        'stop_audio': 'Duro',
        'volume': 'Ipele ohun',
        'mute': 'Pa ohun',
        'unmute': 'Mu ohun ṣiṣẹ',
        'speaker': 'Agbohun',
        'earpiece': 'Earpiece',
        'bluetooth': 'Bluetooth',
        'connected_devices': 'Awọn Ẹrọ ti a ti sopọ',
        'no_devices': 'Ko si awọn ẹrọ ti a ti sopọ',
        'pair_new_device': 'So Ẹrọ Tuntun',
        'device_name': 'Orukọ Ẹrọ',
        'device_type': 'Iru Ẹrọ',
        'signal_strength': 'Agbara Ifihan',
        'battery_level': 'Ipele Batiri',
        'device_connected': 'Ẹrọ ti sopọ',
        'device_disconnected': 'Ẹrọ ti ge asopọ',
        'connection_lost': 'Asopọ ti sọnu',
        'reconnecting': 'Tun sopọ...',
        'scanning': 'Ṣiṣayẹwo...',
        'scan_complete': 'Ṣiṣayẹwo ti pari',
        'no_devices_found': 'Ko si awọn ẹrọ ti a ri',
        'found_devices': 'Awọn ẹrọ ti a ri',
        'connect': 'Sopọ',
        'disconnect': 'Ge asopọ',
        'forget_device': 'Gbagbe Ẹrọ',
        'pairing': 'Sisopọ...',
        'paired': 'Ti sopọ',
        'pairing_failed': 'Sisopọ kuna',
        'enter_pin': 'Tẹ PIN sii',
        'incorrect_pin': 'PIN ti ko tọ',
        'map': 'Maapu',
        'satellite': 'Satẹlaịti',
        'terrain': 'Ilẹ',
        'traffic': 'Ijabọ',
        'heatmap': 'Ooru maapu',
        'incident_heatmap': 'Ooru maapu Iṣẹlẹ',
        'my_location': 'Ipo Mi',
        'zoom_in': 'Sunmo',
        'zoom_out': 'Jinna',
        'center_map': 'Maapu Aarin',
        'map_layers': 'Awọn Ipele Maapu',
        'map_style': 'Ara Maapu',
        'standard': 'Boṣewa',
        'navigation': 'Itọsọna',
        'hybrid': 'Arabara',
        'dark': 'Dudu',
        'zones': 'Awọn Agbegbe',
        'danger_zone': 'Agbegbe Ewu',
        'safe_zone': 'Agbegbe Ailewu',
        'restricted_zone': 'Agbegbe Idinamọ',
        'zone_details': 'Awọn Alaye Agbegbe',
        'zone_name': 'Orukọ Agbegbe',
        'zone_type': 'Iru Agbegbe',
        'zone_boundary': 'Aala Agbegbe',
        'zone_radius': 'Redio Agbegbe',
        'enter_zone': 'Wọ Agbegbe',
        'exit_zone': 'Jade Agbegbe',
        'approaching_zone': 'Sunmo Agbegbe',
        'zone_alert': 'Itaniji Agbegbe',
        'you_are_here': 'O wa nibi',
        'distance': 'Ijinna',
        'estimated_time': 'Akoko Ifoju',
        'arrival': 'Dide',
        'departure': 'Ilọkuro',
        'eta': 'ETA',
        'directions': 'Awọn Itọsọna',
        'route': 'Ipa-ọna',
        'alternative_route': 'Ipa-ọna Yiyan',
        'fastest_route': 'Ipa-ọna Yara Ju',
        'safest_route': 'Ipa-ọna Ailewu Ju',
        'shortest_route': 'Ipa-ọna Kukuru Ju',
        'route_saved': 'Ipa-ọna ti fipamọ',
        'route_cleared': 'Ipa-ọna ti nu',
        'start_navigation': 'Bẹrẹ Itọsọna',
        'stop_navigation': 'Duro Itọsọna',
        'navigation_started': 'Itọsọna ti bẹrẹ',
        'navigation_ended': 'Itọsọna ti pari',
        'recalculating': 'Tun ṣe iṣiro...',
        'turn_left': 'Yipada si osi',
        'turn_right': 'Yipada si otun',
        'go_straight': 'Lọ taara',
        'arrived': 'Ti de',
        'destination_reached': 'O ti de ibi ti o nlo',
        'off_route': 'O wa ni ita ipa-ọna',
        'stay_on_route': 'Duro lori ipa-ọna ti a gbero',
        'danger_ahead': 'Ewu ni iwaju',
        'caution': 'Iṣọra',
        'proceed_with_caution': 'Tesiwaju pẹlu iṣọra',
        'avoid_area': 'Yago fun agbegbe yii',
        'reported_incident_ahead': 'Iṣẹlẹ ti a royin ni iwaju',
        'heavy_traffic': 'Ijabọ nla',
        'road_closure': 'Titipa opopona',
        'construction': 'Ikole',
        'accident': 'Ijamba',
        'weather_alert': 'Itaniji Oju-ọjọ',
        'security_checkpoint': 'Ibi ayẹwo Aabo',
        'permission_storage': 'A nilo igbanilaaye ibi ipamọ lati fi awọn faili ẹri pamọ',
    }
    
    # Igbo translations
    igbo = {
        'app_name': 'Sectop',
        'ok': 'Ọ Dịkwa',
        'cancel': 'Kagbuo',
        'save': 'Chekwa',
        'delete': 'Hichapụ',
        'edit': 'Dezie',
        'retry': 'Nwaa ọzọ',
        'loading': 'Na-ebunye...',
        'error': 'Njehie',
        'success': 'Ọganihu',
        'warning': 'Ịdọ aka ná ntị',
        'info': 'Ozi',
        'confirm': 'Kwenye',
        'yes': 'Ee',
        'no': 'Mba',
        'back': 'Laghachi',
        'next': 'Osote',
        'submit': 'Nyefee',
        'search': 'Chọọ',
        'filter': 'Nyochaa',
        'sort': 'Hazie',
        'refresh': 'Megharịa',
        'settings': 'Ntọala',
        'profile': 'Profaịlụ',
        'logout': 'Wepụ',
        'login': 'Banye',
        'register': 'Deba aha',
        'home': 'Ụlọ',
        'dashboard': 'Dasiboodu',
        'notifications': 'Ngosi',
        'messages': 'Ozi',
        'alerts': 'Ịdọ aka ná ntị',
        'emergency': 'Ihe mberede',
        'sos': 'SOS',
        'panic_button': 'Bọtịnị Ụjọ',
        'send_sos': 'Ziga SOS',
        'cancel_sos': 'Kagbuo SOS',
        'sos_sent': 'Ezigala SOS!',
        'sos_cancelled': 'Akagbuola SOS',
        'location': 'Ebe',
        'latitude': 'Latitjudu',
        'longitude': 'Longitjudu',
        'accuracy': 'Izi ezi',
        'address': 'Adiresi',
        'city': 'Obodo',
        'state': 'Steeti',
        'country': 'Obodo',
        'phone': 'Ekwentị',
        'email': 'Imeeli',
        'password': 'Okwuntughe',
        'confirm_password': 'Kwenye Okwuntughe',
        'forgot_password': 'Chefuru Okwuntughe?',
        'reset_password': 'Tugharịa Okwuntughe',
        'new_password': 'Okwuntughe Ọhụrụ',
        'old_password': 'Okwuntughe Ochie',
        'change_password': 'Gbanwee Okwuntughe',
        'name': 'Aha',
        'full_name': 'Aha Zuru',
        'username': 'Aha njirimara',
        'phone_number': 'Nọmba Ekwentị',
        'date_of_birth': 'Ụbọchị Ọmụmụ',
        'gender': 'Okike',
        'male': 'Nwoke',
        'female': 'Nwanyị',
        'other': 'Ọzọ',
        'blood_type': 'Ụdị Ọbara',
        'medical_conditions': 'Ọnọdụ Ahụike',
        'allergies': 'Ihe Ahụ Na-anabata',
        'emergency_contact': 'Kọntaktị Mberede',
        'emergency_contacts': 'Kọntaktị Mberede',
        'add_contact': 'Tinye Kọntaktị',
        'remove_contact': 'Wepụ Kọntaktị',
        'contact_name': 'Aha Kọntaktị',
        'contact_phone': 'Ekwentị Kọntaktị',
        'relationship': 'Mmetụta',
        'save_contact': 'Chekwa Kọntaktị',
        'no_contacts': 'Enweghị kọntaktị mberede agbakwunyere',
        'first_aid': 'Enyemaka Mbụ',
        'first_aid_guides': 'Nduzi Enyemaka Mbụ',
        'first_aid_tips': 'Ndụmọdụ Enyemaka Mbụ',
        'bleeding': 'Ọbara',
        'burns': 'Ọkụ',
        'fractures': 'Ọkpụkpụ',
        'choking': 'Nkpagbu',
        'cpr': 'CPR',
        'poisoning': 'Nsị',
        'shock': 'Ujo',
        'heart_attack': 'Nkụchi Obi',
        'stroke': 'Ọrịa Ụbụrụ',
        'seizure': 'Ọdịdọ',
        'snake_bite': 'Agwọ Taa',
        'drowning': 'Mikpu',
        'emergency_numbers': 'Nọmba Mberede',
        'police': 'Ndị Uwe Ojii',
        'ambulance': 'Ụgbọ Ihe Mberede',
        'fire_service': 'Ọrụ Ọkụ',
        'road_safety': 'Nchebe Okporo Ụzọ',
        'civil_defence': 'Nchebe Obodo',
        'coast_guard': 'Nchebe Osimiri',
        'nema': 'NEMA',
        'nigerian_police': 'Ndị Uwe Ojii Naijiria',
        'federal_road_safety': 'Ụlọ Ọrụ Nchebe Okporo Ụzọ Gọọmenti Etiti',
        'nigerian_ambulance': 'Ọrụ Ụgbọ Ihe Mberede Naijiria',
        'nigerian_fire_service': 'Ọrụ Ọkụ Naijiria',
        'nigerian_civil_defence': 'Ụlọ Ọrụ Nchebe na Nchedo Obodo Naijiria',
        'ncdc': 'NCDC',
        'nigerian_coast_guard': 'Nchebe Osimiri Naijiria',
        'nigerian_air_force': 'Ndị Agha Ikuku Naijiria',
        'nigerian_army': 'Ndị Agha Naijiria',
        'nigerian_navy': 'Ndị Agha Mmiri Naijiria',
        'nigerian_red_cross': 'Red Cross Naijiria',
        'nigerian_nema': 'Ụlọ Ọrụ Nchịkwa Mberede Mba',
        'safety_tips': 'Ndụmọdụ Nchebe',
        'disaster_preparedness': 'Nkwadebe Ọdachi',
        'natural_disasters': 'Ọdachi Ndị Eke',
        'flood': 'Ide Mmiri',
        'earthquake': 'Ala Ọma jijiji',
        'landslide': 'Mgbada Ala',
        'volcanic_eruption': 'Ugwu ọkụ',
        'tsunami': 'Tsunami',
        'hurricane': 'Oké Ifufe',
        'tornado': 'Tornado',
        'wildfire': 'Ọkụ Ọhịa',
        'pandemic': 'Ọrịa Na-efe efe',
        'terrorist_attack': 'Mwakpo Ndị Ọtụrụgba',
        'active_shooter': 'Onye Na-agba Egbe',
        'bomb_threat': 'Iyi Egwu Bọmbụ',
        'kidnapping': 'Ntọrọ',
        'robbery': 'Izu',
        'domestic_violence': 'Ime Ihe Ike N'ụlọ',
        'sexual_assault': 'Mwakpo Mmekọahụ',
        'human_trafficking': 'Ịzụ Ahịa Mmadụ',
        'cyberbullying': 'Iji Mmadụ Me Ihe N'Ịntanet',
        'online_scam': 'Aghụghọ N'Ịntanet',
        'identity_theft': 'Ohi Njirimara',
        'report_incident': 'Kọọ Ihe Mere',
        'report_crime': 'Kọọ Mpụ',
        'report_emergency': 'Kọọ Ihe Mberede',
        'tip_off': 'Ntụnye',
        'anonymous_tip': 'Ntụnye Na-amaghị Aha',
        'submit_tip': 'Nyefee Ntụnye',
        'tip_submitted': 'Enyefela ntụnye nke ọma',
        'tip_failed': 'Ọ dara ịnyefe ntụnye',
        'tip_description': 'Nkọwa Ntụnye',
        'attach_evidence': 'Tinye Ihe Ngbakọ',
        'take_photo': 'Sere Foto',
        'choose_from_gallery': 'Họrọ Site na Gallery',
        'record_audio': 'Dekọ Ọdịyo',
        'record_video': 'Dekọ Vidio',
        'select_file': 'Họrọ Faịlụ',
        'remove_file': 'Wepụ Faịlụ',
        'evidence': 'Ihe Ngbakọ',
        'no_evidence': 'Enweghị ihe ngbakọ agbakwunyere',
        'incident_report': 'Akụkọ Ihe Mere',
        'incident_type': 'Ụdị Ihe Mere',
        'incident_date': 'Ụbọchị Ihe Mere',
        'incident_location': 'Ebe Ihe Mere',
        'incident_description': 'Nkọwa Ihe Mere',
        'incident_status': 'Ọnọdụ Ihe Mere',
        'incident_severity': 'Ogo Ihe Mere',
        'low': 'Dị ala',
        'medium': 'Ọkara',
        'high': 'Dị elu',
        'critical': 'Dị oké mkpa',
        'pending': 'Na-echere',
        'in_progress': 'Na-aga n'ihu',
        'resolved': 'Edozila',
        'closed': 'Emechiela',
        'verified': 'Enyochala',
        'unverified': 'Enwebeghị nyocha',
        'nearby_incidents': 'Ihe Mere Dị Nso',
        'no_incidents': 'Enweghị ihe mere akọrọ nso',
        'safe_route': 'Ụzọ Nchebe',
        'plan_route': 'Hazie Ụzọ',
        'current_location': 'Ebe Ị Nọ',
        'destination': 'Ebe Ị Na-aga',
        'route_planned': 'Emeela atụmatụ ụzọ nke ọma',
        'route_error': 'Ọ dara ịhazi ụzọ',
        'danger_zones': 'Mpaghara Ihe Egwu',
        'avoid_areas': 'Mpaghara Ị Zere',
        'safe_areas': 'Mpaghara Nchebe',
        'threat_level': 'Ọkwa Ihe Egwu',
        'threat_assessment': 'Ntụle Ihe Egwu',
        'threat_detected': 'Achọpụtala Ihe Egwu',
        'no_threats': 'Enweghị ihe egwu achọpụtara',
        'threat_awareness': 'Ịmara Ihe Egwu',
        'nearby_threats': 'Ihe Egwu Dị Nso',
        'threat_history': 'Akụkọ Ihe Egwu',
        'threat_analysis': 'Nyocha Ihe Egwu',
        'community_alerts': 'Ịdọ Aka ná Ntị Obodo',
        'broadcast': 'Mgbasa Ozi',
        'create_broadcast': 'Mepụta Mgbasa Ozi',
        'broadcast_message': 'Ozi Mgbasa Ozi',
        'broadcast_to': 'Gbasara',
        'everyone': 'Onye ọ bụla',
        'specific_zone': 'Mpaghara Akọwapụtara',
        'specific_users': 'Ndị ọrụ Akọwapụtara',
        'send_broadcast': 'Ziga Mgbasa Ozi',
        'broadcast_sent': 'Ezigala mgbasa ozi nke ọma',
        'broadcast_failed': 'Ọ dara iziga mgbasa ozi',
        'radio_broadcast': 'Mgbasa Ozi Redio',
        'radio_frequency': 'Ugboro Redio',
        'radio_message': 'Ozi Redio',
        'send_radio': 'Ziga Mgbasa Ozi Redio',
        'radio_sent': 'Ezigala mgbasa ozi redio',
        'radio_failed': 'Ọ dara iziga mgbasa ozi redio',
        'mesh_network': 'Netwọk Mesh',
        'mesh_status': 'Ọnọdụ Netwọk Mesh',
        'mesh_connected': 'Ejikọrọ na Netwọk Mesh',
        'mesh_disconnected': 'Ekwụsịrị na Netwọk Mesh',
        'mesh_nodes': 'Mesh Nodes',
        'mesh_messages': 'Ozi Mesh',
        'send_mesh': 'Ziga site na Mesh',
        'inbox': 'Igbe Ozi',
        'compose': 'Dee',
        'send': 'Ziga',
        'reply': 'Zaghachi',
        'forward': 'Gaa n'ihu',
        'mark_read': 'Gụọ',
        'mark_unread': 'Akpọghị ya',
        'no_messages': 'Enweghị ozi',
        'message_sent': 'Ezigala ozi',
        'message_failed': 'Ọ dara iziga ozi',
        'offline_mode': 'Ọnọdụ Ịntanet Na-adịghị',
        'online_mode': 'Ọnọdụ Ịntanet',
        'connecting': 'Na-ejikọ...',
        'connected': 'Ejikọrọ',
        'disconnected': 'Ekwụsịrị',
        'no_internet': 'Enweghị Njikọ Ịntanet',
        'weak_signal': 'Mgbama Na-adịghị ike',
        'strong_signal': 'Mgbama Siri ike',
        'battery_low': 'Batrị Dị ala',
        'battery_critical': 'Batrị Dị Oké Mkpa',
        'charging': 'Na-achọ',
        'gps_enabled': 'GPS Gbanyụrụ',
        'gps_disabled': 'GPS Gbanyụrụ',
        'enable_gps': 'Gbanwuo GPS',
        'enable_location': 'Gbanwuo Ọrụ Ebe',
        'location_permission': 'Ikike Ebe',
        'camera_permission': 'Ikike Igwefoto',
        'microphone_permission': 'Ikike Igwe Okwu',
        'storage_permission': 'Ikike Nchekwa',
        'notification_permission': 'Ikike Ngosi',
        'allow': 'Kwe',
        'deny': 'Jụ',
        'always_allow': 'Kwe Mgbe Nile',
        'allow_while_using': 'Kwe Mgbe Ị Na-eji Ngwa',
        'permission_required': 'Ikike Ọ dị mkpa',
        'permission_denied': 'Ajụla Ikike',
        'permission_granted': 'Enyela Ikike',
        'open_settings': 'Mepee Ntọala',
        'dark_mode': 'Ọnọdụ Ọchịchịrị',
        'light_mode': 'Ọnọdụ Ìhè',
        'system_mode': 'Ọnọdụ Sistemụ',
        'language': 'Asụsụ',
        'english': 'Bekee',
        'yoruba': 'Yoruba',
        'igbo': 'Igbo',
        'hausa': 'Hausa',
        'select_language': 'Họrọ Asụsụ',
        'about': 'Gbasara',
        'help': 'Enyemaka',
        'faq': 'FAQ',
        'contact_us': 'Kpọtụrụ Anyị',
        'privacy_policy': 'Amụma Nzuzo',
        'terms_of_service': 'Usoro Ọrụ',
        'rate_app': 'Nye Ngwa ọkwa',
        'share_app': 'Kesaa Ngwa',
        'version': 'Mpịakọta',
        'update_available': 'Mmelite Dị',
        'update_now': 'Melite Ugbu a',
        'skip