#!/usr/bin/env python3
"""Generate complete localization.dart with all 4 languages."""
import os

HEADER = """import 'package:flutter/material.dart';

/// Simple localization with Nigerian language support.
class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static final Map<String, Map<String, String>> _localizedValues = {
"""

# English keys
ENGLISH = {
    'app_name': 'Sectop',
    'ok': 'OK',
    'cancel': 'Cancel',
    'save': 'Save',
    'delete': 'Delete',
    'edit': 'Edit',
    'retry': 'Retry',
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'warning': 'Warning',
    'info': 'Info',
    'confirm': 'Confirm',
    'yes': 'Yes',
    'no': 'No',
    'back': 'Back',
    'next': 'Next',
    'submit': 'Submit',
    'search': 'Search',
    'filter': 'Filter',
    'sort': 'Sort',
    'refresh': 'Refresh',
    'settings': 'Settings',
    'profile': 'Profile',
    'logout': 'Logout',
    'login': 'Login',
    'register': 'Register',
    'home': 'Home',
    'dashboard': 'Dashboard',
    'notifications': 'Notifications',
    'messages': 'Messages',
    'alerts': 'Alerts',
    'emergency': 'Emergency',
    'sos': 'SOS',
    'panic_button': 'Panic Button',
    'send_sos': 'Send SOS Alert',
    'cancel_sos': 'Cancel SOS',
    'sos_sent': 'SOS Alert Sent!',
    'sos_cancelled': 'SOS Alert Cancelled',
    'location': 'Location',
    'latitude': 'Latitude',
    'longitude': 'Longitude',
    'accuracy': 'Accuracy',
    'address': 'Address',
    'city': 'City',
    'state': 'State',
    'country': 'Country',
    'phone': 'Phone',
    'email': 'Email',
    'password': 'Password',
    'confirm_password': 'Confirm Password',
    'forgot_password': 'Forgot Password?',
    'reset_password': 'Reset Password',
    'new_password': 'New Password',
    'old_password': 'Old Password',
    'change_password': 'Change Password',
    'name': 'Name',
    'full_name': 'Full Name',
    'username': 'Username',
    'phone_number': 'Phone Number',
    'date_of_birth': 'Date of Birth',
    'gender': 'Gender',
    'male': 'Male',
    'female': 'Female',
    'other': 'Other',
    'blood_type': 'Blood Type',
    'medical_conditions': 'Medical Conditions',
    'allergies': 'Allergies',
    'emergency_contact': 'Emergency Contact',
    'emergency_contacts': 'Emergency Contacts',
    'add_contact': 'Add Contact',
    'remove_contact': 'Remove Contact',
    'contact_name': 'Contact Name',
    'contact_phone': 'Contact Phone',
    'relationship': 'Relationship',
    'save_contact': 'Save Contact',
    'no_contacts': 'No emergency contacts added yet',
    'first_aid': 'First Aid',
    'first_aid_guides': 'First Aid Guides',
    'first_aid_tips': 'First Aid Tips',
    'bleeding': 'Bleeding',
    'burns': 'Burns',
    'fractures': 'Fractures',
    'choking': 'Choking',
    'cpr': 'CPR',
    'poisoning': 'Poisoning',
    'shock': 'Shock',
    'heart_attack': 'Heart Attack',
    'stroke': 'Stroke',
    'seizure': 'Seizure',
    'snake_bite': 'Snake Bite',
    'drowning': 'Drowning',
    'emergency_numbers': 'Emergency Numbers',
    'police': 'Police',
    'ambulance': 'Ambulance',
    'fire_service': 'Fire Service',
    'road_safety': 'Road Safety',
    'civil_defence': 'Civil Defence',
    'coast_guard': 'Coast Guard',
    'nema': 'NEMA',
    'nigerian_police': 'Nigerian Police',
    'federal_road_safety': 'Federal Road Safety Corps',
    'nigerian_ambulance': 'Nigerian Ambulance Service',
    'nigerian_fire_service': 'Nigerian Fire Service',
    'nigerian_civil_defence': 'Nigerian Security and Civil Defence Corps',
    'ncdc': 'NCDC',
    'nigerian_coast_guard': 'Nigerian Coast Guard',
    'nigerian_air_force': 'Nigerian Air Force',
    'nigerian_army': 'Nigerian Army',
    'nigerian_navy': 'Nigerian Navy',
    'nigerian_red_cross': 'Nigerian Red Cross',
    'nigerian_nema': 'National Emergency Management Agency',
    'safety_tips': 'Safety Tips',
    'disaster_preparedness': 'Disaster Preparedness',
    'natural_disasters': 'Natural Disasters',
    'flood': 'Flood',
    'earthquake': 'Earthquake',
    'landslide': 'Landslide',
    'volcanic_eruption': 'Volcanic Eruption',
    'tsunami': 'Tsunami',
    'hurricane': 'Hurricane',
    'tornado': 'Tornado',
    'wildfire': 'Wildfire',
    'pandemic': 'Pandemic',
    'terrorist_attack': 'Terrorist Attack',
    'active_shooter': 'Active Shooter',
    'bomb_threat': 'Bomb Threat',
    'kidnapping': 'Kidnapping',
    'robbery': 'Robbery',
    'domestic_violence': 'Domestic Violence',
    'sexual_assault': 'Sexual Assault',
    'human_trafficking': 'Human Trafficking',
    'cyberbullying': 'Cyberbullying',
    'online_scam': 'Online Scam',
    'identity_theft': 'Identity Theft',
    'report_incident': 'Report Incident',
    'report_crime': 'Report Crime',
    'report_emergency': 'Report Emergency',
    'tip_off': 'Tip Off',
    'anonymous_tip': 'Anonymous Tip',
    'submit_tip': 'Submit Tip',
    'tip_submitted': 'Tip submitted successfully',
    'tip_failed': 'Failed to submit tip',
    'tip_description': 'Tip Description',
    'attach_evidence': 'Attach Evidence',
    'take_photo': 'Take Photo',
    'choose_from_gallery': 'Choose from Gallery',
    'record_audio': 'Record Audio',
    'record_video': 'Record Video',
    'select_file': 'Select File',
    'remove_file': 'Remove File',
    'evidence': 'Evidence',
    'no_evidence': 'No evidence attached',
    'incident_report': 'Incident Report',
    'incident_type': 'Incident Type',
    'incident_date': 'Incident Date',
    'incident_location': 'Incident Location',
    'incident_description': 'Incident Description',
    'incident_status': 'Incident Status',
    'incident_severity': 'Incident Severity',
    'low': 'Low',
    'medium': 'Medium',
    'high': 'High',
    'critical': 'Critical',
    'pending': 'Pending',
    'in_progress': 'In Progress',
    'resolved': 'Resolved',
    'closed': 'Closed',
    'verified': 'Verified',
    'unverified': 'Unverified',
    'nearby_incidents': 'Nearby Incidents',
    'no_incidents': 'No incidents reported nearby',
    'safe_route': 'Safe Route',
    'plan_route': 'Plan Route',
    'current_location': 'Current Location',
    'destination': 'Destination',
    'route_planned': 'Route Planned Successfully',
    'route_error': 'Failed to plan route',
    'danger_zones': 'Danger Zones',
    'avoid_areas': 'Areas to Avoid',
    'safe_areas': 'Safe Areas',
    'threat_level': 'Threat Level',
    'threat_assessment': 'Threat Assessment',
    'threat_detected': 'Threat Detected',
    'no_threats': 'No threats detected',
    'threat_awareness': 'Threat Awareness',
    'nearby_threats': 'Nearby Threats',
    'threat_history': 'Threat History',
    'threat_analysis': 'Threat Analysis',
    'community_alerts': 'Community Alerts',
    'broadcast': 'Broadcast',
    'create_broadcast': 'Create Broadcast',
    'broadcast_message': 'Broadcast Message',
    'broadcast_to': 'Broadcast To',
    'everyone': 'Everyone',
    'specific_zone': 'Specific Zone',
    'specific_users': 'Specific Users',
    'send_broadcast': 'Send Broadcast',
    'broadcast_sent': 'Broadcast sent successfully',
    'broadcast_failed': 'Failed to send broadcast',
    'radio_broadcast': 'Radio Broadcast',
    'radio_frequency': 'Radio Frequency',
    'radio_message': 'Radio Message',
    'send_radio': 'Send Radio Broadcast',
    'radio_sent': 'Radio broadcast sent',
    'radio_failed': 'Failed to send radio broadcast',
    'mesh_network': 'Mesh Network',
    'mesh_status': 'Mesh Network Status',
    'mesh_connected': 'Connected to Mesh Network',
    'mesh_disconnected': 'Disconnected from Mesh Network',
    'mesh_nodes': 'Mesh Nodes',
    'mesh_messages': 'Mesh Messages',
    'send_mesh': 'Send via Mesh',
    'inbox': 'Inbox',
    'compose': 'Compose',
    'send': 'Send',
    'reply': 'Reply',
    'forward': 'Forward',
    'mark_read': 'Mark as Read',
    'mark_unread': 'Mark as Unread',
    'no_messages': 'No messages',
    'message_sent': 'Message sent',
    'message_failed': 'Failed to send message',
    'offline_mode': 'Offline Mode',
    'online_mode': 'Online Mode',
    'connecting': 'Connecting...',
    'connected': 'Connected',
    'disconnected': 'Disconnected',
    'no_internet': 'No Internet Connection',
    'weak_signal': 'Weak Signal',
    'strong_signal': 'Strong Signal',
    'battery_low': 'Battery Low',
    'battery_critical': 'Battery Critical',
    'charging': 'Charging',
    'gps_enabled': 'GPS Enabled',
    'gps_disabled': 'GPS Disabled',
    'enable_gps': 'Enable GPS',
    'enable_location': 'Enable Location Services',
    'location_permission': 'Location Permission',
    'camera_permission': 'Camera Permission',
    'microphone_permission': 'Microphone Permission',
    'storage_permission': 'Storage Permission',
    'notification_permission': 'Notification Permission',
    'allow': 'Allow',
    'deny': 'Deny',
    'always_allow': 'Always Allow',
    'allow_while_using': 'Allow While Using App',
    'permission_required': 'Permission Required',
    'permission_denied': 'Permission Denied',
    'permission_granted': 'Permission Granted',
    'open_settings': 'Open Settings',
    'dark_mode': 'Dark Mode',
    'light_mode': 'Light Mode',
    'system_mode': 'System Mode',
    'language': 'Language',
    'english': 'English',
    'yoruba': 'Yoruba',
    'igbo': 'Igbo',
    'hausa': 'Hausa',
    'select_language': 'Select Language',
    'about': 'About',
    'help': 'Help',
    'faq': 'FAQ',
    'contact_us': 'Contact Us',
    'privacy_policy': 'Privacy Policy',
    'terms_of_service': 'Terms of Service',
    'rate_app': 'Rate App',
    'share_app': 'Share App',
    'version': 'Version',
    'update_available': 'Update Available',
    'update_now': 'Update Now',
    'skip': 'Skip',
    'done': 'Done',
    'welcome': 'Welcome',
    'welcome_back': 'Welcome Back',
    'sign_in': 'Sign In',
    'sign_up': 'Sign Up',
    'create_account': 'Create Account',
    'already_have_account': 'Already have an account?',
    'dont_have_account': "Don't have an account?",
    'forgot_password_desc': 'Enter your email and we will send you a password reset link',
    'reset_link_sent': 'Password reset link sent to your email',
    'reset_password_desc': 'Enter your new password',
    'password_reset_success': 'Password reset successful',
    'password_changed': 'Password changed successfully',
    'account_deleted': 'Account deleted successfully',
    'delete_account': 'Delete Account',
    'delete_account_confirm': 'Are you sure you want to delete your account? This action cannot be undone.',
    'delete_account_warning': 'Your account will be permanently deleted after 30 days. You can cancel within this period.',
    'cancel_deletion': 'Cancel Deletion',
    'deletion_cancelled': 'Account deletion cancelled',
    'deletion_scheduled': 'Account deletion scheduled',
    'session_expired': 'Session Expired',
    'please_login_again': 'Please login again',
    'login_failed': 'Login failed',
    'registration_failed': 'Registration failed',
    'invalid_credentials': 'Invalid email or password',
    'email_already_exists': 'An account with this email already exists',
    'weak_password': 'Password is too weak',
    'password_mismatch': 'Passwords do not match',
    'terms_required': 'You must accept the terms of service',
    'network_error': 'Network error. Please check your connection.',
    'server_error': 'Server error. Please try again later.',
    'unknown_error': 'An unknown error occurred',
    'try_again': 'Try Again',
    'no_data': 'No data available',
    'no_results': 'No results found',
    'no_internet_desc': 'You are currently offline. Some features may be limited.',
    'offline_data_available': 'Offline data available',
    'offline_data_synced': 'Offline data synced',
    'syncing': 'Syncing...',
    'sync_complete': 'Sync complete',
    'sync_failed': 'Sync failed',
    'last_synced': 'Last synced',
    'emergency_access': 'Emergency Access',
    'emergency_access_desc': 'Access emergency features without login',
    'use_offline': 'Use in offline mode',
    'emergency_mode_active': 'Emergency Mode Active',
    'emergency_mode_desc': 'All non-essential features are disabled to save battery',
    'exit_emergency_mode': 'Exit Emergency Mode',
    'emergency_access_no_login': 'Emergency Access (No Login)',
    'use_in_disaster': 'Use in disaster situations when you cannot login',
    'skip_login_guest': 'Skip Login — Use as Guest',
    'browse_without_account': 'Browse alerts, view safe zones, and access emergency info without an account',
    'contact_support_email': 'Contact Support:',
    'authentication_failed': 'Authentication failed',
    'connection_error_offline': 'Connection error. Using offline mode.',
    'failed_emergency_mode': 'Failed to enter emergency mode',
    'please_enter_name': 'Please enter your name',
    'please_enter_email': 'Please enter your email',
    'please_enter_valid_email': 'Please enter a valid email',
    'please_enter_phone': 'Please enter your phone number',
    'please_enter_password': 'Please enter your password',
    'please_enter_valid_password': 'Please enter a valid password (min 6 characters)',
    'please_confirm_password': 'Please confirm your password',
    'password_too_short': 'Password must be at least 6 characters',
    'passwords_do_not_match': 'Passwords do not match',
    'invalid_email_format': 'Invalid email format',
    'field_required': 'This field is required',
    'invalid_input': 'Invalid input',
    'operation_successful': 'Operation successful',
    'operation_failed': 'Operation failed',
    'changes_saved': 'Changes saved successfully',
    'changes_discarded': 'Changes discarded',
    'unsaved_changes': 'You have unsaved changes',
    'discard_changes': 'Discard changes?',
    'stay_and_continue': 'Stay and continue editing',
    'confirm_discard': 'Are you sure you want to discard your changes?',
    'confirm_delete': 'Are you sure you want to delete this?',
    'confirm_logout': 'Are you sure you want to logout?',
    'session_timeout': 'Your session has timed out',
    'session_timeout_desc': 'Please login again to continue',
    'update_profile': 'Update Profile',
    'profile_updated': 'Profile updated successfully',
    'profile_update_failed': 'Failed to update profile',
    'change_profile_picture': 'Change Profile Picture',
    'remove_profile_picture': 'Remove Profile Picture',
    'select_image': 'Select Image',
    'image_too_large': 'Image is too large',
    'unsupported_format': 'Unsupported file format',
    'uploading': 'Uploading...',
    'upload_complete': 'Upload complete',
    'upload_failed': 'Upload failed',
    'downloading': 'Downloading...',
    'download_complete': 'Download complete',
    'download_failed': 'Download failed',
    'processing': 'Processing...',
    'please_wait': 'Please wait...',
    'time_estimate': 'Estimated time:',
    'remaining': 'remaining',
    'completed': 'Completed',
    'progress': 'Progress',
    'task_completed': 'Task completed',
    'task_failed': 'Task failed',
    'task_cancelled': 'Task cancelled',
    'start': 'Start',
    'stop': 'Stop',
    'pause': 'Pause',
    'resume': 'Resume',
    'enable': 'Enable',
    'disable': 'Disable',
    'enabled': 'Enabled',
    'disabled': 'Disabled',
    'on': 'On',
    'off': 'Off',
    'auto': 'Auto',
    'manual': 'Manual',
    'more': 'More',
    'less': 'Less',
    'show_all': 'Show All',
    'show_less': 'Show Less',
    'show_more': 'Show More',
    'select_all': 'Select All',
    'deselect_all': 'Deselect All',
    'clear': 'Clear',
    'clear_all': 'Clear All',
    'reset': 'Reset',
    'reset_all': 'Reset All',
    'default': 'Default',
    'custom': 'Custom',
    'advanced': 'Advanced',
    'basic': 'Basic',
    'general': 'General',
    'security': 'Security',
    'privacy': 'Privacy',
    'account': 'Account',
    'data_usage': 'Data Usage',
    'storage': 'Storage',
    'cache': 'Cache',
    'clear_cache': 'Clear Cache',
    'cache_cleared': 'Cache cleared',
    'cache_size': 'Cache Size',
    'notifications_settings': 'Notification Settings',
    'sound': 'Sound',
    'vibrate': 'Vibrate',
    'silent': 'Silent',
    'loud': 'Loud',
    'notification_sound': 'Notification Sound',
    'emergency_alert_sound': 'Emergency Alert Sound',
    'sos_activation_sound': 'SOS Activation Sound',
    'enable_notifications': 'Enable Notifications',
    'disable_notifications': 'Disable Notifications',
    'notification_preferences': 'Notification Preferences',
    'receive_emergency_alerts': 'Receive Emergency Alerts',
    'receive_community_alerts': 'Receive Community Alerts',
    'receive_broadcasts': 'Receive Broadcasts',
    'receive_messages': 'Receive Messages',
    'location_tracking': 'Location Tracking',
    'enable_location_tracking': 'Enable Location Tracking',
    'disable_location_tracking': 'Disable Location Tracking',
    'tracking_interval': 'Tracking Interval',
    'continuous': 'Continuous',
    'every_5_seconds': 'Every 5 seconds',
    'every_10_seconds': 'Every 10 seconds',
    'every_30_seconds': 'Every 30 seconds',
    'every_1_minute': 'Every 1 minute',
    'every_5_minutes': 'Every 5 minutes',
    'every_15_minutes': 'Every 15 minutes',
    'every_30_minutes': 'Every 30 minutes',
    'every_1_hour': 'Every 1 hour',
    'battery_saving': 'Battery Saving',
    'balanced': 'Balanced',
    'high_accuracy': 'High Accuracy',
    'power_saving_mode': 'Power Saving Mode',
    'ultra_power_saving': 'Ultra Power Saving',
    'performance_mode': 'Performance Mode',
    'data_saver': 'Data Saver',
    'offline_data': 'Offline Data',
    'download_offline_maps': 'Download Offline Maps',
    'offline_maps_downloaded': 'Offline maps downloaded',
    'offline_maps_failed': 'Failed to download offline maps',
    'download_size': 'Download Size',
    'available_offline': 'Available Offline',
    'make_available_offline': 'Make Available Offline',
    'remove_from_offline': 'Remove from Offline',
    'offline_resources': 'Offline Resources',
    'no_offline_data': 'No offline data available',
    'walkie_talkie': 'Walkie Talkie',
    'walkie_talkie_monitor': 'Walkie Talkie Monitor',
    'press_to_talk': 'Press to Talk',
    'release_to_send': 'Release to Send',
    'recording': 'Recording...',
    'listening': 'Listening...',
    'speak_now': 'Speak now',
    'audio_message': 'Audio Message',
    'audio_message_sent': 'Audio message sent',
    'audio_message_failed': 'Failed to send audio message',
    'play': 'Play',
    'pause_audio': 'Pause',
    'stop_audio': 'Stop',
    'volume': 'Volume',
    'mute': 'Mute',
    'unmute': 'Unmute',
    'speaker': 'Speaker',
    'earpiece': 'Earpiece',
    'bluetooth': 'Bluetooth',
    'connected_devices': 'Connected Devices',
    'no_devices': 'No devices connected',
    'pair_new_device': 'Pair New Device',
    'device_name': 'Device Name',
    'device_type': 'Device Type',
    'signal_strength': 'Signal Strength',
    'battery_level': 'Battery Level',
    'device_connected': 'Device connected',
    'device_disconnected': 'Device disconnected',
    'connection_lost': 'Connection lost',
    'reconnecting': 'Reconnecting...',
    'scanning': 'Scanning...',
    'scan_complete': 'Scan complete',
    'no_devices_found': 'No devices found',
    'found_devices': 'Devices found',
    'connect': 'Connect',
    'disconnect': 'Disconnect',
    'forget_device': 'Forget Device',
    'pairing': 'Pairing...',
    'paired': 'Paired',
    'pairing_failed': 'Pairing failed',
    'enter_pin': 'Enter PIN',
    'incorrect_pin': 'Incorrect PIN',
    'map': 'Map',
    'satellite': 'Satellite',
    'terrain': 'Terrain',
    'traffic': 'Traffic',
    'heatmap': 'Heatmap',
    'incident_heatmap': 'Incident Heatmap',
    'my_location': 'My Location',
    'zoom_in': 'Zoom In',
    'zoom_out': 'Zoom Out',
    'center_map': 'Center Map',
    'map_layers': 'Map Layers',
    'map_style': 'Map Style',
    'standard': 'Standard',
    'navigation': 'Navigation',
    'hybrid': 'Hybrid',
    'dark': 'Dark',
    'zones': 'Zones',
    'danger_zone': 'Danger Zone',
    'safe_zone': 'Safe Zone',
    'restricted_zone': 'Restricted Zone',
    'zone_details': 'Zone Details',
    'zone_name': 'Zone Name',
    'zone_type': 'Zone Type',
    'zone_boundary': 'Zone Boundary',
    'zone_radius': 'Zone Radius',
    'enter_zone': 'Entering Zone',
    'exit_zone': 'Exiting Zone',
    'approaching_zone': 'Approaching Zone',
    'zone_alert': 'Zone Alert',
    'you_are_here': 'You are here',
    'distance': 'Distance',
    'estimated_time': 'Estimated Time',
    'arrival': 'Arrival',
    'departure': 'Departure',
    'eta': 'ETA',
    'directions': 'Directions',
    'route': 'Route',
    'alternative_route': 'Alternative Route',
    'fastest_route': 'Fastest Route',
    'safest_route': 'Safest Route',
    'shortest_route': 'Shortest Route',
    'route_saved': 'Route saved',
    'route_cleared': 'Route cleared',
    'start_navigation': 'Start Navigation',
    'stop_navigation': 'Stop Navigation',
    'navigation_started': 'Navigation started',
    'navigation_ended': 'Navigation ended',
    'recalculating': 'Recalculating...',
    'turn_left': 'Turn left',
    'turn_right': 'Turn right',
    'go_straight': 'Go straight',
    'arrived': 'Arrived',
    'destination_reached': 'You have reached your destination',
    'off_route': 'You are off route',
    'stay_on_route': 'Stay on the planned route',
    'danger_ahead': 'Danger ahead',
    'caution': 'Caution',
    'proceed_with_caution': 'Proceed with caution',
    'avoid_area': 'Avoid this area',
    'reported_incident_ahead': 'Reported incident ahead',
    'heavy_traffic': 'Heavy traffic',
    'road_closure': 'Road closure',
    'construction': 'Construction',
    'accident': 'Accident',
    'weather_alert': 'Weather Alert',
    'security_checkpoint': 'Security Checkpoint',
    'permission_storage': 'Storage permission is required to save evidence files',
}

# Yoruba translations
YORUBA = {
    'app_name': 'Sectop',
    'ok': 'O Dara',
    'cancel': 'Fagilee',
    'save': 'Fipamọ',
    'delete': 'Pa rẹ',
    'edit': 'Ṣatunkọ',
    'retry': 'Tun gbiyanju',
    'loading': 'Ṣe ikojọpọ...',
    'error': 'Aṣiṣe',
    'success': 'Aṣeyọri',
    'warning': 'Ikilo',
    'info': 'Alaye',
    'confirm': 'Jẹrisi',
    'yes': 'Bẹẹni',
    'no': 'Rara',
    'back': 'Pada',
    'next': 'Atẹle',
    'submit': 'Fi silẹ',
    'search': 'Wa',
    'filter': 'Ajọ',
    'sort': 'To',
    'refresh': 'Tunṣe',
    'settings': 'Eto',
    'profile': 'Profaili',
    'logout': 'Jade',
    'login': 'Wọle',
    'register': 'Forukọsilẹ',
    'home': 'Ile',
    'dashboard': 'Dasibodu',
    'notifications': 'Awọn ifitonileti',
    'messages': 'Awọn ifiranṣẹ',
    'alerts': 'Awọn itaniji',
    'emergency': 'Pajawiri',
    'sos': 'SOS',
    'panic_button': 'Bọtini Ẹru',
    'send_sos': 'Fi Itaniji SOS Rán',
    'cancel_sos': 'Fagilee SOS',
    'sos_sent': 'Itaniji SOS Ti Firanṣẹ!',
    'sos_cancelled': 'Itaniji SOS Ti Fagilee',
    'location': 'Ipo',
    'latitude': 'Laititu',
    'longitude': 'Lonjitu',
    'accuracy': 'Ipele',
    'address': 'Adirẹsi',
    'city': 'Ilu',
    'state': 'Ipinle',
    'country': 'Orilẹ-ede',
    'phone': 'Foonu',
    'email': 'Imeeli',
    'password': 'Ọrọigbaniwọle',
    'confirm_password': 'Jẹrisi Ọrọigbaniwọle',
    'forgot_password': 'Gbagbe Ọrọigbaniwọle?',
    'reset_password': 'Tunto Ọrọigbaniwọle',
    'new_password': 'Ọrọigbaniwọle Tuntun',
    'old_password': 'Ọrọigbaniwọle Atijọ',
    'change_password': 'Yi Ọrọigbaniwọle Pada',
    'name': 'Orukọ',
    'full_name': 'Orukọ Kikun',
    'username': 'Orukọ olumulo',
    'phone_number': 'Nọmba Foonu',
    'date_of_birth': 'Ọjọ Ibi',
    'gender': 'Akọtabi',
    'male': 'Akọ',
    'female': 'Ani',
    'other': 'Miiran',
    'blood_type': 'Iru Ẹjẹ',
    'medical_conditions': 'Awọn Ilera',
    'allergies': 'Awọn Nkan ti ara ko gba',
    'emergency_contact': 'Olubasọrọ Pajawiri',
    'emergency_contacts': 'Awọn Olubasọrọ Pajawiri',
    'add_contact': 'Fi Olubasọrọ Kun',
    'remove_contact': 'Yọ Olubasọrọ',
    'contact_name': 'Orukọ Olubasọrọ',
    'contact_phone': 'Foonu Olubasọrọ',
    'relationship': 'Ibasepo',
    'save_contact': 'Fi Olubasọrọ Pamọ',
    'no_contacts': 'Ko si awọn olubasọrọ pajawiri ti a fi kun sibẹsibẹ',
    'first_aid': 'Iranwo Akọkọ',
    'first_aid_guides': 'Awọn Itọsọna Iranwo Akọkọ',
    'first_aid_tips': 'Awọn Imọran Iranwo Akọkọ',
    'bleeding': 'Ẹjẹ',
    'burns': 'Ijona',
    'fractures': 'Awọn Egugun',
    'choking': 'Gbigbọn',
    'cpr': 'CPR',
    'poisoning': 'Majele',
    'shock': 'Mọnamọna',
    'heart_attack': 'Ikọlu Ọkàn',
    'stroke': 'Ọpọlọ',
    'seizure': 'Ikọlu',
    'snake_bite': 'Buje Ejo',
    'drowning': 'Omi',
    'emergency_numbers': 'Awọn Nọmba Pajawiri',
    'police': 'Ọlọpa',
    'ambulance': 'Ọkọ alaisan',
    'fire_service': 'Ile-iṣẹ Ina',
    'road_safety': 'Aabo Opopona',
    'civil_defence': 'Aabo Ara ilu',
    'coast_guard': 'Ẹṣọ Etikun',
    'nema': 'NEMA',
    'nigerian_police': 'Ọlọpa Naijiria',
    'federal_road_safety': 'Ẹgbẹ Aabo Opopona Apapo',
    'nigerian_ambulance': 'Iṣẹ Ọkọ alaisan Naijiria',
    'nigerian_fire_service': 'Ile-iṣẹ Ina Naijiria',
    'nigerian_civil_defence': 'Ẹgbẹ Aabo ati Olugbeja Ara ilu Naijiria',
    'ncdc': 'NCDC',
    'nigerian_coast_guard': 'Ẹṣọ Etikun Naijiria',
    'nigerian_air_force': 'Ẹgbẹ Ojú-ọrun Naijiria',
    'nigerian_army': 'Ẹgbẹ Ọmọ-ogun Naijiria',
    'nigerian_navy': 'Ọgagun Naijiria',
    'nigerian_red_cross': 'Red Cross Naijiria',
    'nigerian_nema': 'Ile-ibẹẹ Isakoso Pajawiri ti Orilẹ-ede',
    'safety_tips': 'Awọn Imọran Aabo',
    'disaster_preparedness': 'Igbaradi Ajalu',
    'natural_disasters': 'Awọn Ajalu Adayeba',
    'flood': 'Ikun omi',
    'earthquake': 'Ilẹ jigijigi',
    'landslide': 'Ilẹ ṣiṣan',
    'volcanic_eruption': 'Onina',
    'tsunami': 'Tsunami',
    'hurricane': 'Iji lile',
    'tornado': 'Tornado',
    'wildfire': 'Ina igbo',
    'pandemic': 'Ajakale-arun',
    'terrorist_attack': 'Ikọlu Onijagidijagan',
    'active_shooter': 'Onibọn ti nṣiṣe',
    'bomb_threat': 'Irokeke Bombu',
    'kidnapping': 'Jigbe',
    'robbery': 'Jija',
    'domestic_violence': 'Iwa-ipa Ile',
    'sexual_assault': 'Ibalopo',
    'human_trafficking': 'Gbigbe Eniyan',
    'cyberbullying': 'Ipanilaya Ayelujara',
    'online_scam': 'Jija Ayelujara',
    'identity_theft': 'Jija Idanimọ',
    'report_incident': 'Jabo Iṣẹlẹ',
    'report_crime': 'Jabo Ilufin',
    'report_emergency': 'Jabo Pajawiri',
    'tip_off': 'Ifitonileti',
    'anonymous_tip': 'Ifitonileti Ailojukọ',
    'submit_tip': 'Fi Ifitonileti Silẹ',
    'tip_submitted': 'Ifitonileti ti fi silẹ ni aṣeyọri',
    'tip_failed': 'Kuna lati fi ifitonileti silẹ',
    'tip_description': 'Apejuwe Ifitonileti',
