#!/usr/bin/env python3
"""Fix the truncated localization.dart file by appending the missing content."""
import os

script_dir = os.path.dirname(os.path.abspath(__file__))
part1_path = os.path.join(script_dir, 'localization_part1.dart')
output_path = os.path.join(script_dir, 'localization.dart')

# Read the first 611 lines
with open(part1_path, 'r', encoding='utf-8') as f:
    part1 = f.read()

# The complete remaining content to append
part2 = """      'please_enter_phone': 'J\u1ecdw\u1ecd t\u1eb9 n\u1ecdmba foonu r\u1eb9 sii',
      'please_enter_password': 'J\u1ecdw\u1ecd t\u1eb9 \u1ecdr\u1ecdigbaniw\u1ecdle r\u1eb9 sii',
      'password_min_chars': '\u1eccr\u1ecdigbaniw\u1ecdle gb\u1ecdd\u1ecd kere ju 6 l\u1ecd',
      'emergency_tools': 'Aw\u1ecdn irin\u1e63\u1eb9 Pajawiri',
      'broadcasts': 'Aw\u1ecdn igbohunsafefe',
      'radio': 'Redio',
      'walkie_talkie': 'Walkie-Talkie',
      'danger_zones': 'Aw\u1ecdn agbegbe ewu',
      'data_sync': 'Amu\u1e63i\u1e63\u1eb9p\u1ecd Data',
      'syncing': 'N mu\u1e63i\u1e63\u1eb9p\u1ecd...',
      'pending_items': 'aw\u1ecdn nkan isunm\u1ecdt\u1eb9l\u1eb9',
      'peers_connected': 'aw\u1ecdn \u1eb9l\u1eb9gb\u1eb9 ti a sop\u1ecd',
      'sos_sent_silently': 'SOS ti firan\u1e63\u1eb9 ni \u1ecdpal\u1ecdl\u1ecd',
      'sos_failed': 'SOS kuna:',
      'send_sos_alert_title': 'Fi Itaniji SOS R\u00e1n',
      'alert_type': 'Iru Itaniji',
      'select_alert_type': 'Yan iru itaniji',
      'description_optional': 'Apejuwe (Yan)',
      'capture_evidence_optional': 'Ya \u1eb8ri (Yan)',
      'photo': 'F\u1ecdt\u1ecd',
      'video': 'Fidio',
      'audio': 'Ohun',
      'sending_in_seconds': 'N firan\u1e63\u1eb9 ni',
      'tap_to_send_alert': 'T\u1eb9 lati fi itaniji pajawiri ran',
      'ai_analyzing': 'AI n \u1e63e itupal\u1eb9 apejuwe...',
      'distress_detected': '\u26a0 Aw\u1ecdn ifihan ip\u1ecdnju ti a ri!',
      'no_distress_detected': '\u2705 Ko si ip\u1ecdnju ti a ri',
      'priority': 'K\u00ec\u00edn\u00ed',
      'confidence': 'igb\u1eb9k\u1eb9le',
      'alert_broadcast_channels': 'Itaniji ti tan kaakiri nipas\u1eb9 gbogbo aw\u1ecdn ikanni ti o wa',
      'your_location_sent': 'A yoo fi ipo r\u1eb9 ran p\u1eb9lu itaniji yii. A yoo tan itaniji naa kaakiri nipas\u1eb9 gbogbo aw\u1ecdn ikanni ti o wa (aw\u1ecdsanma, Bluetooth mesh, Wi-Fi Direct, LoRa).',
      'failed_to_send_sos': 'Kuna lati fi SOS ran:',
      'permissions_required': 'Aw\u1ecdn igbanilaaye ti a beere',
      'grant_permissions': 'Funni ni Aw\u1ecdn igbanilaaye',
      'location': 'Ipo',
      'bluetooth': 'Bluetooth',
      'storage': 'Ibi ipam\u1ecd',
      'unread_messages': 'Aw\u1ecdn ifiran\u1e63\u1eb9 ti a ko ka',
      'active_alerts': 'Aw\u1ecdn itaniji ti n\u1e63i\u1e63\u1eb9',
      'recent_messages': 'Aw\u1ecdn ifiran\u1e63\u1eb9 to \u1e63\u1eb9\u1e63\u1eb9',
      'no_recent_messages': 'Ko si aw\u1ecdn ifiran\u1e63\u1eb9 to \u1e63\u1eb9\u1e63\u1eb9',
      'open_inbox': '\u1e62ii Apoti ifiran\u1e63\u1eb9',
      'unknown_sender': 'Aim\u1ecd',
      'medical_info': 'Alaye I\u1e63oogun',
      'privacy_security': 'Asiri & Aabo',
      'stealth_mode_sos': 'SOS Ipo Ifura',
      'silent_panic_trigger': 'Ifa \u1ecdpal\u1ecdl\u1ecd nipas\u1eb9 aw\u1ecdn b\u1ecdtini ohun elo',
      'stealth_mode_description': 'Nigbati o ba \u1e63i\u1e63\u1eb9, aw\u1ecdn okunfa ohun elo (Ipele Soke + Isal\u1eb9) yoo fi SOS \u1ecdpal\u1ecdl\u1ecd ran laisi fifi UI han tabi \u1e63i\u1e63e ohun.',
      'close': 'PAADE',
      'save': 'FIPAM\u1ecc',
      'name': 'Oruk\u1ecd',
      'phone': 'Foonu',
      'profile_updated': 'Profaili ti imudojuiw\u1ecdn',
      'medical_info_saved': 'Alaye i\u1e63oogun ti fipam\u1ecd',
      'blood_type': 'Iru \u1eb8j\u1eb9',
      'allergies': 'Aw\u1ecdn aleji',
      'medications': 'Aw\u1ecdn oogun',
      'medical_conditions': 'Aw\u1ecdn ipo i\u1e63oogun',
      'add_contact': 'Fi Olubas\u1ecdr\u1ecd Kun',
      'edit_contact': '\u1e62atunk\u1ecd Olubas\u1ecdr\u1ecd',
      'no_contacts': 'Ko si aw\u1ecdn olubas\u1ecdr\u1ecd pajawiri ti a fi kun sib\u1eb9sib\u1eb9.',
      'read_privacy_policy': 'Ka Eto Imulo Asiri',
      'open_full_map': '\u1e62ii Maapu Kikun',
      'zones_nearby': 'agbegbe(s) nitosi',
      'failed_to_load': 'Kuna lati gba',
      'change_language': 'Yi Ede Pada',
      'english': 'G\u1eb9\u0300\u1eb9\u0301s\u00ec',
      'yoruba': 'Yor\u00f9b\u00e1',
      'igbo': 'Igbo',
      'hausa': 'Hausa',
      'trapped': 'Id\u1eb9k\u00f9n',
      'lost': 'P\u00e0d\u00e1n\u00f9',
      'structural_damage': 'Ibaj\u1eb9 Igbekale',
      'other_emergency': 'Pajawiri Miiran',
      'general_emergency': 'Pajawiri Gbogbogbo',
      'silent_panic': 'Ipaya Ipal\u1ecdl\u1ecd',
      'stealth_sos': 'SOS ipo ifura ti a fa lati iboju SOS',
      'stealth_sos_dashboard': 'SOS ipo ifura ti a fa lati dasibodu',
      'emergency_user': 'Olumulo Pajawiri',
      'offline_mode': 'Ipo Laisi Asop\u1ecd',
      'medical_info_title': 'Alaye I\u1e63oogun',
      'privacy_security_title': 'Asiri & Aabo',
      'edit_profile_title': '\u1e62atunk\u1ecd Profaili',
      'emergency_contacts_title': 'Aw\u1ecdn Olubas\u1ecdr\u1ecd Pajawiri',
      'about_title': 'Nipa',
      'app_version': '1.0.0 (Nigeria Edition)',
      'sectop_description': 'Eto pajawiri pataki kan ti a \u1e63e ap\u1eb9r\u1eb9 fun aw\u1ecdn agbegbe aabo eewu giga.',
      'no_emergency_contacts': 'Ko si aw\u1ecdn olubas\u1ecdr\u1ecd pajawiri ti a fi kun sib\u1eb9sib\u1eb9.',
      'add_contact_title': 'Fi Olubas\u1ecdr\u1ecd Kun',
      'edit_contact_title': '\u1e62atunk\u1ecd Olubas\u1ecdr\u1ecd',
      'contact_name': 'Oruk\u1ecd',
      'contact_phone': 'N\u1ecdmba Foonu',
      'save_contact': 'FIPAM\u1ecc',
      'cancel_btn': 'FAGILE',
      'close_btn': 'PAADE',
      'save_btn': 'FIPAM\u1ecc',
      'cancel_action': 'FAGILE',
      'close_action': 'PAADE',
      'save_action': 'FIPAM\u1ecc',
      'permission_location': 'Ipo',
      'permission_notifications': 'Aw\u1ecdn ifitonileti',
      'permission_bluetooth': 'Bluetooth',
      'permission_storage': 'Ibi ipam\u1ecd',
    },
    'ig': {
      'app_name': 'Sectop',
      'send_sos': 'ZIGA SOS',
      'tap_emergency': 'P\u1ecba maka ihe mberede',
      'quick_actions': 'Omume Ngwa',
      'safe_zones': 'Mpaghara Nche',
      'mesh_network': 'Netw\u1ecdk Mesh',
      'messages': 'Ozi',
      'first_aid': 'Enyemaka Mb\u1ee5',
      'system_status': '\u1eccn\u1ecddu Sistem\u1ee5',
      'cloud_connection': 'Njik\u1ecd Igwe Ojii',
      'connected': 'Ejik\u1ecdr\u1ecd',
      'offline': 'An\u1ecdgh\u1ecb n\u2019\u1ecbntanet\u1ecb',
      'location_tracking': 'Nch\u1ecdta \u1eccn\u1ecddu',
      'active': 'Na-ar\u1ee5 \u1ecdr\u1ee5',
      'inactive': 'Anagh\u1ecb ar\u1ee5 \u1ecdr\u1ee5',
      'sync_status': '\u1eccn\u1ecddu Mmek\u1ecd',
      'sos_active': 'SOS Na-ar\u1ee5 \u1ecdr\u1ee5',
      'cancel': 'Kagbuo',
      'ok': '\u1ecc d\u1ecb mma',
      'error': 'Njehie',
      'loading': 'Na-ebunye...',
      'retry': 'Nwaa \u1ecdz\u1ecd',
      'settings': 'Nt\u1ecdala',
      'profile': 'Profa\u1ecbl\u1ee5',
      'about': 'Gbasara',
      'help': 'Enyemaka',
      'privacy_policy': 'Am\u1ee5ma Nzuzo',
      'logout': 'Wep\u1ee5',
      'dashboard': 'Dashboard',
      'alerts': '\u1ecckwa',
      'emergency_contacts': 'K\u1ecdnkt\u1ecb Mberede',
      'report_incident': 'K\u1ecd\u1ecd Ihe Mere',
      'nearby_dangers': 'Ihe Egwu D\u1ecb Nso',
      'safe_route': '\u1ee4z\u1ecd Nche',
      'language': 'As\u1ee5s\u1ee5',
      'dark_mode': '\u1eccn\u1ecddu \u1eccch\u1ecbch\u1ecbr\u1ecb',
      'notifications': 'Ngosi',
      'permission_required': 'Sectop ch\u1ecdr\u1ecd ikike nd\u1ecb a iji h\u1ee5 na nchekwa g\u1ecb n\u2019\u1ecdn\u1ecddu nd\u1ecb d\u1ecb egwu.',
      'welcome_title': 'Nn\u1ecd\u1ecd na Sectop',
      'welcome_description': 'Ntuziaka a ga-enyere g\u1ecb aka \u1ecbgh\u1ecbta otu esi eji ngwa ah\u1ee5 ar\u1ee5 \u1ecdr\u1ee5 nke \u1ecdma maka nchekwa g\u1ecb na iji nyere nd\u1ecb \u1ecdz\u1ecd aka n\u2019oge ihe mberede.',
      'version': 'Sectop v',
      'about_description': 'Sistem\u1ee5 ihe mberede p\u1ee5r\u1ee5 \u1ecbche emebere maka gburugburu nchekwa d\u1ecb egwu.',
      'push_notifications': 'Ngosi \u1ecckwanye',
      'receive_alerts_messages': 'Nata \u1ecdkwa na ozi',
      'appearance': '\u1eccd\u1ecbd\u1ecb',
      'light_mode': '\u1eccn\u1ecddu \u00cch\u00e8',
      'system_default': 'Sistem\u1ee5 Ndabara',
      'data_usage': 'Ojiji Data',
      'data_saver_mode': '\u1eccn\u1ecddu Nchekwa Data',
      'reduce_data_usage': 'Belata ojiji data maka maap\u1ee5 na mmek\u1ecd',
      'auto_download_maps': 'Budata maap\u1ee5 akpagh\u1ecb aka',
      'preload_map_tiles': 'Budata ta\u1ecbl\u1ecb maap\u1ee5 maka ojiji na-an\u1ecdgh\u1ecb n\u2019\u1ecbntanet\u1ecb',
      'cache_management': 'Njikwa Cache',
      'cache_size': 'Ogo cache',
      'clear_cache': 'Kpochap\u1ee5 Cache',
      'data_management': 'Njikwa Data',
      'delete_local_data': 'Hichap\u1ee5 Data Mpaghara',
      'clear_messages_cache': 'Kpochap\u1ee5 ozi, cache, na mmas\u1ecb (na-edebe aka\u1ee5nt\u1ee5)',
      'account': 'Aka\u1ee5nt\u1ee5',
      'delete_account': 'Hichap\u1ee5 Aka\u1ee5nt\u1ee5',
      'permanently_remove_account': 'Wep\u1ee5 aka\u1ee5nt\u1ee5 na data g\u1ecb kpamkpam',
      'support': 'Nkwado',
      'rate_on_play_store': 'T\u1ee5lee na Play Store',
      'rate_this_app': 'T\u1ee5lee ngwa a ma hap\u1ee5 aro',
      'contact_support': 'Kp\u1ecdt\u1ee5r\u1ee5 Nkwado',
      'how_to_use': 'Otu esi eji',
      'learn_how_to_use': 'M\u1ee5ta otu esi eji ngwa ah\u1ee5',
      'delete_local_data_title': 'Hichap\u1ee5 Data Mpaghara',
      'delete_local_data_message': 'Nke a ga-ehichap\u1ee5 ozi niile echekwara na mpaghara, data cache, na mmas\u1ecb. Aka\u1ee5nt\u1ee5 g\u1ecb (\u1ecdb\u1ee5r\u1ee5 na \u1ecd d\u1ecb) agagh\u1ecb emet\u1ee5ta. Enwegh\u1ecb ike \u1ecbmeghar\u1ecb ihe a.',
      'delete': 'Hichap\u1ee5',
      'language_changed_to': 'As\u1ee5s\u1ee5 gbanwere na',
      'local_data_deleted': 'E mechara hichap\u1ee5 data mpaghara nke \u1ecdma',
      'cache_cleared': 'E kpochap\u1ee5r\u1ee5 cache nke \u1ecdma',
      'could_not_open_play_store': 'Enwegh\u1ecb ike imeghe Play Store',
      'contact': 'Kp\u1ecdt\u1ee5r\u1ee5',
      'home': '\u1ee4l\u1ecd',
      'map': 'Maap\u1ee5',
      'inbox': 'Igbe Ozi',
      'medical_emergency': 'Ihe Mberede Ah\u1ee5ike',
      'fire': '\u1ecck\u1ee5',
      'natural_disaster': '\u1eccdachi Nd\u1ecb Na-emere Onwe',
      'violence_attack': 'Ime Ihe Ike/Mwakpo',
      'kidnapping': '\u1ecct\u1ecdr\u1ecd',
      'other': '\u1eccz\u1ecd',
      'describe_emergency': 'K\u1ecdwaa ihe mberede g\u1ecb...',
      'send_sos_alert': 'Ziga \u1ecckwa SOS',
      'sos_sent': 'Ezigala SOS!',
      'help_is_on_the_way': 'Enyemaka na-ab\u1ecba. N\u1ecdr\u1ecd j\u1ee5\u1ee5 ma n\u1ecdr\u1ecd na nchekwa.',
      'sending': 'Na-eziga...',
      'add_evidence': 'Tinye Ihe akaebe',
      'capture_photo': 'Sere Foto',
      'record_video': 'Dek\u1ecd Vidio',
      'record_audio': 'Dek\u1ecd \u1eccd\u1ecbyo',
      'evidence_captured': 'Eseela Ihe akaebe',
      'sos_will_send_in': 'SOS ga-eziga n\u2019ime',
      'seconds': 'sek\u1ecdn',
      'login': 'Banye',
      'email': 'Email',
      'password': 'Okwuntughe',
      'forgot_password': 'Chefuru Okwuntughe?',
      'dont_have_account': 'Enwegh\u1ecb aka\u1ee5nt\u1ee5?',
      'sign_up': 'Debanye Aha',
      'emergency_bypass': 'Mberede Bypass',
      'use_offline': 'Jiri na-an\u1ecdgh\u1ecb n\u2019\u1ecbntanet\u1ecb',
      'permission_title': 'Ikike \u1eccch\u1ecdr\u1ecd',
      'grant_permissions': 'Nye Ikike',
      'location_permission': '\u1eccn\u1ecddu',
      'location_permission_desc': 'Maka \u1ecdkwa SOS na nch\u1ecdp\u1ee5ta ihe egwu d\u1ecb nso',
      'notification_permission': 'Ngosi',
      'notification_permission_desc': 'Maka \u1ecdkwa mberede na mmelite',
      'bluetooth_permission': 'Bluetooth',
      'bluetooth_permission_desc': 'Maka nkwur\u1ecbta okwu netw\u1ecdk mesh',
      'storage_permission': 'Nchekwa',
      'storage_permission_desc': 'Maka \u1ecbse ihe akaebe na data an\u1ecdgh\u1ecb n\u2019\u1ecbntanet\u1ecb',
      'first_aid_guide': 'Ntuziaka Enyemaka Mb\u1ee5',
      'bleeding': '\u1eccbara \u1eccp\u1ee5p\u1ee5',
      'burns': '\u1ecck\u1ee5 \u1ecdk\u1ee5',
      'fractures': '\u1ecckp\u1ee5kp\u1ee5 Agbajiri',
      'choking': 'Nkpagbu',
      'cpr': 'CPR',
      'shock': 'Ujo',
      'snake_bite': 'Agw\u1ecd Taa',
      'emergency_numbers': 'N\u1ecdmba Mberede',
      'police': 'Nd\u1ecb uwe ojii',
      'ambulance': '\u1ee4gb\u1ecd ihe mberede',
      'fire_service': '\u1eccr\u1ee5 \u1ecck\u1ee5',
      'broadcast': 'Mgbasa ozi',
      'create_broadcast': 'Mep\u1ee5ta Mgbasa ozi',
      'broadcast_message': 'Ozi Mgbasa ozi',
      'send_broadcast': 'Ziga Mgbasa ozi',
      'target_audience': 'Nd\u1ecb na-ege nt\u1ecb Ezubere',
      'everyone': 'Onye \u1ecdb\u1ee5la',
      'responders_only': 'Nd\u1ecb nzaghachi naan\u1ecb',
      'specific_zone': 'Mpaghara Ak\u1ecdwap\u1ee5tara',
      'radio_broadcast': 'Mgbasa ozi Redio',
      'create_radio_broadcast': 'Mep\u1ee5ta Mgbasa ozi Redio',
      'message_content': '\u1eccd\u1ecbnaya Ozi',
      'target_state': 'Steeti Ezubere',
      'target_lga': 'LGA Ezubere',
      'schedule_broadcast': 'Hazie Mgbasa ozi',
      'tip_off': 'Nt\u1ee5nye',
      'submit_tip': 'Nyefee Nt\u1ee5nye',
      'anonymous_tip': 'Nt\u1ee5nye Na-amagh\u1ecb Aha',
      'tip_description': 'K\u1ecdwaa ihe \u1ecb maara...',
      'tip_type': '\u1ee4d\u1ecb Nt\u1ee5nye',
      'suspicious_activity': '\u1eccr\u1ee5 Na-enyo Enyo',
      'planned_attack': 'Mwakpo Ezubere',
      'wanted_person': 'Onye Ach\u1ecdr\u1ecd',
      'drug_trafficking': '\u1ecct\u1ee5 Ah\u1ecba \u1eccgw\u1ee5',
      'other_tip': '\u1eccz\u1ecd',
      'incident_report': 'Ak\u1ee5k\u1ecd Ihe Mere',
      'incident_type': '\u1ee4d\u1ecb Ihe Mere',
      'incident_description': 'K\u1ecdwaa ihe mere...',
      'submit_report': 'Nyefee Ak\u1ee5k\u1ecd',
      'incident_reported': 'Ak\u1ecd\u1ecdla Ihe Mere',
      'thank_you_report': 'Daal\u1ee5 maka \u1ecbk\u1ecd ak\u1ee5k\u1ecd. Agwala nd\u1ecb \u1ecdch\u1ecbch\u1ecb.',
      'search_location': 'Ch\u1ecd\u1ecd \u1ecdn\u1ecddu...',
      'current_location': '\u1eccn\u1ecddu Ugbu a',
      'danger_zones': 'Mpaghara Ihe Egwu',
      'safe_zones_map': 'Mpaghara Nche',
      'satellite_view': 'Nlele Satellait',
      'street_view': 'Nlele Okporo \u1ee4z\u1ecd',
      'no_messages': 'Enwegh\u1ecb ozi ma',
      'type_message': 'P\u1ecbnye ozi...',
      'send': 'Ziga',
      'mark_as_read': 'Kaa d\u1ecb ka nke ag\u1ee5r\u1ee5la',
      'delete_message': 'Hichap\u1ee5 Ozi',
      'mesh_status': '\u1eccn\u1ecddu Mesh',
      'connected_devices': 'Ngwa\u1ecdr\u1ee5 Ejik\u1ecdr\u1ecd',
      'scan_for_devices': 'Nyocha maka Ngwa\u1ecdr\u1ee5',
      'no_devices_found': 'Ah\u1ee5gh\u1ecb ngwa\u1ecdr\u1ee5 \u1ecdb\u1ee5la',
      'mesh_active': 'Mesh Na-ar\u1ee5 \u1ecdr\u1ee5',
      'mesh_inactive': 'Mesh Anagh\u1ecb ar\u1ee5 \u1ecdr\u1ee5',
      'threat_awareness': 'Mara Banyere Ihe Egwu',
      'current_threat_level': '\u1ecckwa Ihe Egwu Ugbu a',
      'nearby_incidents': 'Ihe Mere D\u1ecb Nso',
      'nearby_danger_zones': 'Mpaghara Ihe Egwu D\u1ecb Nso',
      'no_threats': 'Ah\u1ee5gh\u1ecb ihe egwu \u1ecdb\u1ee5la',
      'threat_alerts': '\u1ecckwa Ihe Egwu',
      'mark_all_read': 'Kaa Ha Nile ka ag\u1ee5r\u1ee5la',
      'plan_safe_route': 'Hazie \u1ee4z\u1ecd Nche',
      'origin': 'Mmalite',
      'destination': 'Ebe \u1ecb Na-aga',
      'find_safe_route': 'Ch\u1ecdta \u1ee4z\u1ecd Nche',
      'route_found': 'Ah\u1ee5la \u1ee4z\u1ecd',
      'no_safe_route': 'Enwegh\u1ecb \u1ee5z\u1ecd nche d\u1ecb',
      'edit_profile': 'Dezie Profa\u1ecbl\u1ee5',
      'full_name': 'Aha Njirimara',
      'phone_number': 'N\u1ecdmba Ekwent\u1ecb',
      'save_changes': 'Chekwa Mgbanwe',
      'change_password': 'Gbanwee Okwuntughe',
      'current_password': 'Okwuntughe Ugbu a',
      'new_password': 'Okwuntughe \u1ecch\u1ee5r\u1ee5',
      'confirm_password': 'Kwenye Okwuntughe',
      'walkie_talkie': 'Walkie Talkie',
      'push_to_talk': 'P\u1ecba ikwu okwu',
      'release_to_send': 'Hap\u1ee5 iziga',
      'listening': 'Na-ege nt\u1ecb...',
      'zone_details': 'Nk\u1ecdwa Mpaghara',
      'zone_name': 'Aha Mpaghara',
      'zone_type': '\u1ee4d\u1ecb Mpaghara',
      'restricted_area': 'Mpaghara Amachibidoro',
      'danger_area': 'Mpaghara Ihe Egwu',
      'safe_area': 'Mpaghara Nche',
      'expires_at': 'Na-agw\u1ee5 na',
      'created_by': 'Onye kere',
      'offline_resources': 'Ak\u1ee5r\u1ee5ngwa An\u1ecdgh\u1ecb n\u2019\u1ecbntanet\u1ecb',
      'download_resources': 'Budata Ak\u1ee5r\u1ee5ngwa',
      'downloaded': 'Budatara',
      'not_downloaded': '\u1ecc Budatabegh\u1ecb',
      'help_center': 'Ebe Enyemaka',
      'faq': 'FAQ',
      'report_problem': 'K\u1ecd\u1ecd Nsogbu',
      'terms_of_service': 'Usoro \u1eccr\u1ee5',
      'welcome_back': 'Nn\u1ecd\u1ecd',
      'create_account': 'Mep\u1ee5ta Aka\u1ee5nt\u1ee5',
      'sign_in_to_access': 'Banye iji nweta \u1ecdr\u1ee5 mberede',
      'register_for_assistance': 'Debanye aha maka enyemaka mberede',
      'sign_in': 'Banye',
      'already_have_account': 'Enwere aka\u1ee5nt\u1ee5? Banye',
      'dont_have_account_register': 'Enwegh\u1ecb aka\u1ee5nt\u1ee5? Debanye aha',
      'emergency_access_no_login': 'Ohere Mberede (Enwegh\u1ecb Nbanye)',
      'use_in_disaster': 'Jiri n\u2019\u1ecdn\u1ecddu \u1ecddachi mgbe \u1ecb na-enwegh\u1ecb ike \u1ecbbanye',
      'skip_login_guest': 'W\u1ee5nye Nbanye \u2014 Jiri d\u1ecb ka \u1eccb\u1ecba',
      'browse_without_account': 'Ch\u1ecdghar\u1ecba mgbasa ozi, lee mpaghara nche, ma nweta ozi mberede na-enwegh\u1ecb aka\u1ee5nt\u1ee5',
      'contact_support_email': 'Kp\u1ecdt\u1ee5r\u1ee5 Nkwado:',
      'authentication_failed': 'Nyocha dara',
      'connection_error_offline': 'Njehie njik\u1ecd. Iji \u1ecdn\u1ecddu an\u1ecdgh\u1ecb n\u2019\u1ecbntanet\u1ecb.',
      'failed_emergency_mode': '\u1ecc dara \u1ecbbanye n\u2019\u1ecdn\u1ecddu mberede',
      'please_enter_name': 'Biko tinye aha g\u1ecb',
      'please_enter_email': 'Biko tinye email g\u1ecb',
      'please_enter_valid_email': 'Biko tinye email ziri ezi',
      'please_enter_phone': 'Biko tinye n\u1ecdmba ekwent\u1ecb g\u1ecb',
      'please_enter_password': 'Biko tinye okwuntughe g\u1ecb',
      'password_min_chars': 'Okwuntughe ga-enwe ma \u1ecdd\u1ecbkar\u1ecb ala mkp\u1ee5r\u1ee5edemede 6',
      'emergency_tools': 'Ngwa Mberede',
      'broadcasts': 'Mgbasa ozi',
      'radio': 'Redio',
      'walkie_talkie': 'Walkie-Talkie',
      'danger_zones': 'Mpaghara Ihe Egwu',
      'data_sync': 'Mmek\u1ecd Data',
      'syncing': 'Na-emek\u1ecd...',
      'pending_items': 'ihe nd\u1ecb na-echere',
      'peers_connected': 'nd\u1ecb \u1ecdb\u1ecd ejik\u1ecdr\u1ecd',
      'sos_sent_silently': 'Ezigara SOS na nk\u1ecbt\u1ecb',
      'sos_failed': 'SOS dara:',
      'send_sos_alert_title': 'Ziga \u1ecckwa SOS',
      'alert_type': '\u1ee4d\u1ecb \u1ecckwa',
      'select_alert_type': 'H\u1ecdr\u1ecd \u1ee5d\u1ecb \u1ecdkwa',
      'description_optional': 'Nk\u1ecdwa (Nh\u1ecdr\u1ecd)',
      'capture_evidence_optional': 'Sere Ihe akaebe (Nh\u1ecdr\u1ecd)',
      'photo': 'Foto',
      'video': 'Vidio',
      'audio': '\u1eccd\u1ecbyo',
      'sending_in_seconds': 'Na-eziga n\u2019ime',
      'tap_to_send_alert': 'P\u1ecba iziga \u1ecdkwa mberede',
      'ai_analyzing': 'AI na-enyocha nk\u1ecdwa...',
      'distress_detected': '\u26a0 Ach\u1ecdp\u1ee5tala akara nh\u1ee5ju anya!',
      'no_distress_detected': '\u2705 Ach\u1ecdp\u1ee5tagh\u1ecb nh\u1ee5ju anya',
      'priority': 'Mkpa',
      'confidence': 'nt\u1ee5kwas\u1ecb obi',
      'alert_broadcast_channels': 'A na-agbasa \u1ecdkwa site na \u1ecdwa niile d\u1ecb',
      'your_location_sent': 'A ga-eziga \u1ecdn\u1ecddu g\u1ecb na \u1ecdkwa a. A ga-agbasa \u1ecdkwa a site na \u1ecdwa niile d\u1ecb (igwe ojii, Bluetooth mesh, Wi-Fi Direct, LoRa).',
      'failed_to_send_sos': '\u1ecc d