#!/usr/bin/env python3
"""Generate the complete localization.dart file."""
import os

content = r"""import 'package:flutter/material.dart';

/// Simple localization with Nigerian language support.
/// TODO: Replace with flutter_localizations + ARB files for production:
///   - Add flutter_localizations to pubspec.yaml
///   - Generate .arb files in lib/l10n/
///   - Use AppLocalizations.of(context)!.translate('key')
class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const Map<String, Map<String, String>> _localizedStrings = {
    'en': {
      'app_name': 'Sectop',
      'send_sos': 'SEND SOS',
      'tap_emergency': 'Tap for emergency alert',
      'quick_actions': 'Quick Actions',
      'safe_zones': 'Safe Zones',
      'mesh_network': 'Mesh Network',
      'messages': 'Messages',
      'first_aid': 'First Aid',
      'system_status': 'System Status',
      'cloud_connection': 'Cloud Connection',
      'connected': 'Connected',
      'offline': 'Offline',
      'location_tracking': 'Location Tracking',
      'active': 'Active',
      'inactive': 'Inactive',
      'sync_status': 'Sync Status',
      'sos_active': 'SOS Active',
      'cancel': 'Cancel',
      'ok': 'OK',
      'error': 'Error',
      'loading': 'Loading...',
      'retry': 'Retry',
      'settings': 'Settings',
      'profile': 'Profile',
      'about': 'About',
      'help': 'Help',
      'privacy_policy': 'Privacy Policy',
      'logout': 'Logout',
      'dashboard': 'Dashboard',
      'alerts': 'Alerts',
      'emergency_contacts': 'Emergency Contacts',
      'report_incident': 'Report Incident',
      'nearby_dangers': 'Nearby Dangers',
      'safe_route': 'Safe Route',
      'language': 'Language',
      'dark_mode': 'Dark Mode',
      'notifications': 'Notifications',
      'permission_required': 'Sectop requires the following permissions to ensure your safety in critical scenarios.',
      'welcome_title': 'Welcome to Sectop',
      'welcome_description': 'This guide will help you understand how to use the app effectively for your safety and to assist others during emergencies.',
      'version': 'Sectop v',
      'about_description': 'A specialized emergency system designed for high-risk security environments.',
      'push_notifications': 'Push Notifications',
      'receive_alerts_messages': 'Receive alerts and messages',
      'appearance': 'Appearance',
      'light_mode': 'Light Mode',
      'system_default': 'System Default',
      'data_usage': 'Data Usage',
      'data_saver_mode': 'Data Saver Mode',
      'reduce_data_usage': 'Reduce data usage for maps and sync',
      'auto_download_maps': 'Auto-download Maps',
      'preload_map_tiles': 'Preload map tiles for offline use',
      'cache_management': 'Cache Management',
      'cache_size': 'Cache size',
      'clear_cache': 'Clear Cache',
      'data_management': 'Data Management',
      'delete_local_data': 'Delete Local Data',
      'clear_messages_cache': 'Clear messages, cache, and preferences (keeps account)',
      'account': 'Account',
      'delete_account': 'Delete Account',
      'permanently_remove_account': 'Permanently remove your account and data',
      'support': 'Support',
      'rate_on_play_store': 'Rate on Play Store',
      'rate_this_app': 'Rate this app and leave a suggestion',
      'contact_support': 'Contact Support',
      'how_to_use': 'How to Use',
      'learn_how_to_use': 'Learn how to use the app',
      'delete_local_data_title': 'Delete Local Data',
      'delete_local_data_message': 'This will delete all locally stored messages, cached data, and preferences. Your account (if any) will NOT be affected. This action cannot be undone.',
      'delete': 'Delete',
      'language_changed_to': 'Language changed to',
      'local_data_deleted': 'Local data deleted successfully',
      'cache_cleared': 'Cache cleared successfully',
      'could_not_open_play_store': 'Could not open Play Store',
      'contact': 'Contact',
      'home': 'Home',
      'map': 'Map',
      'inbox': 'Inbox',
      'medical_emergency': 'Medical Emergency',
      'fire': 'Fire',
      'natural_disaster': 'Natural Disaster',
      'violence_attack': 'Violence/Attack',
      'kidnapping': 'Kidnapping',
      'other': 'Other',
      'describe_emergency': 'Describe your emergency...',
      'send_sos_alert': 'Send SOS Alert',
      'sos_sent': 'SOS Sent!',
      'help_is_on_the_way': 'Help is on the way. Stay calm and stay safe.',
      'sending': 'Sending...',
      'add_evidence': 'Add Evidence',
      'capture_photo': 'Capture Photo',
      'record_video': 'Record Video',
      'record_audio': 'Record Audio',
      'evidence_captured': 'Evidence Captured',
      'sos_will_send_in': 'SOS will send in',
      'seconds': 'seconds',
      'login': 'Login',
      'email': 'Email',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'dont_have_account': "Don't have an account?",
      'sign_up': 'Sign Up',
      'emergency_bypass': 'Emergency Bypass',
      'use_offline': 'Use Offline',
      'permission_title': 'Permissions Required',
      'grant_permissions': 'Grant Permissions',
      'location_permission': 'Location',
      'location_permission_desc': 'For SOS alerts and nearby danger detection',
      'notification_permission': 'Notifications',
      'notification_permission_desc': 'For emergency alerts and updates',
      'bluetooth_permission': 'Bluetooth',
      'bluetooth_permission_desc': 'For mesh network communication',
      'storage_permission': 'Storage',
      'storage_permission_desc': 'For evidence capture and offline data',
      'first_aid_guide': 'First Aid Guide',
      'bleeding': 'Bleeding',
      'burns': 'Burns',
      'fractures': 'Fractures',
      'choking': 'Choking',
      'cpr': 'CPR',
      'shock': 'Shock',
      'snake_bite': 'Snake Bite',
      'emergency_numbers': 'Emergency Numbers',
      'police': 'Police',
      'ambulance': 'Ambulance',
      'fire_service': 'Fire Service',
      'broadcast': 'Broadcast',
      'create_broadcast': 'Create Broadcast',
      'broadcast_message': 'Broadcast Message',
      'send_broadcast': 'Send Broadcast',
      'target_audience': 'Target Audience',
      'everyone': 'Everyone',
      'responders_only': 'Responders Only',
      'specific_zone': 'Specific Zone',
      'radio_broadcast': 'Radio Broadcast',
      'create_radio_broadcast': 'Create Radio Broadcast',
      'message_content': 'Message Content',
      'target_state': 'Target State',
      'target_lga': 'Target LGA',
      'schedule_broadcast': 'Schedule Broadcast',
      'tip_off': 'Tip Off',
      'submit_tip': 'Submit Tip',
      'anonymous_tip': 'Anonymous Tip',
      'tip_description': 'Describe what you know...',
      'tip_type': 'Tip Type',
      'suspicious_activity': 'Suspicious Activity',
      'planned_attack': 'Planned Attack',
      'wanted_person': 'Wanted Person',
      'drug_trafficking': 'Drug Trafficking',
      'other_tip': 'Other',
      'incident_report': 'Incident Report',
      'incident_type': 'Incident Type',
      'incident_description': 'Describe the incident...',
      'submit_report': 'Submit Report',
      'incident_reported': 'Incident Reported',
      'thank_you_report': 'Thank you for reporting. Authorities have been notified.',
      'search_location': 'Search location...',
      'current_location': 'Current Location',
      'danger_zones': 'Danger Zones',
      'safe_zones_map': 'Safe Zones',
      'satellite_view': 'Satellite View',
      'street_view': 'Street View',
      'no_messages': 'No messages yet',
      'type_message': 'Type a message...',
      'send': 'Send',
      'mark_as_read': 'Mark as Read',
      'delete_message': 'Delete Message',
      'mesh_status': 'Mesh Status',
      'connected_devices': 'Connected Devices',
      'scan_for_devices': 'Scan for Devices',
      'no_devices_found': 'No devices found',
      'mesh_active': 'Mesh Active',
      'mesh_inactive': 'Mesh Inactive',
      'threat_awareness': 'Threat Awareness',
      'current_threat_level': 'Current Threat Level',
      'nearby_incidents': 'Nearby Incidents',
      'nearby_danger_zones': 'Nearby Danger Zones',
      'no_threats': 'No threats detected',
      'threat_alerts': 'Threat Alerts',
      'mark_all_read': 'Mark All Read',
      'plan_safe_route': 'Plan Safe Route',
      'origin': 'Origin',
      'destination': 'Destination',
      'find_safe_route': 'Find Safe Route',
      'route_found': 'Route Found',
      'no_safe_route': 'No safe route available',
      'edit_profile': 'Edit Profile',
      'full_name': 'Full Name',
      'phone_number': 'Phone Number',
      'save_changes': 'Save Changes',
      'change_password': 'Change Password',
      'current_password': 'Current Password',
      'new_password': 'New Password',
      'confirm_password': 'Confirm Password',
      'walkie_talkie': 'Walkie Talkie',
      'push_to_talk': 'Push to Talk',
      'release_to_send': 'Release to Send',
      'listening': 'Listening...',
      'zone_details': 'Zone Details',
      'zone_name': 'Zone Name',
      'zone_type': 'Zone Type',
      'restricted_area': 'Restricted Area',
      'danger_area': 'Danger Area',
      'safe_area': 'Safe Area',
      'expires_at': 'Expires At',
      'created_by': 'Created By',
      'offline_resources': 'Offline Resources',
      'download_resources': 'Download Resources',
      'downloaded': 'Downloaded',
      'not_downloaded': 'Not Downloaded',
      'help_center': 'Help Center',
      'faq': 'FAQ',
      'report_problem': 'Report a Problem',
      'terms_of_service': 'Terms of Service',
      'welcome_back': 'Welcome Back',
      'create_account': 'Create Account',
      'sign_in_to_access': 'Sign in to access emergency services',
      'register_for_assistance': 'Register for emergency assistance',
      'sign_in': 'Sign In',
      'already_have_account': 'Already have an account? Sign In',
      'dont_have_account_register': "Don't have an account? Register",
      'emergency_access_no_login': 'Emergency Access (No Login)',
      'use_in_disaster': 'Use in disaster situations when you cannot log in',
      'skip_login_guest': 'Skip Login \u2014 Use as Guest',
      'browse_without_account': 'Browse broadcasts, view safe zones, and access emergency info without an account',
      'contact_support_email': 'Contact Support:',
      'authentication_failed': 'Authentication failed',
      'connection_error_offline': 'Connection error. Using offline mode.',
      'failed_emergency_mode': 'Failed to enter emergency mode',
      'please_enter_name': 'Please enter your name',
      'please_enter_email': 'Please enter your email',
      'please_enter_valid_email': 'Please enter a valid email',
      'please_enter_phone': 'Please enter your phone number',
      'please_enter_password': 'Please enter your password',
      'password_min_chars': 'Password must be at least 6 characters',
      'emergency_tools': 'Emergency Tools',
      'broadcasts': 'Broadcasts',
      'radio': 'Radio',
      'walkie_talkie': 'Walkie-Talkie',
      'danger_zones': 'Danger Zones',
      'data_sync': 'Data Sync',
      'syncing': 'Syncing...',
      'pending_items': 'pending items',
      'peers_connected': 'peers connected',
      'sos_sent_silently': 'SOS sent silently',
      'sos_failed': 'SOS failed:',
      'send_sos_alert_title': 'Send SOS Alert',
      'alert_type': 'Alert Type',
      'select_alert_type': 'Select alert type',
      'description_optional': 'Description (Optional)',
      'capture_evidence_optional': 'Capture Evidence (Optional)',
      'photo': 'Photo',
      'video': 'Video',
      'audio': 'Audio',
      'sending_in_seconds': 'Sending in',
      'tap_to_send_alert': 'Tap to send emergency alert',
      'ai_analyzing': 'AI analyzing description...',
      'distress_detected': '\u26a0 Distress signals detected!',
      'no_distress_detected': '\u2705 No distress detected',
      'priority': 'Priority',
      'confidence': 'confidence',
      'alert_broadcast_channels': 'Alert broadcast via all available channels',
      'your_location_sent': 'Your location will be sent with this alert. The alert will be broadcast via all available channels (cloud, Bluetooth mesh, Wi-Fi Direct, LoRa).',
      'failed_to_send_sos': 'Failed to send SOS:',
      'permissions_required': 'Permissions Required',
      'grant_permissions': 'Grant Permissions',
      'location': 'Location',
      'bluetooth': 'Bluetooth',
      'storage': 'Storage',
      'unread_messages': 'Unread Messages',
      'active_alerts': 'Active Alerts',
      'recent_messages': 'Recent Messages',
      'no_recent_messages': 'No recent messages',
      'open_inbox': 'Open Inbox',
      'unknown_sender': 'Unknown',
      'medical_info': 'Medical Info',
      'privacy_security': 'Privacy & Security',
      'stealth_mode_sos': 'Stealth Mode SOS',
      'silent_panic_trigger': 'Silent panic trigger via hardware buttons',
      'stealth_mode_description': 'When enabled, hardware triggers (Volume Up + Down) will send a silent SOS without showing any UI or making sound.',
      'close': 'CLOSE',
      'save': 'SAVE',
      'name': 'Name',
      'phone': 'Phone',
      'profile_updated': 'Profile updated',
      'medical_info_saved': 'Medical info saved',
      'blood_type': 'Blood Type',
      'allergies': 'Allergies',
      'medications': 'Medications',
      'medical_conditions': 'Medical Conditions',
      'add_contact': 'Add Contact',
      'edit_contact': 'Edit Contact',
      'no_contacts': 'No emergency contacts added yet.',
      'read_privacy_policy': 'Read Privacy Policy',
      'open_full_map': 'Open Full Map',
      'zones_nearby': 'zone(s) nearby',
      'failed_to_load': 'Failed to load',
      'change_language': 'Change Language',
      'english': 'English',
      'yoruba': 'Yor\u00f9b\u00e1',
      'igbo': 'Igbo',
      'hausa': 'Hausa',
      'trapped': 'Trapped',
      'lost': 'Lost',
      'structural_damage': 'Structural Damage',
      'other_emergency': 'Other Emergency',
      'general_emergency': 'General Emergency',
      'silent_panic': 'Silent Panic',
      'stealth_sos': 'Stealth mode SOS triggered from SOS screen',
      'stealth_sos_dashboard': 'Stealth mode SOS triggered from dashboard',
      'emergency_user': 'Emergency User',
      'offline_mode': 'Offline Mode',
      'medical_info_title': 'Medical Info',
      'privacy_security_title': 'Privacy & Security',
      'edit_profile_title': 'Edit Profile',
      'emergency_contacts_title': 'Emergency Contacts',
      'about_title': 'About',
      'app_version': '1.0.0 (Nigeria Edition)',
      'sectop_description': 'A specialized emergency system designed for high-risk security environments.',
      'no_emergency_contacts': 'No emergency contacts added yet.',
      'add_contact_title': 'Add Contact',
      'edit_contact_title': 'Edit Contact',
      'contact_name': 'Name',
      'contact_phone': 'Phone Number',
      'save_contact': 'SAVE',
      'cancel_btn': 'CANCEL',
      'close_btn': 'CLOSE',
      'save_btn': 'SAVE',
      'cancel_action': 'CANCEL',
      'close_action': 'CLOSE',
      'save_action': 'SAVE',
      'permission_location': 'Location',
      'permission_notifications': 'Notifications',
      'permission_bluetooth': 'Bluetooth',
      'permission_storage': 'Storage',
    },
    'yo': {
      'app_name': 'Sectop',
      'send_sos': 'RAN SOS',
      'tap_emergency': 'T\u1eb9 fun itaniji pajawiri',
      'quick_actions': 'Aw\u1ecdn i\u1e63e iyara',
      'safe_zones': 'Aw\u1ecdn agbegbe ailewu',
      'mesh_network': 'N\u1eb9tiw\u1ecd\u1ecdi Mesh',
      'messages': 'Aw\u1ecdn ifiran\u1e63\u1eb9',
      'first_aid': 'Iranwo ak\u1ecdk\u1ecd',
      'system_status': 'Ipo eto',
      'cloud_connection': 'Asop\u1ecdm\u1ecdra aw\u1ecdsanma',
      'connected': 'Asop\u1ecd',
      'offline': 'Aisi asop\u1ecd',
      'location_tracking': 'Ipil\u1eb9 ipo',
      'active': '\u1e62i\u1e63\u1eb9',
      'inactive': 'Ai\u1e63i\u1e63\u1eb9',
      'sync_status': 'Ipo amu\u1e63i\u1e63\u1eb9p\u1ecd',
      'sos_active': 'SOS \u1e63i\u1e63\u1eb9',
      'cancel': 'Fagilee',
      'ok': 'O dara',
      'error': 'A\u1e63i\u1e63e',
      'loading': 'N gba lati...',
      'retry': 'Tun gbiyanju',
      'settings': 'Aw\u1ecdn eto',
      'profile': 'Profaili',
      'about': 'Nipa',
      'help': 'Iranw\u1ecd',
      'privacy_policy': 'Eto imulo asiri',
      'logout': 'Ijade',
      'dashboard': 'Dasibodu',
      'alerts': 'Aw\u1ecdn itaniji',
      'emergency_contacts': 'Aw\u1ecdn olubas\u1ecdr\u1ecd pajawiri',
      'report_incident': 'Jab\u1ecd i\u1e63\u1eb9l\u1eb9',
      'nearby_dangers': 'Aw\u1ecdn ewu nitosi',
      'safe_route': '\u1eccna ailewu',
      'language': 'Ede',
      'dark_mode': 'Ipo dudu',
      'notifications': 'Aw\u1ecdn ifitonileti',
      'permission_required': 'Sectop nilo aw\u1ecdn igbanilaaye w\u1ecdnyi lati rii daju aabo r\u1eb9 ni aw\u1ecdn oju i\u1e63\u1eb9l\u1eb9 to \u1e63e pataki.',
      'welcome_title': 'Kaabo si Sectop',
      'welcome_description': 'It\u1ecds\u1ecdn\u1ecd yii yoo ran \u1ecd l\u1ecdw\u1ecd lati loye bi o \u1e63e le lo ohun elo naa daradara fun aabo r\u1eb9 ati lati ran aw\u1ecdn \u1eb9lomiran l\u1ecdw\u1ecd lakoko aw\u1ecdn pajawiri.',
      'version': 'Sectop v',
      'about_description': 'Eto pajawiri pataki kan ti a \u1e63e ap\u1eb9r\u1eb9 fun aw\u1ecdn agbegbe aabo eewu giga.',
      'push_notifications': 'Aw\u1ecdn ifitonileti Titari',
      'receive_alerts_messages': 'Gba aw\u1ecdn itaniji ati aw\u1ecdn ifiran\u1e63\u1eb9',
      'appearance': 'Ifarahan',
      'light_mode': 'Ipo Im\u1ecdl\u1eb9',
      'system_default': 'Aiyipada Eto',
      'data_usage': 'Lilo Data',
      'data_saver_mode': 'Ipo Ifipam\u1ecd Data',
      'reduce_data_usage': 'Dinku lilo data fun aw\u1ecdn maapu ati amu\u1e63i\u1e63\u1eb9p\u1ecd',
      'auto_download_maps': 'Gba aw\u1ecdn maapu laif\u1ecdw\u1ecdyi',
      'preload_map_tiles': 'T\u1eb9 aw\u1ecdn maapu t\u1eb9l\u1eb9 fun lilo offline',
      'cache_management': 'I\u1e63akoso Ka\u1e63e',
      'cache_size': 'Iw\u1ecdn ka\u1e63e',
      'clear_cache': 'Nu Ka\u1e63e',
      'data_management': 'I\u1e63akoso Data',
      'delete_local_data': 'Pa Data Agbegbe r\u1eb9',
      'clear_messages_cache': 'Nu aw\u1ecdn ifiran\u1e63\u1eb9, ka\u1e63e, ati aw\u1ecdn ayanf\u1eb9 (o nt\u1ecdu ak\u1ecd\u1ecdl\u1eb9)',
      'account': 'Ak\u1ecd\u1ecdl\u1eb9',
      'delete_account': 'Pa Ak\u1ecd\u1ecdl\u1eb9 r\u1eb9',
      'permanently_remove_account': 'Y\u1ecd ak\u1ecd\u1ecdl\u1eb9 ati data r\u1eb9 kuro patapata',
      'support': 'Atil\u1eb9yin',
      'rate_on_play_store': '\u1e62e idiyele lori Play Store',
      'rate_this_app': '\u1e62e idiyele app yii ki o fi im\u1ecdr\u1ecdn sil\u1eb9',
      'contact_support': 'Kan si Atil\u1eb9yin',
      'how_to_use': 'Bii o \u1e63e le Lo',
      'learn_how_to_use': 'K\u1ecd \u1eb9k\u1ecd bi o \u1e63e le lo app naa',
      'delete_local_data_title': 'Pa Data Agbegbe r\u1eb9',
      'delete_local_data_message': 'Eyi yoo pa gbogbo aw\u1ecdn ifiran\u1e63\u1eb9 ti o fipam\u1ecd ni agbegbe, data ka\u1e63e, ati aw\u1ecdn ayanf\u1eb9 r\u1eb9. Ak\u1ecd\u1ecdl\u1eb9 r\u1eb9 (ti o ba wa) kii yoo kan. A ko le \u1e63e atun\u1e63e i\u1e63e yii.',
      'delete': 'Paar\u1eb9',
      'language_changed_to': 'Ede ti yipada si',
      'local_data_deleted': 'Data agbegre ti paar\u1eb9 ni a\u1e63ey\u1ecdnri',
      'cache_cleared': 'Ka\u1e63e ti nu kuro ni a\u1e63ey\u1ecdnri',
      'could_not_open_play_store': 'Ko le \u1e63ii Play Store',
      'contact': 'Kan si',
      'home': 'Ile',
      'map': 'Maapu',
      'inbox': 'Apoti ifiran\u1e63\u1eb9',
      'medical_emergency': 'Pajawiri I\u1e63oogun',
      'fire': 'Ina',
      'natural_disaster': 'Ajalu Adayeba',
      'violence_attack': 'Iwa-ipa/Ik\u1ecdl\u1ee5',
      'kidnapping': 'Jigbe',
      'other': 'Miiran',
      'describe_emergency': '\u1e62e apejuwe ipo pajawiri r\u1eb9...',
      'send_sos_alert': 'Fi Itaniji SOS R\u00e1n',
      'sos_sent': 'SOS Ti Firan\u1e63\u1eb9!',
      'help_is_on_the_way': 'Iranw\u1ecd n b\u1ecd. J\u1eb9\u0301 k\u00ed o f\u1ecdk\u00e0n bal\u1eb9 ki o si wa lailewu.',
      'sending': 'N firan\u1e63\u1eb9...',
      'add_evidence': 'Fi \u1eb8ri Kun',
      'capture_photo': 'Ya F\u1ecdt\u1ecd',
      'record_video': 'Gba Fidio',
      'record_audio': 'Gba Ohun',
      'evidence_captured': '\u1eb8ri Ti Ya',
      'sos_will_send_in': 'SOS yoo firan\u1e63\u1eb9 ni',
      'seconds': 'aaya',
      'login': 'W\u1ecdle',
      'email': 'Imeeli',
      'password': '\u1eccr\u1ecdigbaniw\u1ecdle',
      'forgot_password': 'Gbagbe \u1eccr\u1ecdigbaniw\u1ecdle?',
      'dont_have_account': 'Ko ni ak\u1ecd\u1ecdl\u1eb9?',
      'sign_up': 'Foruk\u1ecdsil\u1eb9',
      'emergency_bypass': 'Fori Pajawiri',
      'use_offline': 'Lo Laisi Asop\u1ecd',
      'permission_title': 'Aw\u1ecdn igbanilaaye ti a beere',
      'grant_permissions': 'Funni ni Aw\u1ecdn igbanilaaye',
      'location_permission': 'Ipo',
      'location_permission_desc': 'Fun aw\u1ecdn itaniji SOS ati wiwa ewu nitosi',
      'notification_permission': 'Aw\u1ecdn ifitonileti',
      'notification_permission_desc': 'Fun aw\u1ecdn itaniji pajawiri ati aw\u1ecdn imudojuiw\u1ecdn',
      'bluetooth_permission': 'Bluetooth',
      'bluetooth_permission_desc': 'Fun ibara\u1eb9nis\u1ecdr\u1ecd n\u1eb9tiw\u1ecd\u1ecdi mesh',
      'storage_permission': 'Ibi ipam\u1ecd',
      'storage_permission_desc': 'Fun gbigba \u1eb9ri ati data offline',
      'first_aid_guide': 'It\u1ecds\u1ecdn\u1ecd Iranwo Ak\u1ecdk\u1ecd',
      'bleeding': '\u1eb8j\u1eb9',
      'burns': 'In\u00e1',
      'fractures': 'Egugun dida',
      'choking': 'Gbigb\u1ecdn',
      'cpr': 'CPR',
      'shock': 'M\u1ecdanam\u1ecdna',
      'snake_bite': 'Buje Ejo',
      'emergency_numbers': 'Aw\u1ecdn n\u1ecdmba pajawiri',
      'police': '\u1eccl\u1ecdpa',
      'ambulance': '\u1ecck\u1ecd alaisan',
      'fire_service': 'Eto ina',
      'broadcast': 'Igbohunsafefe',
      'create_broadcast': '\u1e62\u1eb9da Igbohunsafefe',
      'broadcast_message': 'Ifiran\u1e63\u1eb9 Igbohunsafefe',
      'send_broadcast': 'Fi Igbohunsafefe R\u00e1n',
      'target_audience': 'Aw\u1ecdn olugbo ibi-af\u1eb9de',
      'everyone': 'Gbogbo eniyan',
      'responders_only': 'Aw\u1ecdn oludahun nikan',
      'specific_zone': 'Agbegbe kan pato',
      'radio_broadcast': 'Igbohunsafefe Redio',
      'create_radio_broadcast': '\u1e62\u1eb9da Igbohunsafefe Redio',
      'message_content': 'Akoonu Ifiran\u1e63\u1eb9',
      'target_state': 'Ipinle ibi-af\u1eb9de',
      'target_lga': 'LGA ibi-af\u1eb9de',
      'schedule_broadcast': '\u1e62eto Igbohunsafefe',
      'tip_off': 'Ifitonileti',
      'submit_tip': 'Fi Ifitonileti R\u00e1n',
      'anonymous_tip': 'Ifitonileti Ail\u1ecdr\u1ee5k\u1ecd',
      'tip_description': '\u1e62e apejuwe ohun ti o m\u1ecd...',
      'tip_type': 'Iru Ifitonileti',
      'suspicious_activity': 'I\u1e63\u1eb9 Ifura',
      'planned_attack': 'Ik\u1ecdl\u1ee5 Ti a Gbero',
      'wanted_person': 'Eniyan Ti a F\u1eb9',
      'drug_trafficking': 'Gbigbe O\u00f2g\u00f9n',
      'other_tip': 'Miiran',
      'incident_report': 'Iroyin I\u1e63\u1eb9l\u1eb9',
      'incident_type': 'Iru I\u1e63\u1eb9l\u1eb9',
      'incident_description': '\u1e62e apejuwe i\u1e63\u1eb9l\u1eb9 naa...',
      'submit_report': 'Fi Iroyin R\u00e1n',
      'incident_reported': 'I\u1e63\u1eb9l\u1eb9 Ti Royin',
      'thank_you_report': 'O \u1e63eun fun ijab\u1ecd r\u1eb9. A ti fi to aw\u1ecdn ala\u1e63\u1eb9 leti.',
      'search_location': '\u1e62e agbekal\u1eb9 ipo...',
      'current_location': 'Ipo L\u1ecdw\u1ecdl\u1ecdw\u1ecd',
      'danger_zones': 'Aw\u1ecdn agbegbe ewu',
      'safe_zones_map': 'Aw\u1ecdn agbegbe ailewu',
      'satellite_view': 'Wiwo Sat\u1eb9la\u1ecbti',
      'street_view': 'Wiwo Opopona',
      'no_messages': 'Ko si aw\u1ecdn ifiran\u1e63\u1eb9 sib\u1eb9sib\u1eb9',
      'type_message': 'T\u1eb9 ifiran\u1e63\u1eb9 sii...',
      'send': 'Fi R\u00e1n',
      'mark_as_read': 'Samisi bi a ti ka',
      'delete_message': 'Pa Ifiran\u1e63\u1eb9 r\u1eb9',
      'mesh_status': 'Ipo Mesh',
      'connected_devices': 'Aw\u1ecdn \u1eb9r\u1ecd ti a ti sop\u1ecd',
      'scan_for_devices': '\u1e62e ay\u1eb9wo fun aw\u1ecdn \u1eb9r\u1ecd',
      'no_devices_found': 'Ko si aw\u1ecdn \u1eb9r\u1ecd ti a ri',
      'mesh_active': 'Mesh \u1e62i\u1e63\u1eb9',
      'mesh_inactive': 'Mesh Ai\u1e63i\u1e63\u1eb9',
      'threat_awareness': 'Akiyesi Irokeke',
      'current_threat_level': 'Ipele Irokeke L\u1ecdw\u1ecdl\u1ecdw\u1ecd',
      'nearby_incidents': 'Aw\u1ecdn i\u1e63\u1eb9l\u1eb9 nitosi',
      'nearby_danger_zones': 'Aw\u1ecdn agbegbe ewu nitosi',
      'no_threats': 'Ko si aw\u1ecdn irokeke ti a ri',
      'threat_alerts': 'Aw\u1ecdn itaniji irokeke',
      'mark_all_read': 'Samisi Gbogbo bi a ti ka',
      'plan_safe_route': 'Gbero \u1eccna Ailewu',
      'origin': 'Ibi ti a ti b\u1eb9r\u1eb9',
      'destination': 'Ibi ti a nlo',
      'find_safe_route': 'Wa \u1eccna Ailewu',
      'route_found': '\u1eccna Ti Ri',
      'no_safe_route': 'Ko si \u1ecdna ailewu to wa',
      'edit_profile': '\u1e62atunk\u1ecd Profaili',
      'full_name': 'Oruk\u1ecd Kikun',
      'phone_number': 'N\u1ecdmba Foonu',
      'save_changes': 'Fi Aw\u1ecdn Ayipada Pam\u1ecd',
      'change_password': 'Yi \u1eccr\u1ecdigbaniw\u1ecdle Pada',
      'current_password': '\u1eccr\u1ecdigbaniw\u1ecdle L\u1ecdw\u1ecdl\u1ecdw\u1ecd',
      'new_password': '\u1eccr\u1ecdigbaniw\u1ecdle Tuntun',
      'confirm_password': 'J\u1