import 'package:flutter/material.dart';

/// Simple localization with Nigerian language support.
/// TODO: Replace with flutter_localizations + ARB files for production:
///   - Add flutter_localizations to pubspec.yaml
///   - Generate .arb files in lib/l10n/
///   - Use AppLocalizations.of(context)!.translate('key')
class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const Map<String, Map<String, String>> _localizedStrings = {
    'en': {
      'app_name': 'Sectop',
      'send_sos': 'SEND SOS',
      'tap_emergency': 'Tap for emergency alert',
      'quick_actions': 'Quick Actions',
      'safe_zones': 'Safe Zones',
      'mesh_network': 'Mesh Network',
      'messages': 'Messages',
      'first_aid': 'First Aid',
      'system_status': 'System Status',
      'cloud_connection': 'Cloud Connection',
      'connected': 'Connected',
      'offline': 'Offline',
      'location_tracking': 'Location Tracking',
      'active': 'Active',
      'inactive': 'Inactive',
      'sync_status': 'Sync Status',
      'sos_active': 'SOS Active',
      'cancel': 'Cancel',
      'ok': 'OK',
      'error': 'Error',
      'loading': 'Loading...',
      'retry': 'Retry',
      'settings': 'Settings',
      'profile': 'Profile',
      'about': 'About',
      'help': 'Help',
      'privacy_policy': 'Privacy Policy',
      'logout': 'Logout',
      'dashboard': 'Dashboard',
      'alerts': 'Alerts',
      'emergency_contacts': 'Emergency Contacts',
      'report_incident': 'Report Incident',
      'nearby_dangers': 'Nearby Dangers',
      'safe_route': 'Safe Route',
      'language': 'Language',
      'dark_mode': 'Dark Mode',
      'notifications': 'Notifications',
      'permission_required': 'Sectop requires the following permissions to ensure your safety in critical scenarios.',
      'welcome_title': 'Welcome to Sectop',
      'welcome_description': 'This guide will help you understand how to use the app effectively for your safety and to assist others during emergencies.',
      'version': 'Sectop v',
      'about_description': 'A specialized emergency system designed for high-risk security environments.',
      // Settings screen
      'push_notifications': 'Push Notifications',
      'receive_alerts_messages': 'Receive alerts and messages',
      'appearance': 'Appearance',
      'light_mode': 'Light Mode',
      'system_default': 'System Default',
      'data_usage': 'Data Usage',
      'data_saver_mode': 'Data Saver Mode',
      'reduce_data_usage': 'Reduce data usage for maps and sync',
      'auto_download_maps': 'Auto-download Maps',
      'preload_map_tiles': 'Preload map tiles for offline use',
      'cache_management': 'Cache Management',
      'cache_size': 'Cache size',
      'clear_cache': 'Clear Cache',
      'data_management': 'Data Management',
      'delete_local_data': 'Delete Local Data',
      'clear_messages_cache': 'Clear messages, cache, and preferences (keeps account)',
      'account': 'Account',
      'delete_account': 'Delete Account',
      'permanently_remove_account': 'Permanently remove your account and data',
      'support': 'Support',
      'rate_on_play_store': 'Rate on Play Store',
      'rate_this_app': 'Rate this app and leave a suggestion',
      'contact_support': 'Contact Support',
      'how_to_use': 'How to Use',
      'learn_how_to_use': 'Learn how to use the app',
      'delete_local_data_title': 'Delete Local Data',
      'delete_local_data_message': 'This will delete all locally stored messages, cached data, and preferences. Your account (if any) will NOT be affected. This action cannot be undone.',
      'delete': 'Delete',
      'language_changed_to': 'Language changed to',
      'local_data_deleted': 'Local data deleted successfully',
      'cache_cleared': 'Cache cleared successfully',
      'could_not_open_play_store': 'Could not open Play Store',
      'contact': 'Contact',
      // Dashboard
      'home': 'Home',
      'map': 'Map',
      'inbox': 'Inbox',
      // SOS screen
      'medical_emergency': 'Medical Emergency',
      'fire': 'Fire',
      'natural_disaster': 'Natural Disaster',
      'violence_attack': 'Violence/Attack',
      'kidnapping': 'Kidnapping',
      'other': 'Other',
      'describe_emergency': 'Describe your emergency...',
      'send_sos_alert': 'Send SOS Alert',
      'sos_sent': 'SOS Sent!',
      'help_is_on_the_way': 'Help is on the way. Stay calm and stay safe.',
      'sending': 'Sending...',
      'add_evidence': 'Add Evidence',
      'capture_photo': 'Capture Photo',
      'record_video': 'Record Video',
      'record_audio': 'Record Audio',
      'evidence_captured': 'Evidence Captured',
      'sos_will_send_in': 'SOS will send in',
      'seconds': 'seconds',
      // Login screen
      'login': 'Login',
      'email': 'Email',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'dont_have_account': "Don't have an account?",
      'sign_up': 'Sign Up',
      'emergency_bypass': 'Emergency Bypass',
      'use_offline': 'Use Offline',
      // Permission screen
      'permission_title': 'Permissions Required',
      'grant_permissions': 'Grant Permissions',
      'location_permission': 'Location',
      'location_permission_desc': 'For SOS alerts and nearby danger detection',
      'notification_permission': 'Notifications',
      'notification_permission_desc': 'For emergency alerts and updates',
      'bluetooth_permission': 'Bluetooth',
      'bluetooth_permission_desc': 'For mesh network communication',
      'storage_permission': 'Storage',
      'storage_permission_desc': 'For evidence capture and offline data',
      // First Aid
      'first_aid_guide': 'First Aid Guide',
      'bleeding': 'Bleeding',
      'burns': 'Burns',
      'fractures': 'Fractures',
      'choking': 'Choking',
      'cpr': 'CPR',
      'shock': 'Shock',
      'snake_bite': 'Snake Bite',
      'emergency_numbers': 'Emergency Numbers',
      'police': 'Police',
      'ambulance': 'Ambulance',
      'fire_service': 'Fire Service',
      // Broadcast
      'broadcast': 'Broadcast',
      'create_broadcast': 'Create Broadcast',
      'broadcast_message': 'Broadcast Message',
      'send_broadcast': 'Send Broadcast',
      'target_audience': 'Target Audience',
      'everyone': 'Everyone',
      'responders_only': 'Responders Only',
      'specific_zone': 'Specific Zone',
      // Radio Broadcast
      'radio_broadcast': 'Radio Broadcast',
      'create_radio_broadcast': 'Create Radio Broadcast',
      'message_content': 'Message Content',
      'target_state': 'Target State',
      'target_lga': 'Target LGA',
      'schedule_broadcast': 'Schedule Broadcast',
      // Tip Off
      'tip_off': 'Tip Off',
      'submit_tip': 'Submit Tip',
      'anonymous_tip': 'Anonymous Tip',
      'tip_description': 'Describe what you know...',
      'tip_type': 'Tip Type',
      'suspicious_activity': 'Suspicious Activity',
      'planned_attack': 'Planned Attack',
      'wanted_person': 'Wanted Person',
      'drug_trafficking': 'Drug Trafficking',
      'other_tip': 'Other',
      // Incident Report
      'incident_report': 'Incident Report',
      'incident_type': 'Incident Type',
      'incident_description': 'Describe the incident...',
      'submit_report': 'Submit Report',
      'incident_reported': 'Incident Reported',
      'thank_you_report': 'Thank you for reporting. Authorities have been notified.',
      // Map
      'search_location': 'Search location...',
      'current_location': 'Current Location',
      'danger_zones': 'Danger Zones',
      'safe_zones_map': 'Safe Zones',
      'satellite_view': 'Satellite View',
      'street_view': 'Street View',
      // Inbox / Messages
      'no_messages': 'No messages yet',
      'type_message': 'Type a message...',
      'send': 'Send',
      'mark_as_read': 'Mark as Read',
      'delete_message': 'Delete Message',
      // Mesh Network
      'mesh_status': 'Mesh Status',
      'connected_devices': 'Connected Devices',
      'scan_for_devices': 'Scan for Devices',
      'no_devices_found': 'No devices found',
      'mesh_active': 'Mesh Active',
      'mesh_inactive': 'Mesh Inactive',
      // Threat Awareness
      'threat_awareness': 'Threat Awareness',
      'current_threat_level': 'Current Threat Level',
      'nearby_incidents': 'Nearby Incidents',
      'nearby_danger_zones': 'Nearby Danger Zones',
      'no_threats': 'No threats detected',
      'threat_alerts': 'Threat Alerts',
      'mark_all_read': 'Mark All Read',
      // Safe Route
      'plan_safe_route': 'Plan Safe Route',
      'origin': 'Origin',
      'destination': 'Destination',
      'find_safe_route': 'Find Safe Route',
      'route_found': 'Route Found',
      'no_safe_route': 'No safe route available',
      // Profile
      'edit_profile': 'Edit Profile',
      'full_name': 'Full Name',
      'phone_number': 'Phone Number',
      'save_changes': 'Save Changes',
      'change_password': 'Change Password',
      'current_password': 'Current Password',
      'new_password': 'New Password',
      'confirm_password': 'Confirm Password',
      // Walkie Talkie
      'walkie_talkie': 'Walkie Talkie',
      'push_to_talk': 'Push to Talk',
      'release_to_send': 'Release to Send',
      'listening': 'Listening...',
      // Zone Details
      'zone_details': 'Zone Details',
      'zone_name': 'Zone Name',
      'zone_type': 'Zone Type',
      'restricted_area': 'Restricted Area',
      'danger_area': 'Danger Area',
      'safe_area': 'Safe Area',
      'expires_at': 'Expires At',
      'created_by': 'Created By',
      // Offline Resources
      'offline_resources': 'Offline Resources',
      'download_resources': 'Download Resources',
      'downloaded': 'Downloaded',
      'not_downloaded': 'Not Downloaded',
      // Help
      'help_center': 'Help Center',
      'faq': 'FAQ',
      'report_problem': 'Report a Problem',
      'terms_of_service': 'Terms of Service',
      // Additional keys needed by screens
      'welcome_back': 'Welcome Back',
      'create_account': 'Create Account',
      'sign_in_to_access': 'Sign in to access emergency services',
      'register_for_assistance': 'Register for emergency assistance',
      'sign_in': 'Sign In',
      'already_have_account': 'Already have an account? Sign In',
      'dont_have_account_register': "Don't have an account? Register",
      'emergency_access_no_login': 'Emergency Access (No Login)',
      'use_in_disaster': 'Use in disaster situations when you cannot log in',
      'skip_login_guest': 'Skip Login â€” Use as Guest',
      'browse_without_account': 'Browse broadcasts, view safe zones, and access emergency info without an account',
      'contact_support_email': 'Contact Support:',
      'authentication_failed': 'Authentication failed',
      'connection_error_offline': 'Connection error. Using offline mode.',
      'failed_emergency_mode': 'Failed to enter emergency mode',
      'please_enter_name': 'Please enter your name',
      'please_enter_email': 'Please enter your email',
      'please_enter_valid_email': 'Please enter a valid email',
      'please_enter_phone': 'Please enter your phone number',
      'please_enter_password': 'Please enter your password',
      'password_min_chars': 'Password must be at least 6 characters',
      'emergency_tools': 'Emergency Tools',
      'broadcasts': 'Broadcasts',
      'radio': 'Radio',
      'data_sync': 'Data Sync',
      'syncing': 'Syncing...',
      'pending_items': 'pending items',
      'peers_connected': 'peers connected',
      'sos_sent_silently': 'SOS sent silently',
      'sos_failed': 'SOS failed:',
      'send_sos_alert_title': 'Send SOS Alert',
      'alert_type': 'Alert Type',
      'select_alert_type': 'Select alert type',
      'description_optional': 'Description (Optional)',
      'capture_evidence_optional': 'Capture Evidence (Optional)',
      'photo': 'Photo',
      'video': 'Video',
      'audio': 'Audio',
      'sending_in_seconds': 'Sending in',
      'tap_to_send_alert': 'Tap to send emergency alert',
      'ai_analyzing': 'AI analyzing description...',
      'distress_detected': 'âš  Distress signals detected!',
      'no_distress_detected': 'âœ… No distress detected',
      'priority': 'Priority',
      'confidence': 'confidence',
      'alert_broadcast_channels': 'Alert broadcast via all available channels',
      'your_location_sent': 'Your location will be sent with this alert. The alert will be broadcast via all available channels (cloud, Bluetooth mesh, Wi-Fi Direct, LoRa).',
      'failed_to_send_sos': 'Failed to send SOS:',
      'permissions_required': 'Permissions Required',
      'grant_permissions': 'Grant Permissions',
      'location': 'Location',
      'bluetooth': 'Bluetooth',
      'storage': 'Storage',
      'unread_messages': 'Unread Messages',
      'active_alerts': 'Active Alerts',
      'recent_messages': 'Recent Messages',
      'no_recent_messages': 'No recent messages',
      'open_inbox': 'Open Inbox',
      'unknown_sender': 'Unknown',
      'medical_info': 'Medical Info',
      'privacy_security': 'Privacy & Security',
      'stealth_mode_sos': 'Stealth Mode SOS',
      'silent_panic_trigger': 'Silent panic trigger via hardware buttons',
      'stealth_mode_description': 'When enabled, hardware triggers (Volume Up + Down) will send a silent SOS without showing any UI or making sound.',
      'close': 'CLOSE',
      'save': 'SAVE',
      'name': 'Name',
      'phone': 'Phone',
      'profile_updated': 'Profile updated',
      'medical_info_saved': 'Medical info saved',
      'blood_type': 'Blood Type',
      'allergies': 'Allergies',
      'medications': 'Medications',
      'medical_conditions': 'Medical Conditions',
      'add_contact': 'Add Contact',
      'edit_contact': 'Edit Contact',
      'no_contacts': 'No emergency contacts added yet.',
      'read_privacy_policy': 'Read Privacy Policy',
      'open_full_map': 'Open Full Map',
      'zones_nearby': 'zone(s) nearby',
      'failed_to_load': 'Failed to load',
      'change_language': 'Change Language',
      'english': 'English',
      'yoruba': 'YorÃ¹bÃ¡',
      'igbo': 'Igbo',
      'hausa': 'Hausa',
      'trapped': 'Trapped',
      'lost': 'Lost',
      'structural_damage': 'Structural Damage',
      'other_emergency': 'Other Emergency',
      'general_emergency': 'General Emergency',
      'silent_panic': 'Silent Panic',
      'stealth_sos': 'Stealth mode SOS triggered from SOS screen',
      'stealth_sos_dashboard': 'Stealth mode SOS triggered from dashboard',
      'emergency_user': 'Emergency User',
      'offline_mode': 'Offline Mode',
      'medical_info_title': 'Medical Info',
      'privacy_security_title': 'Privacy & Security',
      'edit_profile_title': 'Edit Profile',
      'emergency_contacts_title': 'Emergency Contacts',
      'about_title': 'About',
      'app_version': '1.0.0 (Nigeria Edition)',
      'sectop_description': 'A specialized emergency system designed for high-risk security environments.',
      'no_emergency_contacts': 'No emergency contacts added yet.',
      'add_contact_title': 'Add Contact',
      'edit_contact_title': 'Edit Contact',
      'contact_name': 'Name',
      'contact_phone': 'Phone Number',
      'save_contact': 'SAVE',
      'cancel_btn': 'CANCEL',
      'close_btn': 'CLOSE',
      'save_btn': 'SAVE',
      'cancel_action': 'CANCEL',
      'close_action': 'CLOSE',
      'save_action': 'SAVE',
      'permission_location': 'Location',
      'permission_notifications': 'Notifications',
      'permission_bluetooth': 'Bluetooth',
      'permission_storage': 'Storage',
    },
    'yo': {
      'app_name': 'Sectop',
      'send_sos': 'RAN SOS',
      'tap_emergency': 'Táº¹ fun itaniji pajawiri',
      'quick_actions': 'Awá»n iá¹£e iyara',
      'safe_zones': 'Awá»n agbegbe ailewu',
      'mesh_network': 'Náº¹tiwá»á»ki Mesh',
      'messages': 'Awá»n ifiraná¹£áº¹',
      'first_aid': 'Iranwo aká»ká»',
      'system_status': 'Ipo eto',
      'cloud_connection': 'Asopá»má»ra awá»sanma',
      'connected': 'Asopá»',
      'offline': 'Aisi asopá»',
      'location_tracking': 'Ipiláº¹ ipo',
      'active': 'á¹¢iá¹£áº¹',
      'inactive': 'Aiá¹£iá¹£áº¹',
      'sync_status': 'Ipo amuá¹£iá¹£áº¹pá»',
      'sos_active': 'SOS á¹£iá¹£áº¹',
      'cancel': 'Fagilee',
      'ok': 'O dara',
      'error': 'Aá¹£iá¹£e',
      'loading': 'N gba lati...',
      'retry': 'Tun gbiyanju',
      'settings': 'Awá»n eto',
      'profile': 'Profaili',
      'about': 'Nipa',
      'help': 'Iranwá»',
      'privacy_policy': 'Eto imulo asiri',
      'logout': 'Ijade',
      'dashboard': 'Dasibodu',
      'alerts': 'Awá»n itaniji',
      'emergency_contacts': 'Awá»n olubasá»rá» pajawiri',
      'report_incident': 'Jabá» iá¹£áº¹láº¹',
      'nearby_dangers': 'Awá»n ewu nitosi',
      'safe_route': 'á»Œna ailewu',
      'language': 'Ede',
      'dark_mode': 'Ipo dudu',
      'notifications': 'Awá»n ifitonileti',
      'permission_required': 'Sectop nilo awá»n igbanilaaye wá»nyi lati rii daju aabo ráº¹ ni awá»n oju iá¹£áº¹láº¹ to á¹£e pataki.',
      'welcome_title': 'Kaabo si Sectop',
      'welcome_description': 'Itá»sá»na yii yoo ran á» lá»wá» lati loye bi o á¹£e le lo ohun elo naa daradara fun aabo ráº¹ ati lati ran awá»n áº¹lomiran lá»wá» lakoko awá»n pajawiri.',
      'version': 'Sectop v',
      'about_description': 'Eto pajawiri pataki kan ti a á¹£e apáº¹ráº¹ fun awá»n agbegbe aabo eewu giga.',
      'push_notifications': 'Awá»n ifitonileti Titari',
      'receive_alerts_messages': 'Gba awá»n itaniji ati awá»n ifiraná¹£áº¹',
      'appearance': 'Ifarahan',
      'light_mode': 'Ipo Imá»láº¹',
      'system_default': 'Aiyipada Eto',
      'data_usage': 'Lilo Data',
      'data_saver_mode': 'Ipo Ifipamá» Data',
      'reduce_data_usage': 'Dinku lilo data fun awá»n maapu ati amuá¹£iá¹£áº¹pá»',
      'auto_download_maps': 'Gba awá»n maapu laifá»wá»yi',
      'preload_map_tiles': 'Táº¹ awá»n maapu táº¹láº¹ fun lilo offline',
      'cache_management': 'Iá¹£akoso Kaá¹£e',
      'cache_size': 'Iwá»n kaá¹£e',
      'clear_cache': 'Nu Kaá¹£e',
      'data_management': 'Iá¹£akoso Data',
      'delete_local_data': 'Pa Data Agbegbe ráº¹',
      'clear_messages_cache': 'Nu awá»n ifiraná¹£áº¹, kaá¹£e, ati awá»n ayanfáº¹ (o ntá»ju aká»á»láº¹)',
      'account': 'Aká»á»láº¹',
      'delete_account': 'Pa Aká»á»láº¹ ráº¹',
      'permanently_remove_account': 'Yá» aká»á»láº¹ ati data ráº¹ kuro patapata',
      'support': 'Atiláº¹yin',
      'rate_on_play_store': 'á¹¢e idiyele lori Play Store',
      'rate_this_app': 'á¹¢e idiyele app yii ki o fi imá»ran siláº¹',
      'contact_support': 'Kan si Atiláº¹yin',
      'how_to_use': 'Bii o á¹£e le Lo',
      'learn_how_to_use': 'Ká» áº¹ká» bi o á¹£e le lo app naa',
      'delete_local_data_title': 'Pa Data Agbegbe ráº¹',
      'delete_local_data_message': 'Eyi yoo pa gbogbo awá»n ifiraná¹£áº¹ ti o fipamá» ni agbegbe, data kaá¹£e, ati awá»n ayanfáº¹ ráº¹. Aká»á»láº¹ ráº¹ (ti o ba wa) kii yoo kan. A ko le á¹£e atuná¹£e iá¹£e yii.',
      'delete': 'Paaráº¹',
      'language_changed_to': 'Ede ti yipada si',
      'local_data_deleted': 'Data agbegre ti paaráº¹ ni aá¹£eyá»ri',
      'cache_cleared': 'Kaá¹£e ti nu kuro ni aá¹£eyá»ri',
      'could_not_open_play_store': 'Ko le á¹£ii Play Store',
      'contact': 'Kan si',
      'home': 'Ile',
      'map': 'Maapu',
      'inbox': 'Apoti ifiraná¹£áº¹',
      'medical_emergency': 'Pajawiri Iá¹£oogun',
      'fire': 'Ina',
      'natural_disaster': 'Ajalu Adayeba',
      'violence_attack': 'Iwa-ipa/Iká»lu',
      'kidnapping': 'Jigbe',
      'other': 'Miiran',
      'describe_emergency': 'á¹¢e apejuwe ipo pajawiri ráº¹...',
      'send_sos_alert': 'Fi Itaniji SOS RÃ¡n',
      'sos_sent': 'SOS Ti Firaná¹£áº¹!',
      'help_is_on_the_way': 'Iranwá» n bá». Jáº¹Ì kÃ­ o fá»kÃ n baláº¹ ki o si wa lailewu.',
      'sending': 'N firaná¹£áº¹...',
      'add_evidence': 'Fi áº¸ri Kun',
      'capture_photo': 'Ya Fá»to',
      'record_video': 'Gba Fidio',
      'record_audio': 'Gba Ohun',
      'evidence_captured': 'áº¸ri Ti Ya',
      'sos_will_send_in': 'SOS yoo firaná¹£áº¹ ni',
      'seconds': 'aaya',
      'login': 'Wá»le',
      'email': 'Imeeli',
      'password': 'á»Œrá»igbaniwá»le',
      'forgot_password': 'Gbagbe á»Œrá»igbaniwá»le?',
      'dont_have_account': 'Ko ni aká»á»láº¹?',
      'sign_up': 'Foruká»siláº¹',
      'emergency_bypass': 'Fori Pajawiri',
      'use_offline': 'Lo Laisi Asopá»',
      'permission_title': 'Awá»n igbanilaaye ti a beere',
      'grant_permissions': 'Funni ni Awá»n igbanilaaye',
      'location_permission': 'Ipo',
      'location_permission_desc': 'Fun awá»n itaniji SOS ati wiwa ewu nitosi',
      'notification_permission': 'Awá»n ifitonileti',
      'notification_permission_desc': 'Fun awá»n itaniji pajawiri ati awá»n imudojuiwá»n',
      'bluetooth_permission': 'Bluetooth',
      'bluetooth_permission_desc': 'Fun ibaraáº¹nisá»rá» náº¹tiwá»á»ki mesh',
      'storage_permission': 'Ibi ipamá»',
      'storage_permission_desc': 'Fun gbigba áº¹ri ati data offline',
      'first_aid_guide': 'Itá»sá»na Iranwo Aká»ká»',
      'bleeding': 'áº¸jáº¹',
      'burns': 'InÃ¡',
      'fractures': 'Egugun dida',
      'choking': 'Gbigbá»n',
      'cpr': 'CPR',
      'shock': 'Má»namá»na',
      'snake_bite': 'Buje Ejo',
      'emergency_numbers': 'Awá»n ná»mba pajawiri',
      'police': 'á»Œlá»pa',
      'ambulance': 'á»Œká» alaisan',
      'fire_service': 'Eto ina',
      'broadcast': 'Igbohunsafefe',
      'create_broadcast': 'á¹¢áº¹da Igbohunsafefe',
      'broadcast_message': 'Ifiraná¹£áº¹ Igbohunsafefe',
      'send_broadcast': 'Fi Igbohunsafefe RÃ¡n',
      'target_audience': 'Awá»n olugbo ibi-afáº¹de',
      'everyone': 'Gbogbo eniyan',
      'responders_only': 'Awá»n oludahun nikan',
      'specific_zone': 'Agbegbe kan pato',
      'radio_broadcast': 'Igbohunsafefe Redio',
      'create_radio_broadcast': 'á¹¢áº¹da Igbohunsafefe Redio',
      'message_content': 'Akoonu Ifiraná¹£áº¹',
      'target_state': 'Ipinle ibi-afáº¹de',
      'target_lga': 'LGA ibi-afáº¹de',
      'schedule_broadcast': 'á¹¢eto Igbohunsafefe',
      'tip_off': 'Ifitonileti',
      'submit_tip': 'Fi Ifitonileti RÃ¡n',
      'anonymous_tip': 'Ifitonileti Ailá»ruká»',
      'tip_description': 'á¹¢e apejuwe ohun ti o má»...',
      'tip_type': 'Iru Ifitonileti',
      'suspicious_activity': 'Iá¹£áº¹ Ifura',
      'planned_attack': 'Iká»lu Ti a Gbero',
      'wanted_person': 'Eniyan Ti a Fáº¹',
      'drug_trafficking': 'Gbigbe OÃ²gÃ¹n',
      'other_tip': 'Miiran',
      'incident_report': 'Iroyin Iá¹£áº¹láº¹',
      'incident_type': 'Iru Iá¹£áº¹láº¹',
      'incident_description': 'á¹¢e apejuwe iá¹£áº¹láº¹ naa...',
      'submit_report': 'Fi Iroyin RÃ¡n',
      'incident_reported': 'Iá¹£áº¹láº¹ Ti Royin',
      'thank_you_report': 'O á¹£eun fun ijabá» ráº¹. A ti fi to awá»n alaá¹£áº¹ leti.',
      'search_location': 'á¹¢e agbekaláº¹ ipo...',
      'current_location': 'Ipo Lá»wá»lá»wá»',
      'danger_zones': 'Awá»n agbegbe ewu',
      'safe_zones_map': 'Awá»n agbegbe ailewu',
      'satellite_view': 'Wiwo Satáº¹laá»‹ti',
      'street_view': 'Wiwo Opopona',
      'no_messages': 'Ko si awá»n ifiraná¹£áº¹ sibáº¹sibáº¹',
      'type_message': 'Táº¹ ifiraná¹£áº¹ sii...',
      'send': 'Fi RÃ¡n',
      'mark_as_read': 'Samisi bi a ti ka',
      'delete_message': 'Pa Ifiraná¹£áº¹ ráº¹',
      'mesh_status': 'Ipo Mesh',
      'connected_devices': 'Awá»n áº¹rá» ti a ti sopá»',
      'scan_for_devices': 'á¹¢e ayáº¹wo fun awá»n áº¹rá»',
      'no_devices_found': 'Ko si awá»n áº¹rá» ti a ri',
      'mesh_active': 'Mesh á¹¢iá¹£áº¹',
      'mesh_inactive': 'Mesh Aiá¹£iá¹£áº¹',
      'threat_awareness': 'Akiyesi Irokeke',
      'current_threat_level': 'Ipele Irokeke Lá»wá»lá»wá»',
      'nearby_incidents': 'Awá»n iá¹£áº¹láº¹ nitosi',
      'nearby_danger_zones': 'Awá»n agbegbe ewu nitosi',
      'no_threats': 'Ko si awá»n irokeke ti a ri',
      'threat_alerts': 'Awá»n itaniji irokeke',
      'mark_all_read': 'Samisi Gbogbo bi a ti ka',
      'plan_safe_route': 'Gbero á»Œna Ailewu',
      'origin': 'Ibi ti a ti báº¹ráº¹',
      'destination': 'Ibi ti a nlo',
      'find_safe_route': 'Wa á»Œna Ailewu',
      'route_found': 'á»Œna Ti Ri',
      'no_safe_route': 'Ko si á»na ailewu to wa',
      'edit_profile': 'á¹¢atunká» Profaili',
      'full_name': 'Oruká» Kikun',
      'phone_number': 'Ná»mba Foonu',
      'save_changes': 'Fi Awá»n Ayipada Pamá»',
      'change_password': 'Yi á»Œrá»igbaniwá»le Pada',
      'current_password': 'á»Œrá»igbaniwá»le Lá»wá»lá»wá»',
      'new_password': 'á»Œrá»igbaniwá»le Tuntun',
      'confirm_password': 'Jáº¹risi á»Œrá»igbaniwá»le',
      'walkie_talkie': 'Walkie Talkie',
      'push_to_talk': 'Táº¹ lati Sá»rá»',
      'release_to_send': 'Tu siláº¹ lati Fi RÃ¡n',
      'listening': 'N gbá»...',
      'zone_details': 'Awá»n alaye agbegbe',
      'zone_name': 'Oruká» agbegbe',
      'zone_type': 'Iru agbegbe',
      'restricted_area': 'Agbegbe ihamá»',
      'danger_area': 'Agbegbe ewu',
      'safe_area': 'Agbegbe ailewu',
      'expires_at': 'O pari ni',
      'created_by': 'Ti a á¹£áº¹da nipasáº¹',
      'offline_resources': 'Awá»n orisun Laisi Asopá»',
      'download_resources': 'Gba Awá»n orisun',
      'downloaded': 'Ti gba lati ayelujara',
      'not_downloaded': 'A ko gba lati ayelujara',
      'help_center': 'Ile Iranwá»',
      'faq': 'FAQ',
      'report_problem': 'Jabá» Iá¹£oro kan',
      'terms_of_service': 'Awá»n ofin Iá¹£áº¹',
      'welcome_back': 'Kaabo Pada',
      'create_account': 'á¹¢áº¹da Aká»á»láº¹',
      'sign_in_to_access': 'Wá»le lati wá»le si awá»n iá¹£áº¹ pajawiri',
      'register_for_assistance': 'Foruká»siláº¹ fun iranlá»wá» pajawiri',
      'sign_in': 'Wá»le',
      'already_have_account': 'Ni aká»á»láº¹ táº¹láº¹? Wá»le',
      'dont_have_account_register': 'Ko ni aká»á»láº¹? Foruká»siláº¹',
      'emergency_access_no_login': 'Wiwá»le Pajawiri (Ko si Iwá»le)',
      'use_in_disaster': 'Lo ni awá»n ipo ajalu nigbati o ko le wá»le',
      'skip_login_guest': 'Fori Iwá»le â€” Lo bi Alejo',
      'browse_without_account': 'Wo awá»n igbohunsafefe, wo awá»n agbegbe ailewu, ki o wá»le si alaye pajawiri laisi aká»á»láº¹',
      'contact_support_email': 'Kan si Atiláº¹yin:',
      'authentication_failed': 'Ijáº¹risi kuna',
      'connection_error_offline': 'Aá¹£iá¹£e asopá». Lilo ipo offline.',
      'failed_emergency_mode': 'Kuna lati táº¹ ipo pajawiri',
      'please_enter_name': 'Já»wá» táº¹ oruká» ráº¹ sii',
      'please_enter_email': 'Já»wá» táº¹ imeeli ráº¹ sii',
      'please_enter_valid_email': 'Já»wá» táº¹ imeeli to wulo sii',
      'please_enter_phone': 'Jọwọ tẹ nọmba foonu rẹ sii',
      'please_enter_password': 'Jọwọ tẹ ọrọmọmọ asọpọ rẹ sii',
      'password_min_chars': 'Ọrọmọmọ asọpọ gbọdọdọd kọ ó kérẹ sii ju àṣẹ 8',
        'emergency_tools': 'Awọn irinṣẹ pajawiri',
        'broadcasts': 'Awọn igbohunsafefe',
        'radio': 'Redio',
        'data_sync': 'Amuṣiṣi data',
        'syncing': 'Ìmúṣiṣi',
        'pending_items': 'Awọn nkan ti o nduro',
        'peers_connected': 'Awọn ẹlẹgbẹ ti a sopọ',
        'sos_sent_silently': 'SOS ti firanṣẹ ni ọpalọlọ',
        'sos_failed': 'SOS kuna',
        'send_sos_alert_title': 'Firanṣẹ itaniji SOS',
        'alert_type': 'Iru itaniji',
        'select_alert_type': 'Yan iru itaniji',
        'description_optional': 'Apejuwe (aṣayan)',
        'capture_evidence_optional': 'Gba ẹri (aṣayan)',
        'photo': 'Fọtọ',
        'video': 'Fidio',
        'audio': 'Ohun',
        'sending_in_seconds': 'Firanṣẹ ni {} aaya',
        'tap_to_send_alert': 'Tẹ lati firanṣẹ itaniji',
        'ai_analyzing': 'AI n ṣe itupalẹ...',
        'distress_detected': 'Wahala ti a rii',
        'no_distress_detected': 'Ko si wahala ti a rii',
        'priority': 'Pataki',
        'confidence': 'Igbagbọ',
        'alert_broadcast_channels': 'Awọn ikanni igbohunsafefe itaniji',
        'your_location_sent': 'Ipo rẹ ti firanṣẹ',
        'failed_to_send_sos': 'Kuna lati firanṣẹ SOS',
        'permissions_required': 'Awọn igbanilaaye ti a beere',
        'location': 'Ipo',
        'bluetooth': 'Bluetooth',
        'storage': 'Ibi ipamọ',
        'unread_messages': 'Awọn ifiranṣẹ ti a ko ka',
        'active_alerts': 'Awọn itaniji ti nṣiṣe lọwọ',
        'recent_messages': 'Awọn ifiranṣẹ aipẹ',
        'no_recent_messages': 'Ko si awọn ifiranṣẹ aipẹ',
        'open_inbox': 'Ṣii apoti ifiranṣẹ',
        'unknown_sender': 'Olufiranṣẹ aimọ',
        'medical_info': 'Alaye iṣoogun',
        'privacy_security': 'Aṣiri ati Aabo',
        'stealth_mode_sos': 'Ipo SOS ni ikoko',
        'silent_panic_trigger': 'Ikọlọ ọpalọlọ',
        'stealth_mode_description': 'Ipo ikoko n gba ọ laaye lati firanṣẹ itaniji laisi ṣiṣi apoti ifiranṣẹ',
        'close': 'Pa',
        'save': 'Fipamọ',
        'name': 'Orukọ',
        'phone': 'Foonu',
        'profile_updated': 'Profaili ti imudojuiwọn',
        'medical_info_saved': 'Alaye iṣoogun ti fipamọ',
        'blood_type': 'Iru ẹjẹ',
        'allergies': 'Awọn aleji',
        'medications': 'Awọn oogun',
        'medical_conditions': 'Awọn ipo iṣoogun',
        'add_contact': 'Fi olubasọrọ kun',
        'edit_contact': 'Ṣatunkọ olubasọrọ',
        'no_contacts': 'Ko si awọn olubasọrọ',
        'read_privacy_policy': 'Ka eto aṣiri',
        'open_full_map': 'Ṣii maapu ni kikun',
        'zones_nearby': 'Awọn agbegbe nitosi',
        'failed_to_load': 'Kuna lati gbe',
        'change_language': 'Yi ede pada',
        'english': 'Gẹ̀ẹ́sì',
        'yoruba': 'Yorùbá',
        'igbo': 'Igbo',
        'hausa': 'Hausa',
        'trapped': 'Idẹkùn',
        'lost': 'Pàdánù',
        'structural_damage': 'Ibajẹ igbekalẹ',
        'other_emergency': 'Pajawiri miiran',
        'general_emergency': 'Pajawiri gbogbogbo',
        'silent_panic': 'Ipayà ọpalọlọ',
        'stealth_sos': 'SOS ikoko',
        'stealth_sos_dashboard': 'SOS ikoko',
        'emergency_user': 'Olumulo pajawiri',
        'offline_mode': 'Ipo aisọpọ',
        'medical_info_title': 'Alaye iṣoogun',
        'privacy_security_title': 'Aṣiri ati Aabo',
        'edit_profile_title': 'Ṣatunkọ profaili',
        'emergency_contacts_title': 'Awọn olubasọrọ pajawiri',
        'about_title': 'Nipa',
        'app_version': 'Ẹya ohun elo',
        'sectop_description': 'Sectop jẹ ohun elo aabo agbegbe ti o fun ọ laaye lati gba awọn itaniji ati awọn imudojuiwọn lori awọn irokeke ewu',
        'no_emergency_contacts': 'Ko si awọn olubasọrọ pajawiri',
        'add_contact_title': 'Fi olubasọrọ kun',
        'edit_contact_title': 'Ṣatunkọ olubasọrọ',
        'contact_name': 'Orukọ olubasọrọ',
        'contact_phone': 'Foonu olubasọrọ',
        'save_contact': 'Fipamọ olubasọrọ',
        'cancel_btn': 'Fagilee',
        'close_btn': 'Pa',
        'save_btn': 'Fipamọ',
        'cancel_action': 'Fagilee',
        'close_action': 'Pa',
        'save_action': 'Fipamọ',
        'permission_location': 'Ipo',
        'permission_notifications': 'Awọn ifitonileti',
        'permission_bluetooth': 'Bluetooth',
        'permission_storage': 'Ibi ipamọ',
      },
      'ig': {
        'app_name': 'App Name',
        'send_sos': 'Send Sos',
        'tap_emergency': 'Tap Emergency',
        'quick_actions': 'Quick Actions',
        'safe_zones': 'Safe Zones',
        'mesh_network': 'Mesh Network',
        'messages': 'Messages',
        'first_aid': 'First Aid',
        'system_status': 'System Status',
        'cloud_connection': 'Cloud Connection',
        'connected': 'Connected',
        'offline': 'Offline',
        'location_tracking': 'Location Tracking',
        'active': 'Active',
        'inactive': 'Inactive',
        'sync_status': 'Sync Status',
        'sos_active': 'Sos Active',
        'cancel': 'Cancel',
        'ok': 'Ok',
        'error': 'Error',
        'loading': 'Loading',
        'retry': 'Retry',
        'settings': 'Settings',
        'profile': 'Profile',
        'about': 'About',
        'help': 'Help',
        'privacy_policy': 'Privacy Policy',
        'logout': 'Logout',
        'dashboard': 'Dashboard',
        'alerts': 'Alerts',
        'emergency_contacts': 'Emergency Contacts',
        'report_incident': 'Report Incident',
        'nearby_dangers': 'Nearby Dangers',
        'safe_route': 'Safe Route',
        'language': 'Language',
        'dark_mode': 'Dark Mode',
        'notifications': 'Notifications',
        'permission_required': 'Permission Required',
        'welcome_title': 'Welcome Title',
        'welcome_description': 'Welcome Description',
        'version': 'Version',
        'about_description': 'About Description',
        'push_notifications': 'Push Notifications',
        'receive_alerts_messages': 'Receive Alerts Messages',
        'appearance': 'Appearance',
        'light_mode': 'Light Mode',
        'system_default': 'System Default',
        'data_usage': 'Data Usage',
        'data_saver_mode': 'Data Saver Mode',
        'reduce_data_usage': 'Reduce Data Usage',
        'auto_download_maps': 'Auto Download Maps',
        'preload_map_tiles': 'Preload Map Tiles',
        'cache_management': 'Cache Management',
        'cache_size': 'Cache Size',
        'clear_cache': 'Clear Cache',
        'data_management': 'Data Management',
        'delete_local_data': 'Delete Local Data',
        'clear_messages_cache': 'Clear Messages Cache',
        'account': 'Account',
        'delete_account': 'Delete Account',
        'permanently_remove_account': 'Permanently Remove Account',
        'support': 'Support',
        'rate_on_play_store': 'Rate On Play Store',
        'rate_this_app': 'Rate This App',
        'contact_support': 'Contact Support',
        'how_to_use': 'How To Use',
        'learn_how_to_use': 'Learn How To Use',
        'delete_local_data_title': 'Delete Local Data Title',
        'delete_local_data_message': 'Delete Local Data Message',
        'delete': 'Delete',
        'language_changed_to': 'Language Changed To',
        'local_data_deleted': 'Local Data Deleted',
        'cache_cleared': 'Cache Cleared',
        'could_not_open_play_store': 'Could Not Open Play Store',
        'contact': 'Contact',
        'home': 'Home',
        'map': 'Map',
        'inbox': 'Inbox',
        'medical_emergency': 'Medical Emergency',
        'fire': 'Fire',
        'natural_disaster': 'Natural Disaster',
        'violence_attack': 'Violence Attack',
        'kidnapping': 'Kidnapping',
        'other': 'Other',
        'describe_emergency': 'Describe Emergency',
        'send_sos_alert': 'Send Sos Alert',
        'sos_sent': 'Sos Sent',
        'help_is_on_the_way': 'Help Is On The Way',
        'sending': 'Sending',
        'add_evidence': 'Add Evidence',
        'capture_photo': 'Capture Photo',
        'record_video': 'Record Video',
        'record_audio': 'Record Audio',
        'evidence_captured': 'Evidence Captured',
        'sos_will_send_in': 'Sos Will Send In',
        'seconds': 'Seconds',
        'login': 'Login',
        'email': 'Email',
        'password': 'Password',
        'forgot_password': 'Forgot Password',
        'sign_up': 'Sign Up',
        'emergency_bypass': 'Emergency Bypass',
        'use_offline': 'Use Offline',
        'permission_title': 'Permission Title',
        'grant_permissions': 'Grant Permissions',
        'location_permission': 'Location Permission',
        'location_permission_desc': 'Location Permission Desc',
        'notification_permission': 'Notification Permission',
        'notification_permission_desc': 'Notification Permission Desc',
        'bluetooth_permission': 'Bluetooth Permission',
        'bluetooth_permission_desc': 'Bluetooth Permission Desc',
        'storage_permission': 'Storage Permission',
        'storage_permission_desc': 'Storage Permission Desc',
        'first_aid_guide': 'First Aid Guide',
        'bleeding': 'Bleeding',
        'burns': 'Burns',
        'fractures': 'Fractures',
        'choking': 'Choking',
        'cpr': 'Cpr',
        'shock': 'Shock',
        'snake_bite': 'Snake Bite',
        'emergency_numbers': 'Emergency Numbers',
        'police': 'Police',
        'ambulance': 'Ambulance',
        'fire_service': 'Fire Service',
        'broadcast': 'Broadcast',
        'create_broadcast': 'Create Broadcast',
        'broadcast_message': 'Broadcast Message',
        'send_broadcast': 'Send Broadcast',
        'target_audience': 'Target Audience',
        'everyone': 'Everyone',
        'responders_only': 'Responders Only',
        'specific_zone': 'Specific Zone',
        'radio_broadcast': 'Radio Broadcast',
        'create_radio_broadcast': 'Create Radio Broadcast',
        'message_content': 'Message Content',
        'target_state': 'Target State',
        'target_lga': 'Target Lga',
        'schedule_broadcast': 'Schedule Broadcast',
        'tip_off': 'Tip Off',
        'submit_tip': 'Submit Tip',
        'anonymous_tip': 'Anonymous Tip',
        'tip_description': 'Tip Description',
        'tip_type': 'Tip Type',
        'suspicious_activity': 'Suspicious Activity',
        'planned_attack': 'Planned Attack',
        'wanted_person': 'Wanted Person',
        'drug_trafficking': 'Drug Trafficking',
        'other_tip': 'Other Tip',
        'incident_report': 'Incident Report',
        'incident_type': 'Incident Type',
        'incident_description': 'Incident Description',
        'submit_report': 'Submit Report',
        'incident_reported': 'Incident Reported',
        'thank_you_report': 'Thank You Report',
        'search_location': 'Search Location',
        'current_location': 'Current Location',
        'danger_zones': 'Danger Zones',
        'safe_zones_map': 'Safe Zones Map',
        'satellite_view': 'Satellite View',
        'street_view': 'Street View',
        'no_messages': 'No Messages',
        'type_message': 'Type Message',
        'send': 'Send',
        'mark_as_read': 'Mark As Read',
        'delete_message': 'Delete Message',
        'mesh_status': 'Mesh Status',
        'connected_devices': 'Connected Devices',
        'scan_for_devices': 'Scan For Devices',
        'no_devices_found': 'No Devices Found',
        'mesh_active': 'Mesh Active',
        'mesh_inactive': 'Mesh Inactive',
        'threat_awareness': 'Threat Awareness',
        'current_threat_level': 'Current Threat Level',
        'nearby_incidents': 'Nearby Incidents',
        'nearby_danger_zones': 'Nearby Danger Zones',
        'no_threats': 'No Threats',
        'threat_alerts': 'Threat Alerts',
        'mark_all_read': 'Mark All Read',
        'plan_safe_route': 'Plan Safe Route',
        'origin': 'Origin',
        'destination': 'Destination',
        'find_safe_route': 'Find Safe Route',
        'route_found': 'Route Found',
        'no_safe_route': 'No Safe Route',
        'edit_profile': 'Edit Profile',
        'full_name': 'Full Name',
        'phone_number': 'Phone Number',
        'save_changes': 'Save Changes',
        'change_password': 'Change Password',
        'current_password': 'Current Password',
        'new_password': 'New Password',
        'confirm_password': 'Confirm Password',
        'walkie_talkie': 'Walkie Talkie',
        'push_to_talk': 'Push To Talk',
        'release_to_send': 'Release To Send',
        'listening': 'Listening',
        'zone_details': 'Zone Details',
        'zone_name': 'Zone Name',
        'zone_type': 'Zone Type',
        'restricted_area': 'Restricted Area',
        'danger_area': 'Danger Area',
        'safe_area': 'Safe Area',
        'expires_at': 'Expires At',
        'created_by': 'Created By',
        'offline_resources': 'Offline Resources',
        'download_resources': 'Download Resources',
        'downloaded': 'Downloaded',
        'not_downloaded': 'Not Downloaded',
        'help_center': 'Help Center',
        'faq': 'Faq',
        'report_problem': 'Report Problem',
        'terms_of_service': 'Terms Of Service',
        'welcome_back': 'Welcome Back',
        'create_account': 'Create Account',
        'sign_in_to_access': 'Sign In To Access',
        'register_for_assistance': 'Register For Assistance',
        'sign_in': 'Sign In',
        'already_have_account': 'Already Have Account',
        'emergency_access_no_login': 'Emergency Access No Login',
        'use_in_disaster': 'Use In Disaster',
        'skip_login_guest': 'Skip Login Guest',
        'browse_without_account': 'Browse Without Account',
        'contact_support_email': 'Contact Support Email',
        'authentication_failed': 'Authentication Failed',
        'connection_error_offline': 'Connection Error Offline',
        'failed_emergency_mode': 'Failed Emergency Mode',
        'please_enter_name': 'Please Enter Name',
        'please_enter_email': 'Please Enter Email',
        'please_enter_valid_email': 'Please Enter Valid Email',
        'please_enter_phone': 'Please Enter Phone',
        'please_enter_password': 'Please Enter Password',
        'password_min_chars': 'Password Min Chars',
        'emergency_tools': 'Emergency Tools',
        'broadcasts': 'Broadcasts',
        'radio': 'Radio',
        'data_sync': 'Data Sync',
        'syncing': 'Syncing',
        'pending_items': 'Pending Items',
        'peers_connected': 'Peers Connected',
        'sos_sent_silently': 'Sos Sent Silently',
        'sos_failed': 'Sos Failed',
        'send_sos_alert_title': 'Send Sos Alert Title',
        'alert_type': 'Alert Type',
        'select_alert_type': 'Select Alert Type',
        'description_optional': 'Description Optional',
        'capture_evidence_optional': 'Capture Evidence Optional',
        'photo': 'Photo',
        'video': 'Video',
        'audio': 'Audio',
        'sending_in_seconds': 'Sending In Seconds',
        'tap_to_send_alert': 'Tap To Send Alert',
        'ai_analyzing': 'Ai Analyzing',
        'distress_detected': 'Distress Detected',
        'no_distress_detected': 'No Distress Detected',
        'priority': 'Priority',
        'confidence': 'Confidence',
        'alert_broadcast_channels': 'Alert Broadcast Channels',
        'your_location_sent': 'Your Location Sent',
        'failed_to_send_sos': 'Failed To Send Sos',
        'permissions_required': 'Permissions Required',
        'location': 'Location',
        'bluetooth': 'Bluetooth',
        'storage': 'Storage',
        'unread_messages': 'Unread Messages',
        'active_alerts': 'Active Alerts',
        'recent_messages': 'Recent Messages',
        'no_recent_messages': 'No Recent Messages',
        'open_inbox': 'Open Inbox',
        'unknown_sender': 'Unknown Sender',
        'medical_info': 'Medical Info',
        'privacy_security': 'Privacy Security',
        'stealth_mode_sos': 'Stealth Mode Sos',
        'silent_panic_trigger': 'Silent Panic Trigger',
        'stealth_mode_description': 'Stealth Mode Description',
        'close': 'Close',
        'save': 'Save',
        'name': 'Name',
        'phone': 'Phone',
        'profile_updated': 'Profile Updated',
        'medical_info_saved': 'Medical Info Saved',
        'blood_type': 'Blood Type',
        'allergies': 'Allergies',
        'medications': 'Medications',
        'medical_conditions': 'Medical Conditions',
        'add_contact': 'Add Contact',
        'edit_contact': 'Edit Contact',
        'no_contacts': 'No Contacts',
        'read_privacy_policy': 'Read Privacy Policy',
        'open_full_map': 'Open Full Map',
        'zones_nearby': 'Zones Nearby',
        'failed_to_load': 'Failed To Load',
        'change_language': 'Change Language',
        'english': 'English',
        'yoruba': 'Yoruba',
        'igbo': 'Igbo',
        'hausa': 'Hausa',
        'trapped': 'Trapped',
        'lost': 'Lost',
        'structural_damage': 'Structural Damage',
        'other_emergency': 'Other Emergency',
        'general_emergency': 'General Emergency',
        'silent_panic': 'Silent Panic',
        'stealth_sos': 'Stealth Sos',
        'stealth_sos_dashboard': 'Stealth Sos Dashboard',
        'emergency_user': 'Emergency User',
        'offline_mode': 'Offline Mode',
        'medical_info_title': 'Medical Info Title',
        'privacy_security_title': 'Privacy Security Title',
        'edit_profile_title': 'Edit Profile Title',
        'emergency_contacts_title': 'Emergency Contacts Title',
        'about_title': 'About Title',
        'app_version': 'App Version',
        'sectop_description': 'Sectop Description',
        'no_emergency_contacts': 'No Emergency Contacts',
        'add_contact_title': 'Add Contact Title',
        'edit_contact_title': 'Edit Contact Title',
        'contact_name': 'Contact Name',
        'contact_phone': 'Contact Phone',
        'save_contact': 'Save Contact',
        'cancel_btn': 'Cancel Btn',
        'close_btn': 'Close Btn',
        'save_btn': 'Save Btn',
        'cancel_action': 'Cancel Action',
        'close_action': 'Close Action',
        'save_action': 'Save Action',
        'permission_location': 'Permission Location',
        'permission_notifications': 'Permission Notifications',
        'permission_bluetooth': 'Permission Bluetooth',
        'permission_storage': 'Permission Storage'
      },
      'ha': {
        'app_name': 'App Name',
        'send_sos': 'Send Sos',
        'tap_emergency': 'Tap Emergency',
        'quick_actions': 'Quick Actions',
        'safe_zones': 'Safe Zones',
        'mesh_network': 'Mesh Network',
        'messages': 'Messages',
        'first_aid': 'First Aid',
        'system_status': 'System Status',
        'cloud_connection': 'Cloud Connection',
        'connected': 'Connected',
        'offline': 'Offline',
        'location_tracking': 'Location Tracking',
        'active': 'Active',
        'inactive': 'Inactive',
        'sync_status': 'Sync Status',
        'sos_active': 'Sos Active',
        'cancel': 'Cancel',
        'ok': 'Ok',
        'error': 'Error',
        'loading': 'Loading',
        'retry': 'Retry',
        'settings': 'Settings',
        'profile': 'Profile',
        'about': 'About',
        'help': 'Help',
        'privacy_policy': 'Privacy Policy',
        'logout': 'Logout',
        'dashboard': 'Dashboard',
        'alerts': 'Alerts',
        'emergency_contacts': 'Emergency Contacts',
        'report_incident': 'Report Incident',
        'nearby_dangers': 'Nearby Dangers',
        'safe_route': 'Safe Route',
        'language': 'Language',
        'dark_mode': 'Dark Mode',
        'notifications': 'Notifications',
        'permission_required': 'Permission Required',
        'welcome_title': 'Welcome Title',
        'welcome_description': 'Welcome Description',
        'version': 'Version',
        'about_description': 'About Description',
        'push_notifications': 'Push Notifications',
        'receive_alerts_messages': 'Receive Alerts Messages',
        'appearance': 'Appearance',
        'light_mode': 'Light Mode',
        'system_default': 'System Default',
        'data_usage': 'Data Usage',
        'data_saver_mode': 'Data Saver Mode',
        'reduce_data_usage': 'Reduce Data Usage',
        'auto_download_maps': 'Auto Download Maps',
        'preload_map_tiles': 'Preload Map Tiles',
        'cache_management': 'Cache Management',
        'cache_size': 'Cache Size',
        'clear_cache': 'Clear Cache',
        'data_management': 'Data Management',
        'delete_local_data': 'Delete Local Data',
        'clear_messages_cache': 'Clear Messages Cache',
        'account': 'Account',
        'delete_account': 'Delete Account',
        'permanently_remove_account': 'Permanently Remove Account',
        'support': 'Support',
        'rate_on_play_store': 'Rate On Play Store',
        'rate_this_app': 'Rate This App',
        'contact_support': 'Contact Support',
        'how_to_use': 'How To Use',
        'learn_how_to_use': 'Learn How To Use',
        'delete_local_data_title': 'Delete Local Data Title',
        'delete_local_data_message': 'Delete Local Data Message',
        'delete': 'Delete',
        'language_changed_to': 'Language Changed To',
        'local_data_deleted': 'Local Data Deleted',
        'cache_cleared': 'Cache Cleared',
        'could_not_open_play_store': 'Could Not Open Play Store',
        'contact': 'Contact',
        'home': 'Home',
        'map': 'Map',
        'inbox': 'Inbox',
        'medical_emergency': 'Medical Emergency',
        'fire': 'Fire',
        'natural_disaster': 'Natural Disaster',
        'violence_attack': 'Violence Attack',
        'kidnapping': 'Kidnapping',
        'other': 'Other',
        'describe_emergency': 'Describe Emergency',
        'send_sos_alert': 'Send Sos Alert',
        'sos_sent': 'Sos Sent',
        'help_is_on_the_way': 'Help Is On The Way',
        'sending': 'Sending',
        'add_evidence': 'Add Evidence',
        'capture_photo': 'Capture Photo',
        'record_video': 'Record Video',
        'record_audio': 'Record Audio',
        'evidence_captured': 'Evidence Captured',
        'sos_will_send_in': 'Sos Will Send In',
        'seconds': 'Seconds',
        'login': 'Login',
        'email': 'Email',
        'password': 'Password',
        'forgot_password': 'Forgot Password',
        'sign_up': 'Sign Up',
        'emergency_bypass': 'Emergency Bypass',
        'use_offline': 'Use Offline',
        'permission_title': 'Permission Title',
        'grant_permissions': 'Grant Permissions',
        'location_permission': 'Location Permission',
        'location_permission_desc': 'Location Permission Desc',
        'notification_permission': 'Notification Permission',
        'notification_permission_desc': 'Notification Permission Desc',
        'bluetooth_permission': 'Bluetooth Permission',
        'bluetooth_permission_desc': 'Bluetooth Permission Desc',
        'storage_permission': 'Storage Permission',
        'storage_permission_desc': 'Storage Permission Desc',
        'first_aid_guide': 'First Aid Guide',
        'bleeding': 'Bleeding',
        'burns': 'Burns',
        'fractures': 'Fractures',
        'choking': 'Choking',
        'cpr': 'Cpr',
        'shock': 'Shock',
        'snake_bite': 'Snake Bite',
        'emergency_numbers': 'Emergency Numbers',
        'police': 'Police',
        'ambulance': 'Ambulance',
        'fire_service': 'Fire Service',
        'broadcast': 'Broadcast',
        'create_broadcast': 'Create Broadcast',
        'broadcast_message': 'Broadcast Message',
        'send_broadcast': 'Send Broadcast',
        'target_audience': 'Target Audience',
        'everyone': 'Everyone',
        'responders_only': 'Responders Only',
        'specific_zone': 'Specific Zone',
        'radio_broadcast': 'Radio Broadcast',
        'create_radio_broadcast': 'Create Radio Broadcast',
        'message_content': 'Message Content',
        'target_state': 'Target State',
        'target_lga': 'Target Lga',
        'schedule_broadcast': 'Schedule Broadcast',
        'tip_off': 'Tip Off',
        'submit_tip': 'Submit Tip',
        'anonymous_tip': 'Anonymous Tip',
        'tip_description': 'Tip Description',
        'tip_type': 'Tip Type',
        'suspicious_activity': 'Suspicious Activity',
        'planned_attack': 'Planned Attack',
        'wanted_person': 'Wanted Person',
        'drug_trafficking': 'Drug Trafficking',
        'other_tip': 'Other Tip',
        'incident_report': 'Incident Report',
        'incident_type': 'Incident Type',
        'incident_description': 'Incident Description',
        'submit_report': 'Submit Report',
        'incident_reported': 'Incident Reported',
        'thank_you_report': 'Thank You Report',
        'search_location': 'Search Location',
        'current_location': 'Current Location',
        'danger_zones': 'Danger Zones',
        'safe_zones_map': 'Safe Zones Map',
        'satellite_view': 'Satellite View',
        'street_view': 'Street View',
        'no_messages': 'No Messages',
        'type_message': 'Type Message',
        'send': 'Send',
        'mark_as_read': 'Mark As Read',
        'delete_message': 'Delete Message',
        'mesh_status': 'Mesh Status',
        'connected_devices': 'Connected Devices',
        'scan_for_devices': 'Scan For Devices',
        'no_devices_found': 'No Devices Found',
        'mesh_active': 'Mesh Active',
        'mesh_inactive': 'Mesh Inactive',
        'threat_awareness': 'Threat Awareness',
        'current_threat_level': 'Current Threat Level',
        'nearby_incidents': 'Nearby Incidents',
        'nearby_danger_zones': 'Nearby Danger Zones',
        'no_threats': 'No Threats',
        'threat_alerts': 'Threat Alerts',
        'mark_all_read': 'Mark All Read',
        'plan_safe_route': 'Plan Safe Route',
        'origin': 'Origin',
        'destination': 'Destination',
        'find_safe_route': 'Find Safe Route',
        'route_found': 'Route Found',
        'no_safe_route': 'No Safe Route',
        'edit_profile': 'Edit Profile',
        'full_name': 'Full Name',
        'phone_number': 'Phone Number',
        'save_changes': 'Save Changes',
        'change_password': 'Change Password',
        'current_password': 'Current Password',
        'new_password': 'New Password',
        'confirm_password': 'Confirm Password',
        'walkie_talkie': 'Walkie Talkie',
        'push_to_talk': 'Push To Talk',
        'release_to_send': 'Release To Send',
        'listening': 'Listening',
        'zone_details': 'Zone Details',
        'zone_name': 'Zone Name',
        'zone_type': 'Zone Type',
        'restricted_area': 'Restricted Area',
        'danger_area': 'Danger Area',
        'safe_area': 'Safe Area',
        'expires_at': 'Expires At',
        'created_by': 'Created By',
        'offline_resources': 'Offline Resources',
        'download_resources': 'Download Resources',
        'downloaded': 'Downloaded',
        'not_downloaded': 'Not Downloaded',
        'help_center': 'Help Center',
        'faq': 'Faq',
        'report_problem': 'Report Problem',
        'terms_of_service': 'Terms Of Service',
        'welcome_back': 'Welcome Back',
        'create_account': 'Create Account',
        'sign_in_to_access': 'Sign In To Access',
        'register_for_assistance': 'Register For Assistance',
        'sign_in': 'Sign In',
        'already_have_account': 'Already Have Account',
        'emergency_access_no_login': 'Emergency Access No Login',
        'use_in_disaster': 'Use In Disaster',
        'skip_login_guest': 'Skip Login Guest',
        'browse_without_account': 'Browse Without Account',
        'contact_support_email': 'Contact Support Email',
        'authentication_failed': 'Authentication Failed',
        'connection_error_offline': 'Connection Error Offline',
        'failed_emergency_mode': 'Failed Emergency Mode',
        'please_enter_name': 'Please Enter Name',
        'please_enter_email': 'Please Enter Email',
        'please_enter_valid_email': 'Please Enter Valid Email',
        'please_enter_phone': 'Please Enter Phone',
        'please_enter_password': 'Please Enter Password',
        'password_min_chars': 'Password Min Chars',
        'emergency_tools': 'Emergency Tools',
        'broadcasts': 'Broadcasts',
        'radio': 'Radio',
        'data_sync': 'Data Sync',
        'syncing': 'Syncing',
        'pending_items': 'Pending Items',
        'peers_connected': 'Peers Connected',
        'sos_sent_silently': 'Sos Sent Silently',
        'sos_failed': 'Sos Failed',
        'send_sos_alert_title': 'Send Sos Alert Title',
        'alert_type': 'Alert Type',
        'select_alert_type': 'Select Alert Type',
        'description_optional': 'Description Optional',
        'capture_evidence_optional': 'Capture Evidence Optional',
        'photo': 'Photo',
        'video': 'Video',
        'audio': 'Audio',
        'sending_in_seconds': 'Sending In Seconds',
        'tap_to_send_alert': 'Tap To Send Alert',
        'ai_analyzing': 'Ai Analyzing',
        'distress_detected': 'Distress Detected',
        'no_distress_detected': 'No Distress Detected',
        'priority': 'Priority',
        'confidence': 'Confidence',
        'alert_broadcast_channels': 'Alert Broadcast Channels',
        'your_location_sent': 'Your Location Sent',
        'failed_to_send_sos': 'Failed To Send Sos',
        'permissions_required': 'Permissions Required',
        'location': 'Location',
        'bluetooth': 'Bluetooth',
        'storage': 'Storage',
        'unread_messages': 'Unread Messages',
        'active_alerts': 'Active Alerts',
        'recent_messages': 'Recent Messages',
        'no_recent_messages': 'No Recent Messages',
        'open_inbox': 'Open Inbox',
        'unknown_sender': 'Unknown Sender',
        'medical_info': 'Medical Info',
        'privacy_security': 'Privacy Security',
        'stealth_mode_sos': 'Stealth Mode Sos',
        'silent_panic_trigger': 'Silent Panic Trigger',
        'stealth_mode_description': 'Stealth Mode Description',
        'close': 'Close',
        'save': 'Save',
        'name': 'Name',
        'phone': 'Phone',
        'profile_updated': 'Profile Updated',
        'medical_info_saved': 'Medical Info Saved',
        'blood_type': 'Blood Type',
        'allergies': 'Allergies',
        'medications': 'Medications',
        'medical_conditions': 'Medical Conditions',
        'add_contact': 'Add Contact',
        'edit_contact': 'Edit Contact',
        'no_contacts': 'No Contacts',
        'read_privacy_policy': 'Read Privacy Policy',
        'open_full_map': 'Open Full Map',
        'zones_nearby': 'Zones Nearby',
        'failed_to_load': 'Failed To Load',
        'change_language': 'Change Language',
        'english': 'English',
        'yoruba': 'Yoruba',
        'igbo': 'Igbo',
        'hausa': 'Hausa',
        'trapped': 'Trapped',
        'lost': 'Lost',
        'structural_damage': 'Structural Damage',
        'other_emergency': 'Other Emergency',
        'general_emergency': 'General Emergency',
        'silent_panic': 'Silent Panic',
        'stealth_sos': 'Stealth Sos',
        'stealth_sos_dashboard': 'Stealth Sos Dashboard',
        'emergency_user': 'Emergency User',
        'offline_mode': 'Offline Mode',
        'medical_info_title': 'Medical Info Title',
        'privacy_security_title': 'Privacy Security Title',
        'edit_profile_title': 'Edit Profile Title',
        'emergency_contacts_title': 'Emergency Contacts Title',
        'about_title': 'About Title',
        'app_version': 'App Version',
        'sectop_description': 'Sectop Description',
        'no_emergency_contacts': 'No Emergency Contacts',
        'add_contact_title': 'Add Contact Title',
        'edit_contact_title': 'Edit Contact Title',
        'contact_name': 'Contact Name',
        'contact_phone': 'Contact Phone',
        'save_contact': 'Save Contact',
        'cancel_btn': 'Cancel Btn',
        'close_btn': 'Close Btn',
        'save_btn': 'Save Btn',
        'cancel_action': 'Cancel Action',
        'close_action': 'Close Action',
        'save_action': 'Save Action',
        'permission_location': 'Permission Location',
        'permission_notifications': 'Permission Notifications',
        'permission_bluetooth': 'Permission Bluetooth',
        'permission_storage': 'Permission Storage'
      },
    };

  String translate(String key) {
    return _localizedStrings[locale.languageCode]?[key] ?? key;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();
  @override
  bool isSupported(Locale locale) => ['en','yo','ig','ha'].contains(locale.languageCode);
  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);
  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension AppLocalizationsX on BuildContext {
  AppLocalizations get loc => AppLocalizations.of(this);
  String tr(String key) => loc.translate(key);
}
