import 'package:flutter/material.dart';

/// Simple localization with Nigerian language support.
/// TODO: Replace with flutter_localizations + ARB files for production:
///   - Add flutter_localizations to pubspec.yaml
///   - Generate .arb files in lib/l10n/
///   - Use AppLocalizations.of(context)!.translate('key')
class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ?? AppLocalizations(const Locale('en', 'US'));
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const Map<String, Map<String, String>> _localizedStrings = {
    'en': {
      'app_name': 'Sectop',
      'send_sos': 'SEND SOS',
      'tap_emergency': 'Tap for emergency alert',
      'quick_actions': 'Quick Actions',
      'safe_zones': 'Safe Zones',
      'mesh_network': 'Mesh Network',
      'messages': 'Messages',
      'first_aid': 'First Aid',
      'system_status': 'System Status',
      'cloud_connection': 'Cloud Connection',
      'connected': 'Connected',
      'offline': 'Offline',
      'location_tracking': 'Location Tracking',
      'active': 'Active',
      'inactive': 'Inactive',
      'sync_status': 'Sync Status',
      'sos_active': 'SOS Active',
      'cancel': 'Cancel',
      'ok': 'OK',
      'error': 'Error',
      'loading': 'Loading...',
      'retry': 'Retry',
      'settings': 'Settings',
      'profile': 'Profile',
      'about': 'About',
      'app_description': 'A specialized emergency system designed for high-risk security environments.',
      'help': 'Help',
      'privacy_policy': 'Privacy Policy',
      'logout': 'Logout',
      'dashboard': 'Dashboard',
      'alerts': 'Alerts',
      'emergency_contacts': 'Emergency Contacts',
      'report_incident': 'Report Incident',
      'nearby_dangers': 'Nearby Dangers',
      'safe_route': 'Safe Route',
      'language': 'Language',
      'dark_mode': 'Dark Mode',
      'notifications': 'Notifications',
      'permission_required': 'Sectop requires the following permissions to ensure your safety in critical scenarios.',
      'welcome_title': 'Welcome to Sectop',
      'welcome_description': 'This guide will help you understand how to use the app effectively for your safety and to assist others during emergencies.',
      'version': 'Sectop v',
      'about_description': 'A specialized emergency system designed for high-risk security environments.',
      // Settings screen
      'push_notifications': 'Push Notifications',
      'receive_alerts_messages': 'Receive alerts and messages',
      'appearance': 'Appearance',
      'light_mode': 'Light Mode',
      'system_default': 'System Default',
      'data_usage': 'Data Usage',
      'data_saver_mode': 'Data Saver Mode',
      'reduce_data_usage': 'Reduce data usage for maps and sync',
      'auto_download_maps': 'Auto-download Maps',
      'preload_map_tiles': 'Preload map tiles for offline use',
      'cache_management': 'Cache Management',
      'cache_size': 'Cache size',
      'clear_cache': 'Clear Cache',
      'data_management': 'Data Management',
      'delete_local_data': 'Delete Local Data',
      'clear_messages_cache': 'Clear messages, cache, and preferences (keeps account)',
      'account': 'Account',
      'delete_account': 'Delete Account',
      'permanently_remove_account': 'Permanently remove your account and data',
      'support': 'Support',
      'rate_on_play_store': 'Rate on Play Store',
      'rate_this_app': 'Rate this app and leave a suggestion',
      'contact_support': 'Contact Support',
      'how_to_use': 'How to Use',
      'learn_how_to_use': 'Learn how to use the app',
      'delete_local_data_title': 'Delete Local Data',
      'delete_local_data_message': 'This will delete all locally stored messages, cached data, and preferences. Your account (if any) will NOT be affected. This action cannot be undone.',
      'delete': 'Delete',
      'language_changed_to': 'Language changed to',
      'local_data_deleted': 'Local data deleted successfully',
      'cache_cleared': 'Cache cleared successfully',
      'could_not_open_play_store': 'Could not open Play Store',
      'contact': 'Contact',
      // Dashboard
      'home': 'Home',
      'map': 'Map',
      'inbox': 'Inbox',
      // SOS screen
      'medical_emergency': 'Medical Emergency',
      'fire': 'Fire',
      'natural_disaster': 'Natural Disaster',
      'violence_attack': 'Violence/Attack',
      'kidnapping': 'Kidnapping',
      'other': 'Other',
      'describe_emergency': 'Describe your emergency...',
      'send_sos_alert': 'Send SOS Alert',
      'sos_sent': 'SOS Sent!',
      'help_is_on_the_way': 'Help is on the way. Stay calm and stay safe.',
      'sending': 'Sending...',
      'add_evidence': 'Add Evidence',
      'capture_photo': 'Capture Photo',
      'record_video': 'Record Video',
      'record_audio': 'Record Audio',
      'evidence_captured': 'Evidence Captured',
      'sos_will_send_in': 'SOS will send in',
      'seconds': 'seconds',
      // Login screen
      'login': 'Login',
      'email': 'Email',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'dont_have_account': "Don't have an account?",
      'sign_up': 'Sign Up',
      'emergency_bypass': 'Emergency Bypass',
      'use_offline': 'Use Offline',
      // Permission screen
      'permission_title': 'Permissions Required',
      'grant_permissions': 'Grant Permissions',
      'location_permission': 'Location',
      'location_permission_desc': 'For SOS alerts and nearby danger detection',
      'notification_permission': 'Notifications',
      'notification_permission_desc': 'For emergency alerts and updates',
      'bluetooth_permission': 'Bluetooth',
      'bluetooth_permission_desc': 'For mesh network communication',
      'storage_permission': 'Storage',
      'storage_permission_desc': 'For evidence capture and offline data',
      // First Aid
      'first_aid_guide': 'First Aid Guide',
      'bleeding': 'Bleeding',
      'burns': 'Burns',
      'fractures': 'Fractures',
      'choking': 'Choking',
      'cpr': 'CPR',
      'shock': 'Shock',
      'snake_bite': 'Snake Bite',
      'emergency_numbers': 'Emergency Numbers',
      'police': 'Police',
      'ambulance': 'Ambulance',
      'fire_service': 'Fire Service',
      // Broadcast
      'broadcast': 'Broadcast',
      'create_broadcast': 'Create Broadcast',
      'broadcast_message': 'Broadcast Message',
      'send_broadcast': 'Send Broadcast',
      'target_audience': 'Target Audience',
      'everyone': 'Everyone',
      'responders_only': 'Responders Only',
      'specific_zone': 'Specific Zone',
      // Radio Broadcast
      'radio_broadcast': 'Radio Broadcast',
      'create_radio_broadcast': 'Create Radio Broadcast',
      'message_content': 'Message Content',
      'target_state': 'Target State',
      'target_lga': 'Target LGA',
      'schedule_broadcast': 'Schedule Broadcast',
      // Tip Off
      'tip_off': 'Tip Off',
      'submit_tip': 'Submit Tip',
      'anonymous_tip': 'Anonymous Tip',
      'tip_description': 'Describe what you know...',
      'tip_type': 'Tip Type',
      'suspicious_activity': 'Suspicious Activity',
      'planned_attack': 'Planned Attack',
      'wanted_person': 'Wanted Person',
      'drug_trafficking': 'Drug Trafficking',
      'other_tip': 'Other',
      // Incident Report
      'incident_report': 'Incident Report',
      'incident_type': 'Incident Type',
      'incident_description': 'Describe the incident...',
      'submit_report': 'Submit Report',
      'incident_reported': 'Incident Reported',
      'thank_you_report': 'Thank you for reporting. Authorities have been notified.',
      // Map
      'search_location': 'Search location...',
      'current_location': 'Current Location',
      'danger_zones': 'Danger Zones',
      'safe_zones_map': 'Safe Zones',
      'satellite_view': 'Satellite View',
      'street_view': 'Street View',
      // Inbox / Messages
      'no_messages': 'No messages yet',
      'type_message': 'Type a message...',
      'send': 'Send',
      'mark_as_read': 'Mark as Read',
      'delete_message': 'Delete Message',
      // Mesh Network
      'mesh_status': 'Mesh Status',
      'connected_devices': 'Connected Devices',
      'scan_for_devices': 'Scan for Devices',
      'no_devices_found': 'No devices found',
      'mesh_active': 'Mesh Active',
      'mesh_inactive': 'Mesh Inactive',
      // Threat Awareness
      'threat_awareness': 'Threat Awareness',
      'current_threat_level': 'Current Threat Level',
      'nearby_incidents': 'Nearby Incidents',
      'nearby_danger_zones': 'Nearby Danger Zones',
      'no_threats': 'No threats detected',
      'threat_alerts': 'Threat Alerts',
      'mark_all_read': 'Mark All Read',
      // Safe Route
      'plan_safe_route': 'Plan Safe Route',
      'origin': 'Origin',
      'destination': 'Destination',
      'find_safe_route': 'Find Safe Route',
      'route_found': 'Route Found',
      'no_safe_route': 'No safe route available',
      // Profile
      'edit_profile': 'Edit Profile',
      'full_name': 'Full Name',
      'phone_number': 'Phone Number',
      'email_address': 'Email Address',
      'save_changes': 'Save Changes',
      'change_password': 'Change Password',
      'current_password': 'Current Password',
      'new_password': 'New Password',
      'confirm_password': 'Confirm Password',
      // Walkie Talkie
      'walkie_talkie': 'Walkie Talkie',
      'push_to_talk': 'Push to Talk',
      'release_to_send': 'Release to Send',
      'listening': 'Listening...',
      // Zone Details
      'zone_details': 'Zone Details',
      'zone_name': 'Zone Name',
      'zone_type': 'Zone Type',
      'restricted_area': 'Restricted Area',
      'danger_area': 'Danger Area',
      'safe_area': 'Safe Area',
      'expires_at': 'Expires At',
      'created_by': 'Created By',
      // Offline Resources
      'offline_resources': 'Offline Resources',
      'download_resources': 'Download Resources',
      'downloaded': 'Downloaded',
      'not_downloaded': 'Not Downloaded',
      // Help
      'help_center': 'Help Center',
      'faq': 'FAQ',
      'report_problem': 'Report a Problem',
      'terms_of_service': 'Terms of Service',
      // Additional keys needed by screens
      'welcome_back': 'Welcome Back',
      'create_account': 'Create Account',
      'sign_in_to_access': 'Sign in to access emergency services',
      'register_for_assistance': 'Register for emergency assistance',
      'sign_in': 'Sign In',
      'already_have_account': 'Already have an account? Sign In',
      'dont_have_account_register': "Don't have an account? Register",
      'emergency_access_no_login': 'Emergency Access (No Login)',
      'use_in_disaster': 'Use in disaster situations when you cannot log in',
      'skip_login_guest': 'Skip Login — Use as Guest',
      'browse_without_account': 'Browse broadcasts, view safe zones, and access emergency info without an account',
      'contact_support_email': 'Contact Support:',
      'authentication_failed': 'Authentication failed',
      'connection_error_offline': 'Connection error. Using offline mode.',
      'failed_emergency_mode': 'Failed to enter emergency mode',
      'please_enter_name': 'Please enter your name',
      'please_enter_email': 'Please enter your email',
      'please_enter_valid_email': 'Please enter a valid email',
      'please_enter_phone': 'Please enter your phone number',
      'please_enter_password': 'Please enter your password',
      'password_min_chars': 'Password must be at least 6 characters',
      'emergency_tools': 'Emergency Tools',
      'broadcasts': 'Broadcasts',
      'radio': 'Radio',
      'data_sync': 'Data Sync',
      'syncing': 'Syncing...',
      'pending_items': 'pending items',
      'peers_connected': 'peers connected',
      'sos_sent_silently': 'SOS sent silently',
      'sos_failed': 'SOS failed:',
      'send_sos_alert_title': 'Send SOS Alert',
      'alert_type': 'Alert Type',
      'select_alert_type': 'Select alert type',
      'description_optional': 'Description (Optional)',
      'capture_evidence_optional': 'Capture Evidence (Optional)',
      'photo': 'Photo',
      'video': 'Video',
      'audio': 'Audio',
      'sending_in_seconds': 'Sending in',
      'tap_to_send_alert': 'Tap to send emergency alert',
      'ai_analyzing': 'AI analyzing description...',
      'distress_detected': '⚠ Distress signals detected!',
      'no_distress_detected': '✅ No distress detected',
      'priority': 'Priority',
      'confidence': 'confidence',
      'alert_broadcast_channels': 'Alert broadcast via all available channels',
      'your_location_sent': 'Your location will be sent with this alert. The alert will be broadcast via all available channels (cloud, Bluetooth mesh, Wi-Fi Direct, LoRa).',
      'failed_to_send_sos': 'Failed to send SOS:',
      'permissions_required': 'Permissions Required',
      'location': 'Location',
      'bluetooth': 'Bluetooth',
      'storage': 'Storage',
      'unread_messages': 'Unread Messages',
      'active_alerts': 'Active Alerts',
      'recent_messages': 'Recent Messages',
      'no_recent_messages': 'No recent messages',
      'open_inbox': 'Open Inbox',
      'unknown_sender': 'Unknown',
      'medical_info': 'Medical Info',
      'privacy_security': 'Privacy & Security',
      'stealth_mode_sos': 'Stealth Mode SOS',
      'silent_panic_trigger': 'Silent panic trigger via hardware buttons',
      'stealth_mode_description': 'When enabled, hardware triggers (Volume Up + Down) will send a silent SOS without showing any UI or making sound.',
      'close': 'CLOSE',
      'save': 'SAVE',
      'name': 'Name',
      'phone': 'Phone',
      'profile_updated': 'Profile updated',
      'medical_info_saved': 'Medical info saved',
      'blood_type': 'Blood Type',
      'allergies': 'Allergies',
      'medications': 'Medications',
      'medical_conditions': 'Medical Conditions',
      'allergies_hint': 'e.g., Penicillin, Peanuts',
      'medications_hint': 'e.g., Metformin 500mg',
      'conditions_hint': 'e.g., Diabetes, Asthma',
      'add_contact': 'Add Contact',
      'edit_contact': 'Edit Contact',
      'no_contacts': 'No emergency contacts added yet.',
      'read_privacy_policy': 'Read Privacy Policy',
      'open_full_map': 'Open Full Map',
      'zones_nearby': 'zone(s) nearby',
      'failed_to_load': 'Failed to load',
      'change_language': 'Change Language',
      'english': 'English',
      'yoruba': 'Yorùbá',
      'igbo': 'Igbo',
      'hausa': 'Hausa',
      'trapped': 'Trapped',
      'lost': 'Lost',
      'structural_damage': 'Structural Damage',
      'other_emergency': 'Other Emergency',
      'general_emergency': 'General Emergency',
      'silent_panic': 'Silent Panic',
      'stealth_sos': 'Stealth mode SOS triggered from SOS screen',
      'stealth_sos_dashboard': 'Stealth mode SOS triggered from dashboard',
      'emergency_user': 'Emergency User',
      'offline_mode': 'Offline Mode',
      'medical_info_title': 'Medical Info',
      'privacy_security_title': 'Privacy & Security',
      'edit_profile_title': 'Edit Profile',
      'emergency_contacts_title': 'Emergency Contacts',
      'about_title': 'About',
      'app_version': '1.0.0 (Nigeria Edition)',
      'sectop_description': 'A specialized emergency system designed for high-risk security environments.',
      'no_emergency_contacts': 'No emergency contacts added yet.',
      'add_contact_title': 'Add Contact',
      'edit_contact_title': 'Edit Contact',
      'contact_name': 'Name',
      'contact_phone': 'Phone Number',
      'save_contact': 'SAVE',
      'cancel_btn': 'CANCEL',
      'close_btn': 'CLOSE',
      'save_btn': 'SAVE',
      'cancel_action': 'CANCEL',
      'close_action': 'CLOSE',
      'save_action': 'SAVE',
      'permission_location': 'Location',
      'permission_notifications': 'Notifications',
      'permission_bluetooth': 'Bluetooth',
      'permission_storage': 'Storage',
      'emergency_radio': 'Emergency Radio',
      'radio_description': 'Radio reaches communities when internet is cut. Messages are converted to speech and broadcast over FM.',
      'new_broadcast': 'New Broadcast',
      'title_required': 'Title *',
      'message_required': 'Message *',
      'severity': 'Severity',
      'target_frequency': 'Target Frequency (MHz)',
      'anonymous_broadcast': 'Anonymous Broadcast',
      'broadcast_over_radio': 'Broadcast Over Radio',
      'broadcasting': 'Broadcasting...',
      'broadcast_history': 'Broadcast History',
      'no_previous_broadcasts': 'No previous broadcasts',
      'info': 'Info',
      'pidgin': 'Pidgin',
      'title_and_message_required': 'Title and message are required',
      'radio_broadcast_sent': 'Radio broadcast sent!',
      'broadcast_retried': 'Broadcast retried',
      'failed_text': 'Failed:',
      'delete_contact': 'Delete Contact',
      'delete_contact_confirm': 'Are you sure you want to delete this contact?',
      'delete_button': 'DELETE',
      'no_emergency_contacts_text': 'No emergency contacts',
      'add_contacts_notified': 'Add contacts who should be notified in an emergency',
      'tip_off_title': 'Submit Tip-Off',
      'review_tips': 'Review Tips',
      'anonymous_tip_notice': 'Your identity is protected. Anonymous tips help keep communities safe.',
      'suspicious_person': 'Suspicious Person',
      'suspicious_vehicle': 'Suspicious Vehicle',
      'hidden_weapons': 'Hidden Weapons',
      'kidnapping_plot': 'Kidnapping Plot',
      'bombing_plot': 'Bombing Plot',
      'suspicious_radio_activity': 'Suspicious Radio / Walkie-Talkie',
      'description': 'Description *',
      'required_field': 'Required',
      'target_description': 'Target Description (optional)',
      'suspect_description': 'Suspect Description (optional)',
      'location_optional': 'Location (optional)',
      'attach_evidence': 'Attach Evidence (Optional)',
      'submit_anonymously': 'Submit Anonymously',
      'identity_not_shared': 'Your identity will not be shared',
      'submitting': 'Submitting...',
      'sos_label': 'SOS',
      'help_on_way': 'Help is on the way',
      'sending_in_seconds_text': 'Sending in',
      'tap_send_emergency': 'Tap to send emergency alert',
      'tip_submitted_thanks': 'Tip submitted anonymously. Thank you.',
      'warning': 'Warning',
      'urgent': 'Urgent',
      'critical': 'Critical',
      'seconds': 'seconds',
      'describe_emergency_hint': 'Describe your emergency situation...',
    },
    'yo': {
      'app_name': 'Sectop',
      'send_sos': 'RAN SOS',
      'tap_emergency': 'Tẹ fun itaniji pajawiri',
      'quick_actions': 'Awọn iṣe iyara',
      'safe_zones': 'Awọn agbegbe ailewu',
      'mesh_network': 'Nẹtiwọọki Mesh',
      'messages': 'Awọn ifiranṣẹ',
      'first_aid': 'Iranwo akọkọ',
      'system_status': 'Ipo eto',
      'cloud_connection': 'Asopọmọra awọsanma',
      'connected': 'Asopọ',
      'offline': 'Aisi asopọ',
      'location_tracking': 'Ipilẹ ipo',
      'active': 'Ṣiṣẹ',
      'inactive': 'Aiṣiṣẹ',
      'sync_status': 'Ipo amuṣiṣẹpọ',
      'sos_active': 'SOS ṣiṣẹ',
      'cancel': 'Fagilee',
      'ok': 'O dara',
      'error': 'Aṣiṣe',
      'loading': 'N gba lati...',
      'retry': 'Tun gbiyanju',
      'settings': 'Awọn eto',
      'profile': 'Profaili',
      'about': 'Nipa',
      'app_description': 'Eto pajawiri pataki ti a ṣe apẹrẹ fun awọn agbegbe aabo eewu giga.',
      'help': 'Iranwọ',
      'privacy_policy': 'Eto imulo asiri',
      'logout': 'Ijade',
      'dashboard': 'Dasibodu',
      'alerts': 'Awọn itaniji',
      'emergency_contacts': 'Awọn olubasọrọ pajawiri',
      'report_incident': 'Jabọ iṣẹlẹ',
      'nearby_dangers': 'Awọn ewu nitosi',
      'safe_route': 'Ọna ailewu',
      'language': 'Ede',
      'dark_mode': 'Ipo dudu',
      'notifications': 'Awọn ifitonileti',
      'permission_required': 'Sectop nilo awọn igbanilaaye wọnyi lati rii daju aabo rẹ ni awọn oju iṣẹlẹ to ṣe pataki.',
      'welcome_title': 'Kaabo si Sectop',
      'welcome_description': 'Itọsọna yii yoo ran ọ lọwọ lati loye bi o ṣe le lo ohun elo naa daradara fun aabo rẹ ati lati ran awọn ẹlomiran lọwọ lakoko awọn pajawiri.',
      'version': 'Sectop v',
      'about_description': 'Eto pajawiri pataki kan ti a ṣe apẹrẹ fun awọn agbegbe aabo eewu giga.',
      'push_notifications': 'Awọn ifitonileti Titari',
      'receive_alerts_messages': 'Gba awọn itaniji ati awọn ifiranṣẹ',
      'appearance': 'Ifarahan',
      'light_mode': 'Ipo Imọlẹ',
      'system_default': 'Aiyipada Eto',
      'data_usage': 'Lilo Data',
      'data_saver_mode': 'Ipo Ifipamọ Data',
      'reduce_data_usage': 'Dinku lilo data fun awọn maapu ati amuṣiṣẹpọ',
      'auto_download_maps': 'Gba awọn maapu laifọwọyi',
      'preload_map_tiles': 'Tẹ awọn maapu tẹlẹ fun lilo offline',
      'cache_management': 'Iṣakoso Kaṣe',
      'cache_size': 'Iwọn kaṣe',
      'clear_cache': 'Nu Kaṣe',
      'data_management': 'Iṣakoso Data',
      'delete_local_data': 'Pa Data Agbegbe rẹ',
      'clear_messages_cache': 'Nu awọn ifiranṣẹ, kaṣe, ati awọn ayanfẹ (o ntọju akọọlẹ)',
      'account': 'Akọọlẹ',
      'delete_account': 'Pa Akọọlẹ rẹ',
      'permanently_remove_account': 'Yọ akọọlẹ ati data rẹ kuro patapata',
      'support': 'Atilẹyin',
      'rate_on_play_store': 'Ṣe idiyele lori Play Store',
      'rate_this_app': 'Ṣe idiyele app yii ki o fi imọran silẹ',
      'contact_support': 'Kan si Atilẹyin',
      'how_to_use': 'Bii o ṣe le Lo',
      'learn_how_to_use': 'Kọ ẹkọ bi o ṣe le lo app naa',
      'delete_local_data_title': 'Pa Data Agbegbe rẹ',
      'delete_local_data_message': 'Eyi yoo pa gbogbo awọn ifiranṣẹ ti o fipamọ ni agbegbe, data kaṣe, ati awọn ayanfẹ rẹ. Akọọlẹ rẹ (ti o ba wa) kii yoo kan. A ko le ṣe atunṣe iṣe yii.',
      'delete': 'Paarẹ',
      'language_changed_to': 'Ede ti yipada si',
      'local_data_deleted': 'Data agbegre ti paarẹ ni aṣeyọri',
      'cache_cleared': 'Kaṣe ti nu kuro ni aṣeyọri',
      'could_not_open_play_store': 'Ko le ṣii Play Store',
      'contact': 'Kan si',
      'home': 'Ile',
      'map': 'Maapu',
      'inbox': 'Apoti ifiranṣẹ',
      'medical_emergency': 'Pajawiri Iṣoogun',
      'fire': 'Ina',
      'natural_disaster': 'Ajalu Adayeba',
      'violence_attack': 'Iwa-ipa/Ikọlu',
      'kidnapping': 'Jigbe',
      'other': 'Miiran',
      'describe_emergency': 'Ṣe apejuwe ipo pajawiri rẹ...',
      'send_sos_alert': 'Fi Itaniji SOS Rán',
      'sos_sent': 'SOS Ti Firanṣẹ!',
      'help_is_on_the_way': 'Iranwọ n bọ. Jẹ́ kí o fọkàn balẹ ki o si wa lailewu.',
      'sending': 'N firanṣẹ...',
      'add_evidence': 'Fi Ẹri Kun',
      'capture_photo': 'Ya Fọto',
      'record_video': 'Gba Fidio',
      'record_audio': 'Gba Ohun',
      'evidence_captured': 'Ẹri Ti Ya',
      'sos_will_send_in': 'SOS yoo firanṣẹ ni',
      'seconds': 'aaya',
      'login': 'Wọle',
      'email': 'Imeeli',
      'password': 'Ọrọigbaniwọle',
      'forgot_password': 'Gbagbe Ọrọigbaniwọle?',
      'dont_have_account': 'Ko ni akọọlẹ?',
      'sign_up': 'Forukọsilẹ',
      'emergency_bypass': 'Fori Pajawiri',
      'use_offline': 'Lo Laisi Asopọ',
      'permission_title': 'Awọn igbanilaaye ti a beere',
      'grant_permissions': 'Funni ni Awọn igbanilaaye',
      'location_permission': 'Ipo',
      'location_permission_desc': 'Fun awọn itaniji SOS ati wiwa ewu nitosi',
      'notification_permission': 'Awọn ifitonileti',
      'notification_permission_desc': 'Fun awọn itaniji pajawiri ati awọn imudojuiwọn',
      'bluetooth_permission': 'Bluetooth',
      'bluetooth_permission_desc': 'Fun ibaraẹnisọrọ nẹtiwọọki mesh',
      'storage_permission': 'Ibi ipamọ',
      'storage_permission_desc': 'Fun gbigba ẹri ati data offline',
      'first_aid_guide': 'Itọsọna Iranwo Akọkọ',
      'bleeding': 'Ẹjẹ',
      'burns': 'Iná',
      'fractures': 'Egugun dida',
      'choking': 'Gbigbọn',
      'cpr': 'CPR',
      'shock': 'Mọnamọna',
      'snake_bite': 'Buje Ejo',
      'emergency_numbers': 'Awọn nọmba pajawiri',
      'police': 'Ọlọpa',
      'ambulance': 'Ọkọ alaisan',
      'fire_service': 'Eto ina',
      'broadcast': 'Igbohunsafefe',
      'create_broadcast': 'Ṣẹda Igbohunsafefe',
      'broadcast_message': 'Ifiranṣẹ Igbohunsafefe',
      'send_broadcast': 'Fi Igbohunsafefe Rán',
      'target_audience': 'Awọn olugbo ibi-afẹde',
      'everyone': 'Gbogbo eniyan',
      'responders_only': 'Awọn oludahun nikan',
      'specific_zone': 'Agbegbe kan pato',
      'radio_broadcast': 'Igbohunsafefe Redio',
      'create_radio_broadcast': 'Ṣẹda Igbohunsafefe Redio',
      'message_content': 'Akoonu Ifiranṣẹ',
      'target_state': 'Ipinle ibi-afẹde',
      'target_lga': 'LGA ibi-afẹde',
      'schedule_broadcast': 'Ṣeto Igbohunsafefe',
      'tip_off': 'Ifitonileti',
      'submit_tip': 'Fi Ifitonileti Rán',
      'anonymous_tip': 'Ifitonileti Ailọrukọ',
      'tip_description': 'Ṣe apejuwe ohun ti o mọ...',
      'tip_type': 'Iru Ifitonileti',
      'suspicious_activity': 'Iṣẹ Ifura',
      'planned_attack': 'Ikọlu Ti a Gbero',
      'wanted_person': 'Eniyan Ti a Fẹ',
      'drug_trafficking': 'Gbigbe Oògùn',
      'other_tip': 'Miiran',
      'incident_report': 'Iroyin Iṣẹlẹ',
      'incident_type': 'Iru Iṣẹlẹ',
      'incident_description': 'Ṣe apejuwe iṣẹlẹ naa...',
      'submit_report': 'Fi Iroyin Rán',
      'incident_reported': 'Iṣẹlẹ Ti Royin',
      'thank_you_report': 'O ṣeun fun ijabọ rẹ. A ti fi to awọn alaṣẹ leti.',
      'search_location': 'Ṣe agbekalẹ ipo...',
      'current_location': 'Ipo Lọwọlọwọ',
      'danger_zones': 'Awọn agbegbe ewu',
      'safe_zones_map': 'Awọn agbegbe ailewu',
      'satellite_view': 'Wiwo Satẹlaọti',
      'street_view': 'Wiwo Opopona',
      'no_messages': 'Ko si awọn ifiranṣẹ sibẹsibẹ',
      'type_message': 'Tẹ ifiranṣẹ sii...',
      'send': 'Fi Rán',
      'mark_as_read': 'Samisi bi a ti ka',
      'delete_message': 'Pa Ifiranṣẹ rẹ',
      'mesh_status': 'Ipo Mesh',
      'connected_devices': 'Awọn ẹrọ ti a ti sopọ',
      'scan_for_devices': 'Ṣe ayẹwo fun awọn ẹrọ',
      'no_devices_found': 'Ko si awọn ẹrọ ti a ri',
      'mesh_active': 'Mesh Ṣiṣẹ',
      'mesh_inactive': 'Mesh Aiṣiṣẹ',
      'threat_awareness': 'Akiyesi Irokeke',
      'current_threat_level': 'Ipele Irokeke Lọwọlọwọ',
      'nearby_incidents': 'Awọn iṣẹlẹ nitosi',
      'nearby_danger_zones': 'Awọn agbegbe ewu nitosi',
      'no_threats': 'Ko si awọn irokeke ti a ri',
      'threat_alerts': 'Awọn itaniji irokeke',
      'mark_all_read': 'Samisi Gbogbo bi a ti ka',
      'plan_safe_route': 'Gbero Ọna Ailewu',
      'origin': 'Ibi ti a ti bẹrẹ',
      'destination': 'Ibi ti a nlo',
      'find_safe_route': 'Wa Ọna Ailewu',
      'route_found': 'Ọna Ti Ri',
      'no_safe_route': 'Ko si ọna ailewu to wa',
      'edit_profile': 'Ṣatunkọ Profaili',
      'full_name': 'Orukọ Kikun',
      'phone_number': 'Nọmba Foonu',
      'email_address': 'Adirẹsi Imeli',
      'save_changes': 'Fi Awọn Ayipada Pamọ',
      'change_password': 'Yi Ọrọigbaniwọle Pada',
      'current_password': 'Ọrọigbaniwọle Lọwọlọwọ',
      'new_password': 'Ọrọigbaniwọle Tuntun',
      'confirm_password': 'Jẹrisi Ọrọigbaniwọle',
      'walkie_talkie': 'Walkie Talkie',
      'push_to_talk': 'Tẹ lati Sọrọ',
      'release_to_send': 'Tu silẹ lati Fi Rán',
      'listening': 'N gbọ...',
      'zone_details': 'Awọn alaye agbegbe',
      'zone_name': 'Orukọ agbegbe',
      'zone_type': 'Iru agbegbe',
      'restricted_area': 'Agbegbe ihamọ',
      'danger_area': 'Agbegbe ewu',
      'safe_area': 'Agbegbe ailewu',
      'expires_at': 'O pari ni',
      'created_by': 'Ti a ṣẹda nipasẹ',
      'offline_resources': 'Awọn orisun Laisi Asopọ',
      'download_resources': 'Gba Awọn orisun',
      'downloaded': 'Ti gba lati ayelujara',
      'not_downloaded': 'A ko gba lati ayelujara',
      'help_center': 'Ile Iranwọ',
      'faq': 'FAQ',
      'report_problem': 'Jabọ Iṣoro kan',
      'terms_of_service': 'Awọn ofin Iṣẹ',
      'welcome_back': 'Kaabo Pada',
      'create_account': 'Ṣẹda Akọọlẹ',
      'sign_in_to_access': 'Wọle lati wọle si awọn iṣẹ pajawiri',
      'register_for_assistance': 'Forukọsilẹ fun iranlọwọ pajawiri',
      'sign_in': 'Wọle',
      'already_have_account': 'Ni akọọlẹ tẹlẹ? Wọle',
      'dont_have_account_register': 'Ko ni akọọlẹ? Forukọsilẹ',
      'emergency_access_no_login': 'Wiwọle Pajawiri (Ko si Iwọle)',
      'use_in_disaster': 'Lo ni awọn ipo ajalu nigbati o ko le wọle',
      'skip_login_guest': 'Fori Iwọle — Lo bi Alejo',
      'browse_without_account': 'Wo awọn igbohunsafefe, wo awọn agbegbe ailewu, ki o wọle si alaye pajawiri laisi akọọlẹ',
      'contact_support_email': 'Kan si Atilẹyin:',
      'authentication_failed': 'Ijẹrisi kuna',
      'connection_error_offline': 'Aṣiṣe asopọ. Lilo ipo offline.',
      'failed_emergency_mode': 'Kuna lati tẹ ipo pajawiri',
      'please_enter_name': 'Jọwọ tẹ orukọ rẹ sii',
      'please_enter_email': 'Jọwọ tẹ imeeli rẹ sii',
      'please_enter_valid_email': 'Jọwọ tẹ imeeli to wulo sii',
      'please_enter_phone': 'Jọwọ tẹ nọmba foonu rẹ sii',
      'please_enter_password': 'Jọwọ tẹ ọrọmọmọ asọpọ rẹ sii',
      'password_min_chars': 'Ọrọmọmọ asọpọ gbọdọdọd kọ ó kérẹ sii ju àṣẹ 8',
      'emergency_tools': 'Awọn irinṣẹ pajawiri',
      'broadcasts': 'Awọn igbohunsafefe',
      'radio': 'Redio',
      'data_sync': 'Amuṣiṣi data',
      'syncing': 'Ìmúṣiṣi',
      'pending_items': 'Awọn nkan ti o nduro',
      'peers_connected': 'Awọn ẹlẹgbẹ ti a sopọ',
      'sos_sent_silently': 'SOS ti firanṣẹ ni ọpalọlọ',
      'sos_failed': 'SOS kuna',
      'send_sos_alert_title': 'Firanṣẹ itaniji SOS',
      'alert_type': 'Iru itaniji',
      'select_alert_type': 'Yan iru itaniji',
      'description_optional': 'Apejuwe (aṣayan)',
      'capture_evidence_optional': 'Gba ẹri (aṣayan)',
      'photo': 'Fọtọ',
      'video': 'Fidio',
      'audio': 'Ohun',
      'sending_in_seconds': 'Firanṣẹ ni {} aaya',
      'tap_to_send_alert': 'Tẹ lati firanṣẹ itaniji',
      'ai_analyzing': 'AI n ṣe itupalẹ...',
      'distress_detected': 'Wahala ti a rii',
      'no_distress_detected': 'Ko si wahala ti a rii',
      'priority': 'Pataki',
      'confidence': 'Igbagbọ',
      'alert_broadcast_channels': 'Awọn ikanni igbohunsafefe itaniji',
      'your_location_sent': 'Ipo rẹ ti firanṣẹ',
      'failed_to_send_sos': 'Kuna lati firanṣẹ SOS',
      'permissions_required': 'Awọn igbanilaaye ti a beere',
      'location': 'Ipo',
      'bluetooth': 'Bluetooth',
      'storage': 'Ibi ipamọ',
      'unread_messages': 'Awọn ifiranṣẹ ti a ko ka',
      'active_alerts': 'Awọn itaniji ti nṣiṣe lọwọ',
      'recent_messages': 'Awọn ifiranṣẹ aipẹ',
      'no_recent_messages': 'Ko si awọn ifiranṣẹ aipẹ',
      'open_inbox': 'Ṣii apoti ifiranṣẹ',
      'unknown_sender': 'Olufiranṣẹ aimọ',
      'medical_info': 'Alaye iṣoogun',
      'privacy_security': 'Aṣiri ati Aabo',
      'stealth_mode_sos': 'Ipo SOS ni ikoko',
      'silent_panic_trigger': 'Ikọlọ ọpalọlọ',
      'stealth_mode_description': 'Ipo ikoko n gba ọ laaye lati firanṣẹ itaniji laisi ṣiṣi apoti ifiranṣẹ',
      'close': 'Pa',
      'save': 'Fipamọ',
      'name': 'Orukọ',
      'phone': 'Foonu',
      'profile_updated': 'Profaili ti imudojuiwọn',
      'medical_info_saved': 'Alaye iṣoogun ti fipamọ',
      'blood_type': 'Iru ẹjẹ',
      'allergies': 'Awọn aleji',
      'medications': 'Awọn oogun',
      'medical_conditions': 'Awọn ipo iṣoogun',
      'allergies_hint': 'Fun apẹẹrẹ, Penicillin, Ẹpa',
      'medications_hint': 'Fun apẹẹrẹ, Metformin 500mg',
      'conditions_hint': 'Fun apẹẹrẹ, Àtọgbẹ, Ikọ-fèé',
      'add_contact': 'Fi olubasọrọ kun',
      'edit_contact': 'Ṣatunkọ olubasọrọ',
      'no_contacts': 'Ko si awọn olubasọrọ',
      'read_privacy_policy': 'Ka eto aṣiri',
      'open_full_map': 'Ṣii maapu ni kikun',
      'zones_nearby': 'Awọn agbegbe nitosi',
      'failed_to_load': 'Kuna lati gbe',
      'change_language': 'Yi ede pada',
      'english': 'Gẹ̀ẹ́sì',
      'yoruba': 'Yorùbá',
      'igbo': 'Igbo',
      'hausa': 'Hausa',
      'trapped': 'Idẹkùn',
      'lost': 'Pàdánù',
      'structural_damage': 'Ibajẹ igbekalẹ',
      'other_emergency': 'Pajawiri miiran',
      'general_emergency': 'Pajawiri gbogbogbo',
      'silent_panic': 'Ipayà ọpalọlọ',
      'stealth_sos': 'SOS ikoko',
      'stealth_sos_dashboard': 'SOS ikoko',
      'emergency_user': 'Olumulo pajawiri',
      'offline_mode': 'Ipo aisọpọ',
      'medical_info_title': 'Alaye iṣoogun',
      'privacy_security_title': 'Aṣiri ati Aabo',
      'edit_profile_title': 'Ṣatunkọ profaili',
      'emergency_contacts_title': 'Awọn olubasọrọ pajawiri',
      'about_title': 'Nipa',
      'app_version': 'Ẹya ohun elo',
      'sectop_description': 'Sectop jẹ ohun elo aabo agbegbe ti o fun ọ laaye lati gba awọn itaniji ati awọn imudojuiwọn lori awọn irokeke ewu',
      'no_emergency_contacts': 'Ko si awọn olubasọrọ pajawiri',
      'add_contact_title': 'Fi olubasọrọ kun',
      'edit_contact_title': 'Ṣatunkọ olubasọrọ',
      'contact_name': 'Orukọ olubasọrọ',
      'contact_phone': 'Foonu olubasọrọ',
      'save_contact': 'Fipamọ olubasọrọ',
      'cancel_btn': 'Fagilee',
      'close_btn': 'Pa',
      'save_btn': 'Fipamọ',
      'cancel_action': 'Fagilee',
      'close_action': 'Pa',
      'save_action': 'Fipamọ',
      'permission_location': 'Ipo',
      'permission_notifications': 'Awọn ifitonileti',
      'permission_bluetooth': 'Bluetooth',
      'permission_storage': 'Ibi ipamọ',
      'emergency_radio': 'Redio Pajawiri',
      'radio_description': 'Redio de awọn agbegbe nigbati intanẹẹti ba ge. Awọn ifiranṣẹ ti yipada si ọrọ ati tan kaakiri lori FM.',
      'new_broadcast': 'Igbohunsafefe Tuntun',
      'title_required': 'Akọle *',
      'message_required': 'Ifiranṣẹ *',
      'severity': 'Ibi',
      'target_frequency': 'Igbohunsafẹfẹ Ibi-afẹde (MHz)',
      'anonymous_broadcast': 'Igbohunsafefe Ailọrukọ',
      'broadcast_over_radio': 'Gbejade Lori Redio',
      'broadcasting': 'Gbigbejade...',
      'broadcast_history': 'Itan Igbohunsafefe',
      'no_previous_broadcasts': 'Ko si awọn igbohunsafefe tẹlẹ',
      'info': 'Alaye',
      'pidgin': 'Pidgin',
      'title_and_message_required': 'Akọle ati ifiranṣẹ ni a nilo',
      'radio_broadcast_sent': 'Igbohunsafefe redio ti firanṣẹ!',
      'broadcast_retried': 'Igbohunsafefe ti tun gbiyanju',
      'failed_text': 'Kuna:',
      'delete_contact': 'Pa olubasọrọ rẹ',
      'delete_contact_confirm': 'Ṣe o da ọ loju pe o fẹ pa olubasọrọ yii rẹ?',
      'delete_button': 'PARẸ',
      'no_emergency_contacts_text': 'Ko si awọn olubasọrọ pajawiri',
      'add_contacts_notified': 'Fi awọn olubasọrọ kun ti o yẹ ki a fi to leti ninu pajawiri',
      'tip_off_title': 'Fi Ifitonileti Rán',
      'review_tips': 'Ṣe Atunyẹwo Awọn Ifitonileti',
      'anonymous_tip_notice': 'Idanimọ rẹ ni aabo. Awọn ifitonileti ailọrukọ ṣe iranlọwọ lati jẹ ki agbegbe wa ni ailewu.',
      'suspicious_person': 'Eniyan Ifura',
      'suspicious_vehicle': 'Ọkọ Ifura',
      'hidden_weapons': 'Awọn ohun ija ti o farapamọ',
      'kidnapping_plot': 'Idite Jija',
      'bombing_plot': 'Idite Bombu',
      'suspicious_radio_activity': 'Redio / Walkie-Talkie Ifura',
      'description': 'Apejuwe *',
      'required_field': 'Ti a beere',
      'target_description': 'Apejuwe Ibi-afẹde (aṣayan)',
      'suspect_description': 'Apejuwe Ifura (aṣayan)',
      'location_optional': 'Ipo (aṣayan)',
      'attach_evidence': 'So Ẹri Kun (Aṣayan)',
      'submit_anonymously': 'Fi Silẹ Lailọrukọ',
      'identity_not_shared': 'Idanimọ rẹ kii yoo pin',
      'submitting': 'Fi Silẹ...',
      'sos_label': 'SOS',
      'help_on_way': 'Iranwọ n bọ',
      'sending_in_seconds_text': 'Firanṣẹ ni',
      'tap_send_emergency': 'Tẹ lati firanṣẹ itaniji pajawiri',
      'tip_submitted_thanks': 'Ifitonileti ti fi silẹ lainiduro. O ṣeun.',
      'warning': 'Ikilọ',
      'urgent': 'Pajawiri',
      'critical': 'Lominu',
      'seconds': 'aaya',
      'describe_emergency_hint': 'Ṣe apejuwe ipo pajawiri rẹ...',
      },
      'ig': {
        'app_name': 'App Name',
        'send_sos': 'Send Sos',
        'tap_emergency': 'Tap Emergency',
        'quick_actions': 'Quick Actions',
        'safe_zones': 'Safe Zones',
        'mesh_network': 'Mesh Network',
        'messages': 'Messages',
        'first_aid': 'First Aid',
        'system_status': 'System Status',
        'cloud_connection': 'Cloud Connection',
        'connected': 'Connected',
        'offline': 'Offline',
        'location_tracking': 'Location Tracking',
        'active': 'Active',
        'inactive': 'Inactive',
        'sync_status': 'Sync Status',
        'sos_active': 'Sos Active',
        'cancel': 'Cancel',
        'ok': 'Ok',
        'error': 'Error',
        'loading': 'Loading',
        'retry': 'Retry',
        'settings': 'Settings',
        'profile': 'Profile',
        'about': 'About',
        'app_description': 'A specialized emergency system designed for high-risk security environments.',
        'help': 'Help',
        'privacy_policy': 'Privacy Policy',
        'logout': 'Logout',
        'dashboard': 'Dashboard',
        'alerts': 'Alerts',
        'emergency_contacts': 'Emergency Contacts',
        'report_incident': 'Report Incident',
        'nearby_dangers': 'Nearby Dangers',
        'safe_route': 'Safe Route',
        'language': 'Language',
        'dark_mode': 'Dark Mode',
        'notifications': 'Notifications',
        'permission_required': 'Permission Required',
        'welcome_title': 'Welcome Title',
        'welcome_description': 'Welcome Description',
        'version': 'Version',
        'about_description': 'About Description',
        'push_notifications': 'Push Notifications',
        'receive_alerts_messages': 'Receive Alerts Messages',
        'appearance': 'Appearance',
        'light_mode': 'Light Mode',
        'system_default': 'System Default',
        'data_usage': 'Data Usage',
        'data_saver_mode': 'Data Saver Mode',
        'reduce_data_usage': 'Reduce Data Usage',
        'auto_download_maps': 'Auto Download Maps',
        'preload_map_tiles': 'Preload Map Tiles',
        'cache_management': 'Cache Management',
        'cache_size': 'Cache Size',
        'clear_cache': 'Clear Cache',
        'data_management': 'Data Management',
        'delete_local_data': 'Delete Local Data',
        'clear_messages_cache': 'Clear Messages Cache',
        'account': 'Account',
        'delete_account': 'Delete Account',
        'permanently_remove_account': 'Permanently Remove Account',
        'support': 'Support',
        'rate_on_play_store': 'Rate On Play Store',
        'rate_this_app': 'Rate This App',
        'contact_support': 'Contact Support',
        'how_to_use': 'How To Use',
        'learn_how_to_use': 'Learn How To Use',
        'delete_local_data_title': 'Delete Local Data Title',
        'delete_local_data_message': 'Delete Local Data Message',
        'delete': 'Delete',
        'language_changed_to': 'Language Changed To',
        'local_data_deleted': 'Local Data Deleted',
        'cache_cleared': 'Cache Cleared',
        'could_not_open_play_store': 'Could Not Open Play Store',
        'contact': 'Contact',
        'home': 'Home',
        'map': 'Map',
        'inbox': 'Inbox',
        'medical_emergency': 'Medical Emergency',
        'fire': 'Fire',
        'natural_disaster': 'Natural Disaster',
        'violence_attack': 'Violence Attack',
        'kidnapping': 'Kidnapping',
        'other': 'Other',
        'describe_emergency': 'Describe Emergency',
        'send_sos_alert': 'Send Sos Alert',
        'sos_sent': 'Sos Sent',
        'help_is_on_the_way': 'Help Is On The Way',
        'sending': 'Sending',
        'add_evidence': 'Add Evidence',
        'capture_photo': 'Capture Photo',
        'record_video': 'Record Video',
        'record_audio': 'Record Audio',
        'evidence_captured': 'Evidence Captured',
        'sos_will_send_in': 'Sos Will Send In',
        'seconds': 'Seconds',
        'login': 'Login',
        'email': 'Email',
        'password': 'Password',
        'forgot_password': 'Forgot Password',
        'sign_up': 'Sign Up',
        'emergency_bypass': 'Emergency Bypass',
        'use_offline': 'Use Offline',
        'permission_title': 'Permission Title',
        'grant_permissions': 'Grant Permissions',
        'location_permission': 'Location Permission',
        'location_permission_desc': 'Location Permission Desc',
        'notification_permission': 'Notification Permission',
        'notification_permission_desc': 'Notification Permission Desc',
        'bluetooth_permission': 'Bluetooth Permission',
        'bluetooth_permission_desc': 'Bluetooth Permission Desc',
        'storage_permission': 'Storage Permission',
        'storage_permission_desc': 'Storage Permission Desc',
        'first_aid_guide': 'First Aid Guide',
        'bleeding': 'Bleeding',
        'burns': 'Burns',
        'fractures': 'Fractures',
        'choking': 'Choking',
        'cpr': 'Cpr',
        'shock': 'Shock',
        'snake_bite': 'Snake Bite',
        'emergency_numbers': 'Emergency Numbers',
        'police': 'Police',
        'ambulance': 'Ambulance',
        'fire_service': 'Fire Service',
        'broadcast': 'Broadcast',
        'create_broadcast': 'Create Broadcast',
        'broadcast_message': 'Broadcast Message',
        'send_broadcast': 'Send Broadcast',
        'target_audience': 'Target Audience',
        'everyone': 'Everyone',
        'responders_only': 'Responders Only',
        'specific_zone': 'Specific Zone',
        'radio_broadcast': 'Radio Broadcast',
        'create_radio_broadcast': 'Create Radio Broadcast',
        'message_content': 'Message Content',
        'target_state': 'Target State',
        'target_lga': 'Target Lga',
        'schedule_broadcast': 'Schedule Broadcast',
        'tip_off': 'Tip Off',
        'submit_tip': 'Submit Tip',
        'anonymous_tip': 'Anonymous Tip',
        'tip_description': 'Tip Description',
        'tip_type': 'Tip Type',
        'suspicious_activity': 'Suspicious Activity',
        'planned_attack': 'Planned Attack',
        'wanted_person': 'Wanted Person',
        'drug_trafficking': 'Drug Trafficking',
        'other_tip': 'Other Tip',
        'incident_report': 'Incident Report',
        'incident_type': 'Incident Type',
        'incident_description': 'Incident Description',
        'submit_report': 'Submit Report',
        'incident_reported': 'Incident Reported',
        'thank_you_report': 'Thank You Report',
        'search_location': 'Search Location',
        'current_location': 'Current Location',
        'danger_zones': 'Danger Zones',
        'safe_zones_map': 'Safe Zones Map',
        'satellite_view': 'Satellite View',
        'street_view': 'Street View',
        'no_messages': 'No Messages',
        'type_message': 'Type Message',
        'send': 'Send',
        'mark_as_read': 'Mark As Read',
        'delete_message': 'Delete Message',
        'mesh_status': 'Mesh Status',
        'connected_devices': 'Connected Devices',
        'scan_for_devices': 'Scan For Devices',
        'no_devices_found': 'No Devices Found',
        'mesh_active': 'Mesh Active',
        'mesh_inactive': 'Mesh Inactive',
        'threat_awareness': 'Threat Awareness',
        'current_threat_level': 'Current Threat Level',
        'nearby_incidents': 'Nearby Incidents',
        'nearby_danger_zones': 'Nearby Danger Zones',
        'no_threats': 'No Threats',
        'threat_alerts': 'Threat Alerts',
        'mark_all_read': 'Mark All Read',
        'plan_safe_route': 'Plan Safe Route',
        'origin': 'Origin',
        'destination': 'Destination',
        'find_safe_route': 'Find Safe Route',
        'route_found': 'Route Found',
        'no_safe_route': 'No Safe Route',
        'edit_profile': 'Edit Profile',
        'full_name': 'Full Name',
        'phone_number': 'Phone Number',
        'email_address': 'Email Address',
        'save_changes': 'Save Changes',
        'change_password': 'Change Password',
        'current_password': 'Current Password',
        'new_password': 'New Password',
        'confirm_password': 'Confirm Password',
        'walkie_talkie': 'Walkie Talkie',
        'push_to_talk': 'Push To Talk',
        'release_to_send': 'Release To Send',
        'listening': 'Listening',
        'zone_details': 'Zone Details',
        'zone_name': 'Zone Name',
        'zone_type': 'Zone Type',
        'restricted_area': 'Restricted Area',
        'danger_area': 'Danger Area',
        'safe_area': 'Safe Area',
        'expires_at': 'Expires At',
        'created_by': 'Created By',
        'offline_resources': 'Offline Resources',
        'download_resources': 'Download Resources',
        'downloaded': 'Downloaded',
        'not_downloaded': 'Not Downloaded',
        'help_center': 'Help Center',
        'faq': 'Faq',
        'report_problem': 'Report Problem',
        'terms_of_service': 'Terms Of Service',
        'welcome_back': 'Welcome Back',
        'create_account': 'Create Account',
        'sign_in_to_access': 'Sign In To Access',
        'register_for_assistance': 'Register For Assistance',
        'sign_in': 'Sign In',
        'already_have_account': 'Already Have Account',
        'dont_have_account_register': "Don't have an account? Register",
        'emergency_access_no_login': 'Emergency Access No Login',
        'use_in_disaster': 'Use In Disaster',
        'skip_login_guest': 'Skip Login Guest',
        'browse_without_account': 'Browse Without Account',
        'contact_support_email': 'Contact Support Email',
        'authentication_failed': 'Authentication Failed',
        'connection_error_offline': 'Connection Error Offline',
        'failed_emergency_mode': 'Failed Emergency Mode',
        'please_enter_name': 'Please Enter Name',
        'please_enter_email': 'Please Enter Email',
        'please_enter_valid_email': 'Please Enter Valid Email',
        'please_enter_phone': 'Please Enter Phone',
        'please_enter_password': 'Please Enter Password',
        'password_min_chars': 'Password Min Chars',
        'emergency_tools': 'Emergency Tools',
        'broadcasts': 'Broadcasts',
        'radio': 'Radio',
        'data_sync': 'Data Sync',
        'syncing': 'Syncing',
        'pending_items': 'Pending Items',
        'peers_connected': 'Peers Connected',
        'sos_sent_silently': 'Sos Sent Silently',
        'sos_failed': 'Sos Failed',
        'send_sos_alert_title': 'Send Sos Alert Title',
        'alert_type': 'Alert Type',
        'select_alert_type': 'Select Alert Type',
        'description_optional': 'Description Optional',
        'capture_evidence_optional': 'Capture Evidence Optional',
        'photo': 'Photo',
        'video': 'Video',
        'audio': 'Audio',
        'sending_in_seconds': 'Sending In Seconds',
        'tap_to_send_alert': 'Tap To Send Alert',
        'ai_analyzing': 'Ai Analyzing',
        'distress_detected': 'Distress Detected',
        'no_distress_detected': 'No Distress Detected',
        'priority': 'Priority',
        'confidence': 'Confidence',
        'alert_broadcast_channels': 'Alert Broadcast Channels',
        'your_location_sent': 'Your Location Sent',
        'failed_to_send_sos': 'Failed To Send Sos',
        'permissions_required': 'Permissions Required',
        'location': 'Location',
        'bluetooth': 'Bluetooth',
        'storage': 'Storage',
        'unread_messages': 'Unread Messages',
        'active_alerts': 'Active Alerts',
        'recent_messages': 'Recent Messages',
        'no_recent_messages': 'No Recent Messages',
        'open_inbox': 'Open Inbox',
        'unknown_sender': 'Unknown Sender',
        'medical_info': 'Medical Info',
        'privacy_security': 'Privacy Security',
        'stealth_mode_sos': 'Stealth Mode Sos',
        'silent_panic_trigger': 'Silent Panic Trigger',
        'stealth_mode_description': 'Stealth Mode Description',
        'close': 'Close',
        'save': 'Save',
        'name': 'Name',
        'phone': 'Phone',
        'profile_updated': 'Profile Updated',
        'medical_info_saved': 'Medical Info Saved',
        'blood_type': 'Blood Type',
        'allergies': 'Allergies',
        'medications': 'Medications',
        'medical_conditions': 'Medical Conditions',
        'allergies_hint': 'e.g., Penicillin, Peanuts',
        'medications_hint': 'e.g., Metformin 500mg',
        'conditions_hint': 'e.g., Diabetes, Asthma',
        'add_contact': 'Add Contact',
        'edit_contact': 'Edit Contact',
        'no_contacts': 'No Contacts',
        'read_privacy_policy': 'Read Privacy Policy',
        'open_full_map': 'Open Full Map',
        'zones_nearby': 'Zones Nearby',
        'failed_to_load': 'Failed To Load',
        'change_language': 'Change Language',
        'english': 'English',
        'yoruba': 'Yoruba',
        'igbo': 'Igbo',
        'hausa': 'Hausa',
        'trapped': 'Trapped',
        'lost': 'Lost',
        'structural_damage': 'Structural Damage',
        'other_emergency': 'Other Emergency',
        'general_emergency': 'General Emergency',
        'silent_panic': 'Silent Panic',
        'stealth_sos': 'Stealth Sos',
        'stealth_sos_dashboard': 'Stealth Sos Dashboard',
        'emergency_user': 'Emergency User',
        'offline_mode': 'Offline Mode',
        'medical_info_title': 'Medical Info Title',
        'privacy_security_title': 'Privacy Security Title',
        'edit_profile_title': 'Edit Profile Title',
        'emergency_contacts_title': 'Emergency Contacts Title',
        'about_title': 'About Title',
        'app_version': 'App Version',
        'sectop_description': 'Sectop Description',
        'no_emergency_contacts': 'No Emergency Contacts',
        'add_contact_title': 'Add Contact Title',
        'edit_contact_title': 'Edit Contact Title',
        'contact_name': 'Contact Name',
        'contact_phone': 'Contact Phone',
        'save_contact': 'Save Contact',
        'cancel_btn': 'Cancel Btn',
        'close_btn': 'Close Btn',
        'save_btn': 'Save Btn',
        'cancel_action': 'Cancel Action',
        'close_action': 'Close Action',
        'save_action': 'Save Action',
        'permission_location': 'Permission Location',
        'permission_notifications': 'Permission Notifications',
        'permission_bluetooth': 'Permission Bluetooth',
        'permission_storage': 'Permission Storage',
        'emergency_radio': 'Emergency Radio',
        'radio_description': 'Radio reaches communities when internet is cut. Messages are converted to speech and broadcast over FM.',
        'new_broadcast': 'New Broadcast',
        'title_required': 'Title *',
        'message_required': 'Message *',
        'severity': 'Severity',
        'target_frequency': 'Target Frequency (MHz)',
        'anonymous_broadcast': 'Anonymous Broadcast',
        'broadcast_over_radio': 'Broadcast Over Radio',
        'broadcasting': 'Broadcasting...',
        'broadcast_history': 'Broadcast History',
        'no_previous_broadcasts': 'No previous broadcasts',
        'info': 'Info',
        'pidgin': 'Pidgin',
        'title_and_message_required': 'Title and message are required',
        'radio_broadcast_sent': 'Radio broadcast sent!',
        'broadcast_retried': 'Broadcast retried',
        'failed_text': 'Failed:',
        'delete_contact': 'Delete Contact',
        'delete_contact_confirm': 'Are you sure you want to delete this contact?',
        'delete_button': 'DELETE',
        'no_emergency_contacts_text': 'No emergency contacts',
        'add_contacts_notified': 'Add contacts who should be notified in an emergency',
        'tip_off_title': 'Submit Tip-Off',
        'review_tips': 'Review Tips',
        'anonymous_tip_notice': 'Your identity is protected. Anonymous tips help keep communities safe.',
        'suspicious_person': 'Suspicious Person',
        'suspicious_vehicle': 'Suspicious Vehicle',
        'hidden_weapons': 'Hidden Weapons',
        'kidnapping_plot': 'Kidnapping Plot',
        'bombing_plot': 'Bombing Plot',
        'suspicious_radio_activity': 'Suspicious Radio / Walkie-Talkie',
        'description': 'Description *',
        'required_field': 'Required',
        'target_description': 'Target Description (optional)',
        'suspect_description': 'Suspect Description (optional)',
        'location_optional': 'Location (optional)',
        'attach_evidence': 'Attach Evidence (Optional)',
        'submit_anonymously': 'Submit Anonymously',
        'identity_not_shared': 'Your identity will not be shared',
        'submitting': 'Submitting...',
        'sos_label': 'SOS',
        'help_on_way': 'Help is on the way',
        'sending_in_seconds_text': 'Sending in',
        'tap_send_emergency': 'Tap to send emergency alert',
        'tip_submitted_thanks': 'Tip submitted anonymously. Thank you.',
        'warning': 'Warning',
        'urgent': 'Urgent',
        'critical': 'Critical',
        'seconds': 'seconds',
        'describe_emergency_hint': 'Describe your emergency situation...'
      },
      'ha': {
        'app_name': 'App Name',
        'send_sos': 'Send Sos',
        'tap_emergency': 'Tap Emergency',
        'quick_actions': 'Quick Actions',
        'safe_zones': 'Safe Zones',
        'mesh_network': 'Mesh Network',
        'messages': 'Messages',
        'first_aid': 'First Aid',
        'system_status': 'System Status',
        'cloud_connection': 'Cloud Connection',
        'connected': 'Connected',
        'offline': 'Offline',
        'location_tracking': 'Location Tracking',
        'active': 'Active',
        'inactive': 'Inactive',
        'sync_status': 'Sync Status',
        'sos_active': 'Sos Active',
        'cancel': 'Cancel',
        'ok': 'Ok',
        'error': 'Error',
        'loading': 'Loading',
        'retry': 'Retry',
        'settings': 'Settings',
        'profile': 'Profile',
        'about': 'About',
        'app_description': 'A specialized emergency system designed for high-risk security environments.',
        'help': 'Help',
        'privacy_policy': 'Privacy Policy',
        'logout': 'Logout',
        'dashboard': 'Dashboard',
        'alerts': 'Alerts',
        'emergency_contacts': 'Emergency Contacts',
        'report_incident': 'Report Incident',
        'nearby_dangers': 'Nearby Dangers',
        'safe_route': 'Safe Route',
        'language': 'Language',
        'dark_mode': 'Dark Mode',
        'notifications': 'Notifications',
        'permission_required': 'Permission Required',
        'welcome_title': 'Welcome Title',
        'welcome_description': 'Welcome Description',
        'version': 'Version',
        'about_description': 'About Description',
        'push_notifications': 'Push Notifications',
        'receive_alerts_messages': 'Receive Alerts Messages',
        'appearance': 'Appearance',
        'light_mode': 'Light Mode',
        'system_default': 'System Default',
        'data_usage': 'Data Usage',
        'data_saver_mode': 'Data Saver Mode',
        'reduce_data_usage': 'Reduce Data Usage',
        'auto_download_maps': 'Auto Download Maps',
        'preload_map_tiles': 'Preload Map Tiles',
        'cache_management': 'Cache Management',
        'cache_size': 'Cache Size',
        'clear_cache': 'Clear Cache',
        'data_management': 'Data Management',
        'delete_local_data': 'Delete Local Data',
        'clear_messages_cache': 'Clear Messages Cache',
        'account': 'Account',
        'delete_account': 'Delete Account',
        'permanently_remove_account': 'Permanently Remove Account',
        'support': 'Support',
        'rate_on_play_store': 'Rate On Play Store',
        'rate_this_app': 'Rate This App',
        'contact_support': 'Contact Support',
        'how_to_use': 'How To Use',
        'learn_how_to_use': 'Learn How To Use',
        'delete_local_data_title': 'Delete Local Data Title',
        'delete_local_data_message': 'Delete Local Data Message',
        'delete': 'Delete',
        'language_changed_to': 'Language Changed To',
        'local_data_deleted': 'Local Data Deleted',
        'cache_cleared': 'Cache Cleared',
        'could_not_open_play_store': 'Could Not Open Play Store',
        'contact': 'Contact',
        'home': 'Home',
        'map': 'Map',
        'inbox': 'Inbox',
        'medical_emergency': 'Medical Emergency',
        'fire': 'Fire',
        'natural_disaster': 'Natural Disaster',
        'violence_attack': 'Violence Attack',
        'kidnapping': 'Kidnapping',
        'other': 'Other',
        'describe_emergency': 'Describe Emergency',
        'send_sos_alert': 'Send Sos Alert',
        'sos_sent': 'Sos Sent',
        'help_is_on_the_way': 'Help Is On The Way',
        'sending': 'Sending',
        'add_evidence': 'Add Evidence',
        'capture_photo': 'Capture Photo',
        'record_video': 'Record Video',
        'record_audio': 'Record Audio',
        'evidence_captured': 'Evidence Captured',
        'sos_will_send_in': 'Sos Will Send In',
        'seconds': 'Seconds',
        'login': 'Login',
        'email': 'Email',
        'password': 'Password',
        'forgot_password': 'Forgot Password',
        'sign_up': 'Sign Up',
        'emergency_bypass': 'Emergency Bypass',
        'use_offline': 'Use Offline',
        'permission_title': 'Permission Title',
        'grant_permissions': 'Grant Permissions',
        'location_permission': 'Location Permission',
        'location_permission_desc': 'Location Permission Desc',
        'notification_permission': 'Notification Permission',
        'notification_permission_desc': 'Notification Permission Desc',
        'bluetooth_permission': 'Bluetooth Permission',
        'bluetooth_permission_desc': 'Bluetooth Permission Desc',
        'storage_permission': 'Storage Permission',
        'storage_permission_desc': 'Storage Permission Desc',
        'first_aid_guide': 'First Aid Guide',
        'bleeding': 'Bleeding',
        'burns': 'Burns',
        'fractures': 'Fractures',
        'choking': 'Choking',
        'cpr': 'Cpr',
        'shock': 'Shock',
        'snake_bite': 'Snake Bite',
        'emergency_numbers': 'Emergency Numbers',
        'police': 'Police',
        'ambulance': 'Ambulance',
        'fire_service': 'Fire Service',
        'broadcast': 'Broadcast',
        'create_broadcast': 'Create Broadcast',
        'broadcast_message': 'Broadcast Message',
        'send_broadcast': 'Send Broadcast',
        'target_audience': 'Target Audience',
        'everyone': 'Everyone',
        'responders_only': 'Responders Only',
        'specific_zone': 'Specific Zone',
        'radio_broadcast': 'Radio Broadcast',
        'create_radio_broadcast': 'Create Radio Broadcast',
        'message_content': 'Message Content',
        'target_state': 'Target State',
        'target_lga': 'Target Lga',
        'schedule_broadcast': 'Schedule Broadcast',
        'tip_off': 'Tip Off',
        'submit_tip': 'Submit Tip',
        'anonymous_tip': 'Anonymous Tip',
        'tip_description': 'Tip Description',
        'tip_type': 'Tip Type',
        'suspicious_activity': 'Suspicious Activity',
        'planned_attack': 'Planned Attack',
        'wanted_person': 'Wanted Person',
        'drug_trafficking': 'Drug Trafficking',
        'other_tip': 'Other Tip',
        'incident_report': 'Incident Report',
        'incident_type': 'Incident Type',
        'incident_description': 'Incident Description',
        'submit_report': 'Submit Report',
        'incident_reported': 'Incident Reported',
        'thank_you_report': 'Thank You Report',
        'search_location': 'Search Location',
        'current_location': 'Current Location',
        'danger_zones': 'Danger Zones',
        'safe_zones_map': 'Safe Zones Map',
        'satellite_view': 'Satellite View',
        'street_view': 'Street View',
        'no_messages': 'No Messages',
        'type_message': 'Type Message',
        'send': 'Send',
        'mark_as_read': 'Mark As Read',
        'delete_message': 'Delete Message',
        'mesh_status': 'Mesh Status',
        'connected_devices': 'Connected Devices',
        'scan_for_devices': 'Scan For Devices',
        'no_devices_found': 'No Devices Found',
        'mesh_active': 'Mesh Active',
        'mesh_inactive': 'Mesh Inactive',
        'threat_awareness': 'Threat Awareness',
        'current_threat_level': 'Current Threat Level',
        'nearby_incidents': 'Nearby Incidents',
        'nearby_danger_zones': 'Nearby Danger Zones',
        'no_threats': 'No Threats',
        'threat_alerts': 'Threat Alerts',
        'mark_all_read': 'Mark All Read',
        'plan_safe_route': 'Plan Safe Route',
        'origin': 'Origin',
        'destination': 'Destination',
        'find_safe_route': 'Find Safe Route',
        'route_found': 'Route Found',
        'no_safe_route': 'No Safe Route',
        'edit_profile': 'Edit Profile',
        'full_name': 'Full Name',
        'phone_number': 'Phone Number',
        'email_address': 'Email Address',
        'save_changes': 'Save Changes',
        'change_password': 'Change Password',
        'current_password': 'Current Password',
        'new_password': 'New Password',
        'confirm_password': 'Confirm Password',
        'walkie_talkie': 'Walkie Talkie',
        'push_to_talk': 'Push To Talk',
        'release_to_send': 'Release To Send',
        'listening': 'Listening',
        'zone_details': 'Zone Details',
        'zone_name': 'Zone Name',
        'zone_type': 'Zone Type',
        'restricted_area': 'Restricted Area',
        'danger_area': 'Danger Area',
        'safe_area': 'Safe Area',
        'expires_at': 'Expires At',
        'created_by': 'Created By',
        'offline_resources': 'Offline Resources',
        'download_resources': 'Download Resources',
        'downloaded': 'Downloaded',
        'not_downloaded': 'Not Downloaded',
        'help_center': 'Help Center',
        'faq': 'Faq',
        'report_problem': 'Report Problem',
        'terms_of_service': 'Terms Of Service',
        'welcome_back': 'Welcome Back',
        'create_account': 'Create Account',
        'sign_in_to_access': 'Sign In To Access',
        'register_for_assistance': 'Register For Assistance',
        'sign_in': 'Sign In',
        'already_have_account': 'Already Have Account',
        'dont_have_account_register': "Don't have an account? Register",
        'emergency_access_no_login': 'Emergency Access No Login',
        'use_in_disaster': 'Use In Disaster',
        'skip_login_guest': 'Skip Login Guest',
        'browse_without_account': 'Browse Without Account',
        'contact_support_email': 'Contact Support Email',
        'authentication_failed': 'Authentication Failed',
        'connection_error_offline': 'Connection Error Offline',
        'failed_emergency_mode': 'Failed Emergency Mode',
        'please_enter_name': 'Please Enter Name',
        'please_enter_email': 'Please Enter Email',
        'please_enter_valid_email': 'Please Enter Valid Email',
        'please_enter_phone': 'Please Enter Phone',
        'please_enter_password': 'Please Enter Password',
        'password_min_chars': 'Password Min Chars',
        'emergency_tools': 'Emergency Tools',
        'broadcasts': 'Broadcasts',
        'radio': 'Radio',
        'data_sync': 'Data Sync',
        'syncing': 'Syncing',
        'pending_items': 'Pending Items',
        'peers_connected': 'Peers Connected',
        'sos_sent_silently': 'Sos Sent Silently',
        'sos_failed': 'Sos Failed',
        'send_sos_alert_title': 'Send Sos Alert Title',
        'alert_type': 'Alert Type',
        'select_alert_type': 'Select Alert Type',
        'description_optional': 'Description Optional',
        'capture_evidence_optional': 'Capture Evidence Optional',
        'photo': 'Photo',
        'video': 'Video',
        'audio': 'Audio',
        'sending_in_seconds': 'Sending In Seconds',
        'tap_to_send_alert': 'Tap To Send Alert',
        'ai_analyzing': 'Ai Analyzing',
        'distress_detected': 'Distress Detected',
        'no_distress_detected': 'No Distress Detected',
        'priority': 'Priority',
        'confidence': 'Confidence',
        'alert_broadcast_channels': 'Alert Broadcast Channels',
        'your_location_sent': 'Your Location Sent',
        'failed_to_send_sos': 'Failed To Send Sos',
        'permissions_required': 'Permissions Required',
        'location': 'Location',
        'bluetooth': 'Bluetooth',
        'storage': 'Storage',
        'unread_messages': 'Unread Messages',
        'active_alerts': 'Active Alerts',
        'recent_messages': 'Recent Messages',
        'no_recent_messages': 'No Recent Messages',
        'open_inbox': 'Open Inbox',
        'unknown_sender': 'Unknown Sender',
        'medical_info': 'Medical Info',
        'privacy_security': 'Privacy Security',
        'stealth_mode_sos': 'Stealth Mode Sos',
        'silent_panic_trigger': 'Silent Panic Trigger',
        'stealth_mode_description': 'Stealth Mode Description',
        'close': 'Close',
        'save': 'Save',
        'name': 'Name',
        'phone': 'Phone',
        'profile_updated': 'Profile Updated',
        'medical_info_saved': 'Medical Info Saved',
        'blood_type': 'Blood Type',
        'allergies': 'Allergies',
        'medications': 'Medications',
        'medical_conditions': 'Medical Conditions',
        'allergies_hint': 'e.g., Penicillin, Peanuts',
        'medications_hint': 'e.g., Metformin 500mg',
        'conditions_hint': 'e.g., Diabetes, Asthma',
        'add_contact': 'Add Contact',
        'edit_contact': 'Edit Contact',
        'no_contacts': 'No Contacts',
        'read_privacy_policy': 'Read Privacy Policy',
        'open_full_map': 'Open Full Map',
        'zones_nearby': 'Zones Nearby',
        'failed_to_load': 'Failed To Load',
        'change_language': 'Change Language',
        'english': 'English',
        'yoruba': 'Yoruba',
        'igbo': 'Igbo',
        'hausa': 'Hausa',
        'trapped': 'Trapped',
        'lost': 'Lost',
        'structural_damage': 'Structural Damage',
        'other_emergency': 'Other Emergency',
        'general_emergency': 'General Emergency',
        'silent_panic': 'Silent Panic',
        'stealth_sos': 'Stealth Sos',
        'stealth_sos_dashboard': 'Stealth Sos Dashboard',
        'emergency_user': 'Emergency User',
        'offline_mode': 'Offline Mode',
        'medical_info_title': 'Medical Info Title',
        'privacy_security_title': 'Privacy Security Title',
        'edit_profile_title': 'Edit Profile Title',
        'emergency_contacts_title': 'Emergency Contacts Title',
        'about_title': 'About Title',
        'app_version': 'App Version',
        'sectop_description': 'Sectop Description',
        'no_emergency_contacts': 'No Emergency Contacts',
        'add_contact_title': 'Add Contact Title',
        'edit_contact_title': 'Edit Contact Title',
        'contact_name': 'Contact Name',
        'contact_phone': 'Contact Phone',
        'save_contact': 'Save Contact',
        'cancel_btn': 'Cancel Btn',
        'close_btn': 'Close Btn',
        'save_btn': 'Save Btn',
        'cancel_action': 'Cancel Action',
        'close_action': 'Close Action',
        'save_action': 'Save Action',
        'permission_location': 'Permission Location',
        'permission_notifications': 'Permission Notifications',
        'permission_bluetooth': 'Permission Bluetooth',
        'permission_storage': 'Permission Storage',
        'emergency_radio': 'Emergency Radio',
        'radio_description': 'Radio reaches communities when internet is cut. Messages are converted to speech and broadcast over FM.',
        'new_broadcast': 'New Broadcast',
        'title_required': 'Title *',
        'message_required': 'Message *',
        'severity': 'Severity',
        'target_frequency': 'Target Frequency (MHz)',
        'anonymous_broadcast': 'Anonymous Broadcast',
        'broadcast_over_radio': 'Broadcast Over Radio',
        'broadcasting': 'Broadcasting...',
        'broadcast_history': 'Broadcast History',
        'no_previous_broadcasts': 'No previous broadcasts',
        'info': 'Info',
        'pidgin': 'Pidgin',
        'title_and_message_required': 'Title and message are required',
        'radio_broadcast_sent': 'Radio broadcast sent!',
        'broadcast_retried': 'Broadcast retried',
        'failed_text': 'Failed:',
        'delete_contact': 'Delete Contact',
        'delete_contact_confirm': 'Are you sure you want to delete this contact?',
        'delete_button': 'DELETE',
        'no_emergency_contacts_text': 'No emergency contacts',
        'add_contacts_notified': 'Add contacts who should be notified in an emergency',
        'tip_off_title': 'Submit Tip-Off',
        'review_tips': 'Review Tips',
        'anonymous_tip_notice': 'Your identity is protected. Anonymous tips help keep communities safe.',
        'suspicious_person': 'Suspicious Person',
        'suspicious_vehicle': 'Suspicious Vehicle',
        'hidden_weapons': 'Hidden Weapons',
        'kidnapping_plot': 'Kidnapping Plot',
        'bombing_plot': 'Bombing Plot',
        'suspicious_radio_activity': 'Suspicious Radio / Walkie-Talkie',
        'description': 'Description *',
        'required_field': 'Required',
        'target_description': 'Target Description (optional)',
        'suspect_description': 'Suspect Description (optional)',
        'location_optional': 'Location (optional)',
        'attach_evidence': 'Attach Evidence (Optional)',
        'submit_anonymously': 'Submit Anonymously',
        'identity_not_shared': 'Your identity will not be shared',
        'submitting': 'Submitting...',
        'sos_label': 'SOS',
        'help_on_way': 'Help is on the way',
        'sending_in_seconds_text': 'Sending in',
        'tap_send_emergency': 'Tap to send emergency alert',
        'tip_submitted_thanks': 'Tip submitted anonymously. Thank you.',
        'warning': 'Warning',
        'urgent': 'Urgent',
        'critical': 'Critical',
        'seconds': 'seconds',
        'describe_emergency_hint': 'Describe your emergency situation...'
      },
    };

  String translate(String key) {
    return _localizedStrings[locale.languageCode]?[key] ?? key;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();
  @override
  bool isSupported(Locale locale) => ['en','yo','ig','ha'].contains(locale.languageCode);
  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);
  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension AppLocalizationsX on BuildContext {
  AppLocalizations get loc => AppLocalizations.of(this);
  String tr(String key) => loc.translate(key);
}
