import 'package:flutter/material.dart';

/// Simple localization with Nigerian language support.
/// TODO: Replace with flutter_localizations + ARB files for production:
///   - Add flutter_localizations to pubspec.yaml
///   - Generate .arb files in lib/l10n/
///   - Use AppLocalizations.of(context)!.translate('key')
class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const Map<String, Map<String, String>> _localizedStrings = {
    'en': {
      'app_name': 'Sectop',
      'send_sos': 'SEND SOS',
      'tap_emergency': 'Tap for emergency alert',
      'quick_actions': 'Quick Actions',
      'safe_zones': 'Safe Zones',
      'mesh_network': 'Mesh Network',
      'messages': 'Messages',
      'first_aid': 'First Aid',
      'system_status': 'System Status',
      'cloud_connection': 'Cloud Connection',
      'connected': 'Connected',
      'offline': 'Offline',
      'location_tracking': 'Location Tracking',
      'active': 'Active',
      'inactive': 'Inactive',
      'sync_status': 'Sync Status',
      'sos_active': 'SOS Active',
      'cancel': 'Cancel',
      'ok': 'OK',
      'error': 'Error',
      'loading': 'Loading...',
      'retry': 'Retry',
      'settings': 'Settings',
      'profile': 'Profile',
      'about': 'About',
      'help': 'Help',
      'privacy_policy': 'Privacy Policy',
      'logout': 'Logout',
      'dashboard': 'Dashboard',
      'alerts': 'Alerts',
      'emergency_contacts': 'Emergency Contacts',
      'report_incident': 'Report Incident',
      'nearby_dangers': 'Nearby Dangers',
      'safe_route': 'Safe Route',
      'language': 'Language',
      'dark_mode': 'Dark Mode',
      'notifications': 'Notifications',
      'permission_required': 'Sectop requires the following permissions to ensure your safety in critical scenarios.',
      'welcome_title': 'Welcome to Sectop',
      'welcome_description': 'This guide will help you understand how to use the app effectively for your safety and to assist others during emergencies.',
      'version': 'Sectop v',
      'about_description': 'A specialized emergency system designed for high-risk security environments.',
    },
    'yo': {
      'app_name': 'Sectop',
      'send_sos': 'RAN SOS',
      'tap_emergency': 'Tẹ fun itaniji pajawiri',
      'quick_actions': 'Awọn iṣe iyara',
      'safe_zones': 'Awọn agbegbe ailewu',
      'mesh_network': 'Nẹtiwọọki Mesh',
      'messages': 'Awọn ifiranṣẹ',
      'first_aid': 'Iranwo akọkọ',
      'system_status': 'Ipo eto',
      'cloud_connection': 'Asopọmọra awọsanma',
      'connected': 'Asopọ',
      'offline': 'Aisi asopọ',
      'location_tracking': 'Ipilẹ ipo',
      'active': 'Ṣiṣẹ',
      'inactive': 'Aiṣiṣẹ',
      'sync_status': 'Ipo amuṣiṣẹpọ',
      'sos_active': 'SOS ṣiṣẹ',
      'cancel': 'Fagilee',
      'ok': 'O dara',
      'error': 'Aṣiṣe',
      'loading': 'N gba lati...',
      'retry': 'Tun gbiyanju',
      'settings': 'Awọn eto',
      'profile': 'Profaili',
      'about': 'Nipa',
      'help': 'Iranwọ',
      'privacy_policy': 'Eto imulo asiri',
      'logout': 'Ijade',
      'dashboard': 'Dasibodu',
      'alerts': 'Awọn itaniji',
      'emergency_contacts': 'Awọn olubasọrọ pajawiri',
      'report_incident': 'Jabọ iṣẹlẹ',
      'nearby_dangers': 'Awọn ewu nitosi',
      'safe_route': 'Ọna ailewu',
      'language': 'Ede',
      'dark_mode': 'Ipo dudu',
      'notifications': 'Awọn ifitonileti',
      'permission_required': 'Sectop nilo awọn igbanilaaye wọnyi lati rii daju aabo rẹ ni awọn oju iṣẹlẹ to ṣe pataki.',
      'welcome_title': 'Kaabo si Sectop',
      'welcome_description': 'Itọsọna yii yoo ran ọ lọwọ lati loye bi o ṣe le lo ohun elo naa daradara fun aabo rẹ ati lati ran awọn ẹlomiran lọwọ lakoko awọn pajawiri.',
      'version': 'Sectop v',
      'about_description': 'Eto pajawiri pataki kan ti a ṣe apẹrẹ fun awọn agbegbe aabo eewu giga.',
    },
    'ig': {
      'app_name': 'Sectop',
      'send_sos': 'ZIGA SOS',
      'tap_emergency': 'Pịa maka njikere mberede',
      'quick_actions': 'Omume ngwa ngwa',
      'safe_zones': 'Mpaghara nchekwa',
      'mesh_network': 'Netwọk ntupu',
      'messages': 'Ozi',
      'first_aid': 'Enyemaka mbụ',
      'system_status': 'Ọnọdụ sistemu',
      'cloud_connection': 'Njikọ igwe ojii',
      'connected': 'Ejikọrọ',
      'offline': "Anọghị n'ịntanetị",
      'location_tracking': 'Nchọta ọnọdụ',
      'active': 'Na-arụ ọrụ',
      'inactive': 'Anaghị arụ ọrụ',
      'sync_status': 'Ọnọdụ mmepekọ',
      'sos_active': 'SOS na-arụ ọrụ',
      'cancel': 'Kagbuo',
      'ok': 'Ọ dị mma',
      'error': 'Njehie',
      'loading': 'Na-ebu...',
      'retry': 'Nwaa ọzọ',
      'settings': 'Ntọala',
      'profile': 'Profaịlụ',
      'about': 'Gbasara',
      'help': 'Enyemaka',
      'privacy_policy': 'Amụma nzuzo',
      'logout': 'Wepụ',
      'dashboard': 'Dasiboodu',
      'alerts': 'Ịdọ aka ná ntị',
      'emergency_contacts': 'Kọntaktị mberede',
      'report_incident': 'Kọọ ihe merenụ',
      'nearby_dangers': 'Ihe egwu dị nso',
      'safe_route': 'Ụzọ nchekwa',
      'language': 'Asụsụ',
      'dark_mode': 'Ọnọdụ gbara ọchịchịrị',
      'notifications': 'Ngosi',
      'permission_required': "Sectop chọrọ ikike ndị a iji hụ na nchekwa gị n'ọnọdụ ndị dị oke egwu.",
      'welcome_title': 'Nnọọ na Sectop',
      'welcome_description': "Ntuziaka a ga-enyere gị aka ịghọta otu esi eji ngwa ahụ rụọ ọrụ nke ọma maka nchekwa gị na iji nyere ndị ọzọ aka n'oge ihe mberede.",
      'version': 'Sectop v',
      'about_description': 'Sistemụ mberede pụrụ iche emere maka gburugburu nchekwa dị elu.',
    },
    'ha': {
      'app_name': 'Sectop',
      'send_sos': 'AIKA SOS',
      'tap_emergency': 'Danna don faɗakarwar gaggawa',
      'quick_actions': 'Ayyuka masu sauri',
      'safe_zones': 'Wuraren aminci',
      'mesh_network': 'Cibiyar sadarwar raga',
      'messages': 'Saƙonni',
      'first_aid': 'Taimakon farko',
      'system_status': 'Matsayin tsarin',
      'cloud_connection': 'Haɗin girgije',
      'connected': 'An haɗa',
      'offline': 'Ba a haɗa',
      'location_tracking': 'Bibiyar wuri',
      'active': 'Aiki',
      'inactive': 'Rashin aiki',
      'sync_status': 'Matsayin aiki tare',
      'sos_active': 'SOS yana aiki',
      'cancel': 'Soke',
      'ok': 'Yayi',
      'error': 'Kuskure',
      'loading': 'Ana ɗauka...',
      'retry': 'Sake gwadawa',
      'settings': 'Saituna',
      'profile': 'Bayanan martaba',
      'about': 'Game da',
      'help': 'Taimako',
      'privacy_policy': 'Manufar keɓantawa',
      'logout': 'Fita',
      'dashboard': 'Dashboard',
      'alerts': 'Faɗakarwa',
      'emergency_contacts': 'Lambobin gaggawa',
      'report_incident': 'Bayar da rahoton lamari',
      'nearby_dangers': 'Hadari na kusa',
      'safe_route': 'Hanyar aminci',
      'language': 'Harshe',
      'dark_mode': 'Yanayin duhu',
      'notifications': 'Sanarwa',
      'permission_required': 'Sectop na buƙatar waɗannan izini don tabbatar da amincin ku a cikin yanayi masu mahimmanci.',
      'welcome_title': 'Barka da zuwa Sectop',
      'welcome_description': 'Wannan jagorar zai taimaka muku fahimtar yadda ake amfani da app ɗin yadda ya kamata don amincin ku da kuma taimaka wa wasu yayin gaggawa.',
      'version': 'Sectop v',
      'about_description': 'Tsarin gaggawa na musamman wanda aka tsara don yanayin tsaro mai haɗari.',
    },
  };

  String translate(String key) {
    return _localizedStrings[locale.languageCode]?[key] ?? key;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();
  @override
  bool isSupported(Locale locale) => ['en', 'yo', 'ig', 'ha'].contains(locale.languageCode);
  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);
  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
